### ISSUE TITLE
Prepare and host our first Annual General Meeting (AGM)

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#102]
Re-ticketed from #
Related issues #167 #202 #104 https://github.com/hyphacoop/handbook/issues/21 https://github.com/hyphacoop/handbook/issues/14 https://github.com/hyphacoop/handbook/issues/13

## Shared Description

:speaking_head: **Loomio:** https://loomio.hypha.coop/d/5akByK9O/agm-preparations-by-laws-etc-  
:date: **Due date:** June 30, 2020 at latest (pls revise!)  
:dart: **Success criteria:** We've run our first AGM.  

## To Do

- [x] discuss goals and visions of AGM
  - [x] wg:gov internal
  - [x] broader membership
- [x] review requirements for AGM\
  - [x] Act
  - [x] OCA Guide for the Act
- [x] finalize a date for our AGM  **May 30-31** (Sat-Sun) Rain date May 23-24 (Sat-Sun).
   - [x] select potential dates: 1.5 days, weekend end-May to first week June (**May 20-June 7**)
   - [x] poll for preferred time: https://loomio.hypha.coop/p/KaUbQxIS/when-are-you-available-for-our-first-agm-
   - [x] add to calendar and communicate Save the Date to folks (via poll)
- [x] draft [initial plan (incl. pre-work, requirements, outcomes)](https://docs.google.com/document/d/1fBm-OB_haaGEIEDGvekMA9wivjJNiA1MCP1Qf-i6QbA/edit)
   - [x] update with outcomes etc... from related gh issues
- [x] @benhylau add `agm` label on gh
- [x] discuss and agree on COVID-19 contingency plan: May 15, go/no go on in-person, second option: shift to june, third: full remote
- [x] send official **notice of AGM/member's meeting with location**:  June 1, 2020
  - [x] send guidance for WGs
- [x] request reports from WGs **June**
- [x] draft and distribute package  **June 05**
  -  agenda
  - members meeting explainer
- [x] https://github.com/hyphacoop/handbook/issues/14 have discussion/brainstorm membership **end-May**
- [x] #202 finalized peer feedback plan **beg-Jun**
- [`organizing#101`](https://github.com/hyphacoop/organizing/issues/101) write our by-laws
- [x] run the meeting
- [`organizing#307`](https://github.com/hyphacoop/organizing/issues/307) post-AGM wrap up tasks

## Road to the AGM Plan of Work

| Month    | Deadlines & Tasks                                       |
|:---------|:--------------------------------------------------------|
| January  |  **31**: date set  <br /> **31**: feedback from membership on AGM hopes  |
| February |                                                         |
| March    | **31: Q1 end**                                         |
| April    |                                                         |
| May      |  **30-31**: **ANNUAL GENERAL MEETING**                                                         |
| June     | **30: Fiscal year-end** <br /> **30: Q2 end**         |
| July     |                                                         |
| August   | 01: Incorporation anniversary <br />                    |

**Comment by dcwalk** [comment]
Adding myself to this to keep it on my radar, not meant as a claim of exclusivity

**Comment by patcon** [comment]
## Potential To Do

- [ ] prepare/present business plan. https://github.com/hyphacoop/organizing/issues/85#issuecomment-565052178

**Comment by patcon** [comment]
From `2020-01-08` all-hands, sought answers to these questions from all:

### Governance Visioning Questions (10mins)

1. Are there roles that you think we need to be successful? Which ones do you think are most important?
2. What makes a successful AGM? What is it not?

**Comment by benhylau** [comment]
1. I expect mostly in-person structured time, not sure what roles are needed other than moderator for each session. I think we can start with some hours that we chat more casually without keeping notes, then move into structured sessions where we'd have dedicated notetakers.

2. My expectation would be:
- Opportunity for all Members to raise topics, some of then can be discussed in person over structured time (can happen async and ahead)
- All Members are well prepared ahead of meeting
- Format that distributes speaking time more evenly
- Review last year's goals and set new ones moving forward

**Comment by uditvira** [comment]
Roles:
- Nothing as such, but what Ben has said above sounds good. Structured but casual feels like the vibe

Expectations:
- Review accomplishments, highlight key moments since incorporation
- Talk about things we are excited to do in the future; speak in ways that make us excited to do what we're doing
- Check in and see how we're doing with the goals/milestones we've set for the year
- Could be the time we kick-off individual goals setting activities (peer feedback is an option)
- Some social time; could also invite folks from local co-ops, neighbours etc.
- I think the location will have an impact on the tone. Would like us to think about the right place to hold this session

**Comment by benhylau** [comment]
>Could be the time we kick-off individual goals setting activities (peer feedback is an option)

+1 to this, now that we clarified this isn't happening earlier from last meeting

>Some social time; could also invite folks from local co-ops, neighbours etc.

Very interesting idea!

>location

My place should be available if needed

**Comment by garrying** [comment]
Roles:
- In the context of the AGM, a Cultivator and Notetaker. I think these roles could rotate amongst ourselves if the mode-switching isn't too much of a burden
- In operations, I don't think we followed through on what a project manager role looks like and I wonder it's still something we're thinking about
- Might be interesting to check back on current roles and see if the definitions/scope are still true and where we want to put time in

Expectations:
- Mix of structured and unstructured time
- Might be too wild: A sharable artifact that captures the spirit of the event (like a radical zine, poster, or playlist)
- +1 to location having some influence on tone. Are there places we have affinities to? What's a place that fits our mission?

**Comment by benhylau** [comment]
Thanks for all the work on this @hyphacoop/governance-wg

**Comment by dcwalk** [comment]
Great resource for using loomio for voting at virtual AGM: https://help.loomio.org/en/guides/virtual_agm/#4-use-checks-to-be-better-prepared

**Comment by dcwalk** [comment]
Ran the meeting! Follow-up in #307
