### ISSUE TITLE
Define and create a "finance" role

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#121]
Re-ticketed from https://github.com/hyphacoop/organizing/issues/70#issuecomment-538146143

## Shared Description

:speaking_head: **Loomio:** N/A  
:date: **Due date:** N/A  
:dart: **Success criteria:** A role exists for dealing with financial matters, someone occupies the role, and everyone has clarity on its scope.  

## To Do

- [x] discuss scope of role and tentative #todo items below?
- [x] decide how we want to manage access to CRA system.
  - related: https://github.com/hyphacoop/organizing/issues/111#issuecomment-538144529
- [x] seek clarity on HST status https://github.com/hyphacoop/organizing/issues/120
- [x] collect SIN/bday/phone/name/address for all employees.
  - recommendation from: accountant kickoff meeting
- [x] ensure bookkeeping process is defined https://github.com/hyphacoop/organizing/issues/122
- [x] distill tasks from https://github.com/hyphacoop/organizing/issues/121#issuecomment-554994755

**Comment by patcon** [comment]
Related: tracking audit thresholds and organizing our exemptions: https://github.com/hyphacoop/handbook/issues/13#issuecomment-538496630

**Comment by patcon** [comment]
From above handbook page:

> Finance WG is responsible for transfering money into our main Desjardins account when accumulated funds exceed a CAD 10,000 threshold.

Should prob add this to role definition

**Comment by benhylau** [comment]
Is this the same role as the person who will do payroll runs? My suggestion is for that to be a separate role.

**Comment by patcon** [comment]
> Is this the same role as the person who will do payroll runs?

I'm down for it to be separate. As I've said, I'm biased toward smaller separate roles that we rotate independently (and maybe more often), so I'm almost always :+1: on atomizing roles.

Clear scope though, ideally. Would hope for clear boundaries/interfaces between roles, not "both people watching payroll" and stuff like that, but rather "role A leads files in X directory and pokes role B when done", instead of "role A and B collab on doing process Y" (which feels messy if avoidable)

**Comment by patcon** [comment]
**Role Names:** Really hoping for roles titles with personality for some of this btw :) inspo: [Bad Idea Factory's Operating Agreement](https://github.com/BadIdeaFactory/corporate/blob/master/documents/operating.md#section-0--definitions-). Money Wizard? Treasure Goblin? This could be fun, and I hope we can inject personality into our first real role definition ❤️

EDIT: Trying to find plant-themed treasure lingo, came across LotR's [ent-draughts](https://lotr.fandom.com/wiki/Ent-draughts)

**Comment by patcon** [comment]
Maybe related. Re: yurko comments on payment methods/docs: https://matrix.to/#/!wvFLvXHaNrxWWwFOKj:tomesh.net/$1572619673633KaSVh:tomesh.net?via=tomesh.net&via=matrix.org&via=elon.li

**Comment by benhylau** [comment]
From https://github.com/hyphacoop/handbook/pull/22#issuecomment-554049511

- **Stretch** Move/integrate content into relevant sections handbook, in particular with an eye to making things like **individual role and working group responsibilities and deadlines** clear and collected in one place. e.g., 
  - move some chunk of the processes you've described into guides page (i would imagine still grouped as finances)
  - add a role that clearly documents the responsibilities for payroll person inline with cultivator to that page
  - add a "working group resp." sort of section which just like roles bullet point lists the responsibilities for that wg? (these could also take from our initial descriptions which are currently only on loomio.
  - At some point I think we'll also want something like calendar deadlines (maybe a page but probably just added to our collective calendar) for some of the things you mention.

**Comment by patcon** [comment]
Ben's comment in https://github.com/hyphacoop/organizing/issues/109#issuecomment-598152860 made me realize that we could include in the role description a minimal set of which legal (or org) docs someone in the role should be intimately familiar with, since it's maybe their responsibility to know it.

So if someone else is coming into finance role later, they'll know it involves getting familiar with docs x,y,z before stepping up.

(Not sure if this is a good or bad idea, but would maybe make onboarding into role more clear.)

- [Social Insurance Number Code of Practice: Employers' responsibilities](https://www.canada.ca/en/employment-social-development/services/sin/reports/code-of-practice/section-3.html)

**Comment by benhylau** [comment]
See https://github.com/hyphacoop/handbook/pull/69/
