### ISSUE TITLE
Determine our bookkeeping process

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#122]
Re-ticketed from https://github.com/hyphacoop/organizing/issues/70#issuecomment-538146143

## Shared Description

:speaking_head: **Loomio:** N/A  
:date: **Due date:** mid-March, 2020  
:dart: **Success criteria:** We are settled with a bookkeeping plan that we feel comfortable with, and know how who's handling it in medium term.  

Hema suggested this strategy for figuring out what we need to bookkeeping: Since 2-3 of us have bookkeeping experience, do them DIY for 1-2 months, then contact Rodica and have her review them, and make a call on if we need more support at this point. [originating meeting notes.](https://hackmd.io/@patcon/ryMxS3okB/https%3A%2F%2Fhackmd.io%2F716xTfHcQ-CSzwmcYgmtjw%3Fview?type=book)

## Open Questions

Questions for our accountant/bookkeeper (until we have a better place).

- owner loans
  - Are there tax implications to making owner loans to the co-op longer than one year? https://github.com/hyphacoop/organizing/issues/154#issuecomment-561358717
  - how should we record owner loans? Does each owner get an account in the chart of accounts, and we transfer between?
- from `2019-12-03` finance WGmeeting
  - do we need to track transferwise movements between currencies in our books?
    - @YurkoWasHere's accountant says "no".
  - is it complex is it to switch pay periods?

## To Do

- [x] sign up for quickbooks
- [x] set up our books in quickbooks
- [x] get bookkeeper set up to offer support
  - [x] contact rodica to let her know our intention.
  - [x] create calendar event for rodica's review in ~2 months
  - [x] get bookkeeper what she needs
    - [x] give access to quickbooks
    - [x] give bookkeeper access to :lock: ["Finance" GDrive folder](https://drive.google.com/drive/u/0/folders/1E7xYFNbdev-B6h4PCNH2-vArA4IA5uxN)
      - incl payroll journals and bank statement
    - ~~access to wagepoint~~ `wontdo`
    - [x] perform review
    - [x] explain our thinking on payroll we ran
    - [x] have feedback email re-sent to us
- [ ] ~~sign :lock: [agreement](https://docs.google.com/document/d/1_DfsGMjcq934IaA6vCEBUOyBbunU4gSZ/edit) with bookkeeper~~ (edit: handled in #218)
- [ ] ~~choose a person to handle bookkeeping~~ (edit: handled in #121)
- [ ] ~~document our process~~ (edit: handled in #156)

**Comment by benhylau** [comment]
Shall I go ahead and purchase [QB EasyStart](https://quickbooks.intuit.com/ca/pricing/)?

For Payroll, I think we should ask our bookkeep which of [Standard vs. Advanced](https://quickbooks.intuit.com/ca/payroll/) is more suitable. The cost for either service is about $35 per month assuming we get monthly paycheques for 7 people. This is on top of the base plan. This is a little more pricey than the $29 per month with Desjardins but I think we should keep this process independent of the financial institution where possible.

**Comment by patcon** [comment]
Candidate to dos from 2019-12-17 finance WG meeting:

- [ ] ask about statutory holidays for our pay style. recommendations?

**Comment by patcon** [comment]
More questions:
- [ ] confirm that alright to do no payroll deductions in wagepoint to start

**Comment by patcon** [comment]
things rodica needs from our 30min call:
- give access to quickbooks
- give access to wagepoint
- give payroll journal
- give bank statements
- send link to payroll mapping screen
- sign draft agreement (rodica will send hers)
  - rodica recalls $45 as rate discussed, so offered that (though current rate is $50)
  - todo confirm rate in notes

**Comment by patcon** [comment]
@hyphacoop/finance-wg since we're actually handling most bookkeeping internally, should we create a bookkeeper role for someone to explicitly own? I'm thinking this is _de facto_ Yurko rn..?

**Comment by patcon** [comment]
Also, what sort of docs should this have? Not sure what sorts of "Guides" should cover what we've been doing, if any. What are the repeating tasks we're doing in-house for bookkeepering?

- invoicing?
- expenses?
- running payroll?
- processing timesheets?

(we could use the items in our bookkeeper's contract as a guide (see link above))

**Comment by patcon** [comment]
- confirmed with bookkeeper that we don't have an HST number until we surpass $30K. 👍 from her.

**Comment by benhylau** [comment]
- [ ] @patcon: transfer relationship and introduce @benhylau as point person

**Comment by patcon** [comment]
Done! Thanks ben

**Comment by benhylau** [comment]
Have agreement with Bookkeeper on work arrangement and timeline via email. Finance role and remainder of documentation is tracked on #121 and #156. Closing this.
