### ISSUE TITLE
Create one-page summary of Hypha, our org structure, coop, and non-profit status

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/organizing#155]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

This has come up many times in meetings and conversation, so let's get rolling on it!

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** early-June
🎯 **Success criteria:** We have a document that matches/guides our shared understanding of our organization and financial arrangement as a non-share capital worker co-operative.

## To Do

- [x] Review business plan, loomio, and handbook for relevant notes
- [x] Identify and review relevant issues: #78 #95 #104 #120 #123 #133 #156 #159 #160   https://github.com/hyphacoop/handbook/issues/4
- [x] Draft document
   - [x] add one line about HST
   - [x] contractor interpretation: https://github.com/hyphacoop/organizing/issues/190 
- [x] Discuss at meeting
- [x] Verify with accountant
- [x] Consense/adopt [explainer](https://github.com/hyphacoop/handbook/pull/90/files)
- [x] Add to handbook
  - [x] initial page (see: https://github.com/hyphacoop/handbook/pull/35)
  - [x] final explainer

**Comment by dcwalk** [comment]
Concerns identified through above issues:

- more clarification about owner vs. employee vs. contractor from payroll/tax perspective, and from worker co-op requirement perspective
- are we employees or contractors?
- what does our non-profit status apply to
  - (justification for our non-profit status)
  - when are we HST exempt
- what laws govern us/should we be aware of

**Comment by dcwalk** [comment]
Some (small) bits which would be good to add to this explainer:
- Relevant [CRA NAICS](https://www.canada.ca/en/revenue-agency/services/tax/businesses/topics/sole-proprietorships-partnerships/report-business-income-expenses/industry-codes.html) code (dc thinks: [541514: Computer systems design and related services (except video game design and development)](https://www23.statcan.gc.ca/imdb/p3VD.pl?Function=getVD&TVD=380372&CVD=380376&CPV=54151&CST=01012017&CLV=4&MLV=5))
- [WSIB classification](https://www.wsib.ca/en/employer-classification-manual/), though phasing out (dc likely: [I-958-04: Software Development and Computer Services](https://www.wsib.ca/en/employer-classification-manual/software-development-and-computer-services))

**Comment by dcwalk** [comment]
Forgot about this OCA resource: https://ontario.coop/sites/default/files/STR06_For%20Profit%20and%20Not%20for%20Profit%20Co-ops.pdf

**Comment by dcwalk** [comment]
Discussion `2020-03-11` Gov WG. Waiting on @hyphacoop/finance-wg  to touch on contractor and HST, mid-April

**Comment by benhylau** [comment]
Sort #120 so this can move finish

**Comment by dcwalk** [comment]
Closing because this is DONE!
