### ISSUE TITLE
Run first payroll

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#156]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** https://github.com/hyphacoop/organizing/issues/89  
🗣 **Loomio:** N/A  
📅 **Due date:** 29 Feb 2020  
🎯 **Success criteria:** We have run our first payroll.

...

cc: @hyphacoop/finance-wg 

## To Do

- Reading [_MaRS: How to set up and process payroll in Ontario: A guide for startups_](https://learn.marsdd.com/article/setting-payroll-ontario/). Summary:
  - [x] obtain BN
  - [x] contact CRA to add a payroll (RP) "program account":
    - :mag: In CRA My Business portal, we only has an RC program account atm [[1][]]
    - Dial 1-800-959-5525: `wait > 2 (account) > 2 (payroll) > enter BN`
      - best time ~3-4pm (10-20 min)
    - ready with details from [mail-in form](https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/rc1/rc1-fill-19e.pdf) (seemed to require much less, just BN and estimates mention in below comment)
    - [x] update handbook https://github.com/hyphacoop/handbook/pull/36
    - [x] confirmed payroll program account added to CRA web portal
  - [x] ~~Register with Ontario Ministry of Finance to remit EHT~~ https://github.com/hyphacoop/organizing/issues/160 `wont-do`
  - [x] ~~Register with WSIB~~ https://github.com/hyphacoop/organizing/issues/123 `wont-do`
  - [x] determine how often we'll run payroll: monthly
    - decided at `2019-11-27` all hands meeting: https://link.hypha.coop/meetings
  - [x] decide if employees paid "to date" or "x week(s) in arrears"
  - [x] decide on third-party payroll provider: ~~QuickBooks Payroll Advanced.~~ Wagepoint.
    - consensed during 2019-12-04 all hands meeting
    - ~~leaning toward quickbooks~~
    - https://github.com/hyphacoop/organizing/issues/156#issuecomment-563401455
  - [x] enrol in service: Wagepoint.
    - [x] ~~set up quickbooks integration. [how to](https://wagepoint.kayako.com/article/58-quickbooks-online-integration)~~ (edit: bookkeeper to handle)
      - [x] Setup QuickBooks Online integration
      - [x] ~~Map your Chart of Accounts. [config page](https://secure.wagepoint.com/addons-quickbooks.cfm)~~ won't work with our account tier. https://github.com/hyphacoop/organizing/issues/156#issuecomment-578363656
      - [x] ~~Export payroll data into QuickBooks Online~~
      - [x] document this as needed (changes of chart of accounts, regular syncs, etc.)
    - [x] sign up
    - [x] add to https://link.hypha.coop/inventory
    - [x] add to https://pass.hypha.coop
    - [x] setup company profile
      - [x] determine "Doing Business As (DBA) Company Name": N/A.
      - [x] determine CRA Payroll Number
      - [x] determine remittance schedule: regular, ~~accelerated 1~~, ~~accelerated 2~~ [docs](https://www.canada.ca/en/revenue-agency/services/tax/businesses/topics/payroll/remitting-source-deductions/how-when-remit-due-dates.html#fndrmttrtyp)
      - [x] add provided company details to https://link.hypha.coop/migrations
    - [x] configure deduction types. [none required for now, but confirm with bookkeeper ]
      - might be needed for stat holiday calculations
    - [x] configure income types. only need _regular_ type pay. can delete rest, but leaving for later use.
    - [x] setup stat holiday calculations
      - [x] import public holidays as bank holiday reminders from Wagepoint
      - [x] re-read business plan section
      - [x] determine whether system supports our desires
    - [x] setup ROE authorization
      - [x] decide on contact person: patcon (Finance role holder later?)
        - [x] track person https://link.hypha.coop/migrations ("Contact Name" sheet)
      - [x] read ROE Web Agreement. [summary](https://github.com/hyphacoop/organizing/issues/156#issuecomment-565157954)
      - [x] e-sign Service Canada form
      - [x] save copy of signed agreement. [done](https://drive.google.com/file/d/0B2riIxpG2GHEWlVnd3BIakhnc25ObDZJRlRUWWg4cVJqLThB/view?usp=sharing) :lock:
    - [x] set up employees
      - [x] collect all basic info https://link.hypha.coop/employees (remaining: garry)
      - [x] collect all SIN numbers in passbolt (remaining: ~~garry,~~ udit, elon)
      - [x] invite admins
        - [x] yurko
        - [x] ben
      - [x] invite employees
        - [x] dcwalk
        - [x] elon
        - [x] garry
        - [x] udit
      - [x] urgent direct deposit
        - [x] patcon
        - [x] ben
        - [x] yurko
      - [x] store completed [federal & ON TD1 forms](https://www.canada.ca/en/revenue-agency/services/forms-publications/td1-personal-tax-credits-returns/td1-forms-pay-received-on-january-1-later.html) [gdrive](https://drive.google.com/drive/u/0/folders/12JanjbeK_oZifxpxusxJEaYKUR4b7Xul) :lock:
        - [x] patcon
        - [x] benhylau
        - [x] yurko
        - [x] dcwalk (soon)
    - [x] connect company bank account
      - [x] add account details
      - [x] determine bank signatory: @benhylau 
        - [x] add to https://link.hypha.coop/migrations ("Contact Name" sheet)
      - [x] validate account via microtransaction (waiting, 2 days)
      - [x] submit bank account verification via yodlee
      - [x] confirm successful verification (waiting, 2 days)
  - [x] decide on monthly payroll run date: 15th of the month.
  - appointment with wagepoint
    - [x] book appointment (10am Fri, Dec 13)
    - [x] prepare questions
    - [x] request starting discount
    - [x] summarize convo
- [x] run first payroll: Jan 15th, 2020

[1]: https://www.canada.ca/en/revenue-agency/services/tax/businesses/topics/changes-your-business/adding-accounts-your-business-number-bn.html

Seeking advice on CoTech forum: https://community.coops.tech/t/what-payroll-schedule-do-you-use-or-recommend/1796

**Comment by patcon** [comment]
[From chat](https://matrix.to/#/!JloFJtoONurMdgcZCa:tomesh.net/$15742900392267xjzOX:tomesh.net?via=tomesh.net&via=elon.li), @dcwalk said:

> Just making sure this doesn't get lost from [our `2019-11-20` all-hands standup] call chat, "Written Authorization" is the mechanism for witholding money on wagess: https://www.ontario.ca/document/your-guide-employment-standards-act-0/payment-wages

**Comment by patcon** [comment]
- Reading [_MaRS: How to set up and process payroll in Ontario: A guide for startups_](https://learn.marsdd.com/article/setting-payroll-ontario/). Summary:
  - [x] obtain BN
  - [ ] contact CRA to add a payroll (RP) "program account":
    - :mag: In CRA My Business portal, we only has an RC program account atm [[1]][]
  - [x] ~~Register with Ontario Ministry of Finance to remit EHT~~ https://github.com/hyphacoop/organizing/issues/160 `wont-do`
  - [x] ~~Register with WSIB~~ https://github.com/hyphacoop/organizing/issues/123 `wont-do`
  - [x] determine how often we'll run payroll: monthly
    - decided at `2019-11-27` all hands meeting: https://link.hypha.coop/meetings
  - [ ] decide if employees paid "to date" or "x week(s) in arrears"

[1]: https://www.canada.ca/en/revenue-agency/services/tax/businesses/topics/changes-your-business/adding-accounts-your-business-number-bn.html

**Comment by patcon** [comment]
Now that I've gotten around to research, this [howto info from a MaRS Discovery District startup incubator](https://learn.marsdd.com/article/setting-payroll-ontario/) offers some insight:

> ### Payroll scheduling options
> Payroll scheduling options include:
>
> - **Weekly:** This schedule is common in **very small enterprises** with many short-term, **hourly** employees
> - **Biweekly:** This practice is **most common** in knowledge-based, professional environments. The schedule is consistent and **easier to administer than monthly or semi-monthly payrolls**, especially if staff are **paid hourly**
> - **Semi-monthly:** This schedule is usually set for the fifteenth day and the last day of the month. This method can work for **salaried** employees. However, it is **cumbersome to manage for hourly** employees, as hours will vary based on the number of workdays in a given month. The **room for error is significant**
> - **Monthly:** **Rarely used**, this timeframe may sometimes be used for **more senior employees** in a company, or for **commissioned** salespeople, where performance is calculated monthly

**Comment by patcon** [comment]
Doing platform comparison here: https://docs.google.com/spreadsheets/d/16PYp0yTpHW1dp7JKf64MGoxR-Gvb_BmZ0NdzCxre61I/edit#gid=0

**Comment by patcon** [comment]
Quickbooks Online Payroll Advanced (the one we decided to go with) is actually powered by Wagepoint to do Canadian payroll. Wagepoint is a local Toronto/Halifax company.

It seems that Payroll Advanced has really bad reviews (this is just from first 3):
https://apps.intuit.com/app/apps/appdetails?shortName=wagepoint&locale=en-US

> Advanced Payroll - BIG NO - 1/5.  It is not an intuitive app, not calendar on submission date, requires you to delete an existing employee and re-enter all the information if something needs to be updated,
>
> Advacned Payroll- NO - 1/5. Tried it with one, you can't make any changes what so ever, you can't even pay an employee a bonus.
> 
> Terrible do not use ever - 1/5. this is probably the worst program I have used.

Sounds like people are having poor integration issues. Quickbooks claims with Advanced Payroll, a benefit is that "you never need to leave Quickbooks interface", but this sounds like it's actually an anti-feature.

The **pricing is identical** between Quickbooks Advanced Payroll and Wagepoint, but Quickbooks abstracts away Wagepoint's UI, which is what it is so highly reviewed for:
https://www.g2.com/products/wagepoint/reviews (4.6 out of 5)

I'm planning to register for Wagepoint and integrate into Quickbooks. We'll get more features sooner, as we won't need to wait for Quickbooks to wire them into their poor UI. Wagepoint is recognized as being a better product.

Thoughts on that?

An alternative is to sign up for Quickbooks Online _Standard_ Payroll, which is Inuit's own internal offering, which is separate. Standard and Advanced seem to use totally different backends. Main difference is that no filing are automatic on Standard.

**Comment by benhylau** [comment]
I watched:

- [Running your first payroll with Wagepoint - Canada](https://www.youtube.com/watch?v=KfLMcqGTDwE)
- [How to connect Wagepoint to Quickbooks Online](https://www.youtube.com/watch?v=Bswijbc1CPQ)

Both seem pretty straight-forward. I want to make sure that the latter integration will work for QB and Wagepoint for Canadian accounts.

I agree that QB Standard Payroll is non-ideal, and perhaps it's good to keep our payroll account decoupled from QB. QB is terrible enough that I feel we may eventually try to move off of it :)

It seems @patcon has done a lot of research into this and I'd be good for him to make the call if @YurkoWasHere is good with it.

**Comment by YurkoWasHere** [comment]
Im happy to go with whatever you guys think will make the most sense.

**Comment by YurkoWasHere** [comment]
> decide if employees paid "to date" or "x week(s) in arrears"

Where i work we "earn" vacation.  This works out well since when an employee leaves we just pay out the balance.

I will say that one of the confusing things about our setup (using qb desktop so i dont know how it will work on qb online) is that QB records vacation in $$$ (how much money do you have banked) but we all work on how many days do you have.

Issues with this setup (i think)is if a employee gets a raise then takes vacation, the company "looses" money since they are paying him more then was saved.

**Comment by patcon** [comment]
Still waiting to hear back from wagepoint, but I've called and gotten confirmation i'm in queue.

**Comment by patcon** [comment]
Called and **set up our payroll program account `RP0001` with CRA**. Here's the information I gave them, and I was very clear that these were very conservative estimates based on what was guaranteed:
- they wished to know how many employees: i said 7, but then said only 1-2 would be paid on first pay run, so they recorded **2 employees on payroll**.
- they wished to know pay period: **monthly**
- they wished to know estimated monthly payroll, and we determined it was best to be conservative with a lowball **$2,000/month total** to start.

The woman was very clear that if any of this changes, we just "tell them on that month's remittance paperwork", and **don't need to call again.**

**Comment by patcon** [comment]
## Outstanding Wagepoint Questions

- Must we track holidays as hourly employees?
- Does our bank work with wagepoint despite name discrepancy?
  - `(829) FÉDÉRATION DES CAISSES DESJARDINS DU QUÉBEC, LÉVIS, CANADA` vs `(829) La Fédération des Caisses Populaires de l’Ontario Inc.` (in Wagepoint)

**Comment by dcwalk** [comment]
RE: holiday hours, not sure interface questions, but here are requirements for pay: https://www.ontario.ca/document/your-guide-employment-standards-act-0/public-holidays#section-3

**Comment by patcon** [comment]
Have an phone appointment with Kyle David @ Wagepoint (in gcal), and I'll have explored and have my questions by then. They wish to know:

> - Are you currently using a payroll system? no
> - What are a couple of the main features you're looking to get?
>   - automatic filing, guidance on deductions, not having to think too hard about first payroll runs, QB integration, off-cycle runs, unlimited runs/month (not offered, but just to offer customer feedback), ...
> - When are you hoping to make the transition and for how many employees are you paying? asap

**Comment by patcon** [comment]
### Plain language summary of [ROE Web Consent Form](https://secure.wagepoint.com/ROE/B0051DA1-A18E-4004-B0A7-CCB7384D2ACE/ROEWeb_AgreementForm.pdf)

- ROE = Record of Employment
- this is a Service Canada form that Wagepoint files for us
- Wagepoint must:
  - provide us a copy of everything they submit for us (this agreement, any regular ROE filings, etc.)
- Hypha must:
  - keep a digital copy of the agreement
  - take full responsibility for keeping Wagepoint records accurate
  - will immediate report any inaccuracies to Wagepoint
  - keep a digital copy of all ROEs
- we all keep our records for **6 years** (after end of year) [as per law](https://laws-lois.justice.gc.ca/eng/acts/E-5.6/page-19.html?txthl=six%20years#s-87)

**Comment by patcon** [comment]
### Call with Wagepoint sales agent

- all fees included with Wagepoint (other platforms add one-off fees for irregular filings)
- recommends we aim to do **first payroll run with Wagepoint for January 15th**
  - due to holidays and some novel aspects about the final payroll of the year
  - "there will be no year-end W2 if we run at end-of-month"
  - if we need to run a payroll sooner, suggested that our bookkeeper or accountant could help us run a one-off, and start the year fresh in Wagepoint
- connecting me to onboarding specialist, who can answer our specific questions about setup

**Comment by benhylau** [comment]
@patcon they seem helpful :) I am +1 to Jan 15 payroll to avoid future complexity if you're okay with

**Comment by patcon** [comment]
- only 2 cases in 12 years where WSIB gave an exemption

**Comment by dcwalk** [comment]
@patcon is the comment above relevant in this issue ^ or #123 or #159?
Not sure the source you identify, but curious if you reviewed the material I've posted elsewhere?

**Comment by patcon** [comment]
Those ref issues look right. Was just recording the wagepoint support person's advice (she's a long-term payroll staff), and didn't have time to further process before my cafe closed :)

**Comment by patcon** [comment]
Holy jeez. We're def committed to Wagepoint at this point, but fwiw, this Canadian platform is **free for unlimited, any-time payroll runs**. Their **Rise People** HR platform didn't have a "pricing" page when I was looking, just "book a demo", so I missed this link:
https://risepeople.com/small-business/

> I have **20 employees or less**. Great, that means you’re eligible for **free payroll**!
>
> Our easy-to-use online system saves you tons of time and makes your life easier by automating your T4s, CRA remittances and ROEs so you don’t have to!
>
> You can pay your employees any time. **Run payroll as many times as you need**, at your convenience. You can make **off-cycle** payments, cancel a pay run, or give a bonus on the spot without having to make tax calculations.

Anyhow, not going back on Wagepoint now -- Rise has obvious downsides of lacking QB integration anyhow -- but interesting

**Comment by dcwalk** [comment]
Called WSIB per todo above and confirmed we are in a "by application" (read: optional) industry, summarized in #123

**Comment by patcon** [comment]
# Candidate To Dos

From 2019-12-17 finance WG meeting.

- [ ] explore new CRA payroll program account

**Comment by patcon** [comment]
- Filling out the [Federal TD1 worksheet](https://www.canada.ca/en/revenue-agency/services/forms-publications/td1-personal-tax-credits-returns/td1-forms-pay-received-on-january-1-later/td1-ws.html):
  - Only look at this if any of the following apply:
    - you are 65+ years old
    - you are a legal caregiver for dependants
- Filling out the [Federal TD1](https://www.canada.ca/en/revenue-agency/services/forms-publications/td1-personal-tax-credits-returns/td1-forms-pay-received-on-january-1-later/td1.html)
  - personal basic 
  - "employee number" is not required to dedup us and so we can leave it blank. [[?]](https://www.reddit.com/r/PersonalFinanceCanada/comments/c5kx95/employee_number_on_td1_form/)
 - we keep SIN in passbolt, so suggest that we can optionally leave it blank for now
  - need to sign, so maybe need to print and scan fully completed, incl SIN
- Filling out the [TD1-ON form](https://www.canada.ca/en/revenue-agency/services/forms-publications/td1-personal-tax-credits-returns/td1-forms-pay-received-on-january-1-later/td1on.html)
  - only need if your TD1 total claim was more than personal basic amount (mine wasn't)
- Filling out the [Ontario TD1-ON worksheet](https://www.canada.ca/en/revenue-agency/services/forms-publications/td1-personal-tax-credits-returns/td1-forms-pay-received-on-january-1-later/td1on-ws.html)
  - if needed to complete TD1-ON, only look at this if any of the following apply:
    - you are 65+ years old
    - you are a legal caregiver
    - you have depedants
    - you have a spouse/commonlaw partner with low income

Signed and stored completed TD1 and TD1ON forms [in a private GDrive folder](https://drive.google.com/drive/u/0/folders/12JanjbeK_oZifxpxusxJEaYKUR4b7Xul) :lock:

**Comment by patcon** [comment]
Added todos for setting up direct deposit, if you could add that to your docket for this week @benhylau :rocket:

**Comment by patcon** [comment]
**DECISION** via @hyphacoop/finance-wg chat room: We will not have **employee numbers or IDs** as an organization unless compelled. cc @hyphacoop/governance-wg

**Comment by benhylau** [comment]
Direct deposit on Wagepoint and TD forms on Drive, done. Thanks for the ping @patcon

**Comment by patcon** [comment]
This seems mega useful for mapping chart of accounts: https://quickbooks.intuit.com/learn-support/en-ca/employees-payroll/how-to-map-the-chart-of-accounts-before-running-advanced-payroll/00/261440

**Comment by benhylau** [comment]
I would like the payroll process to not depend on the amounts or timelines that we collect on invoices. There are a couple reasons:

- Exchange rate fluctuations and transaction costs (e.g. unexpected transaction costs are business costs, optimizations are business savings, late payments are business risks) and they should be absorbed by the business to provide stability to the employee

    - From https://handbook.hypha.coop/finance.html#calculating-member-wages

        >The amount is calculated based on the invoiced amount before transaction costs.

        Costs of collection, such as receiving a wire or currency exchange, is a cost that the Hypha collective absorbs.

- Invoice collection timelines and pay periods happen on independent threads
    - Legally I believe the employer (Hypha) has to pay for work rendered in a period to its employees , regardless of whether the business is successful in collecting the invoice in time
    - Having to look at the invoice amount to back figure out how much the effective hourly rate is each time will be a huge overhead, especially when invoice periods don't line up nicely with payroll periods. Instead the payroll calculation should take as input: employee timesheet + project rate, and be able to spit out pay numbers for the current cycle

I have created a [sheet](https://docs.google.com/spreadsheets/d/1O2ZZzRanUNYYt0Uq2WBi2wpUOpoCqWStbDyz1ZhRZ8k/edit#gid=987160937) to show how this can be done for the current cycle, and left comments in some cells to clarify.

I also think we can go ahead with what @patcon has for this cycle and discuss my proposal at the next Finance WG meeting / All Hands, because we can easily plug his numbers into this proposal if we decide to go with it. It just means the `project rate` for this cycle will be an effective rate that @patcon's method came up with.

**Comment by YurkoWasHere** [comment]
I think hedging the conversion rate by setting a hourly rate that its 25% (clip) + few % below what we would typically get paid would make calculations of payroll when it gets more complicated easier.  

We will have to keep an eye on that exchange rate to make sure it does not dip to far into the "clip"  (or maybe even too far away from it) and at that point re-adjust.

This will be a necessary method in the future if we have to ever "dip" into the "reserve fund" to pay an employee before a client actually sends the cheque as we cannot predict what the rate till be.

IE this round, December hours was not yet processed but COULD have still been paid if the above was done, but now its depended on collecting the money first.

**Comment by patcon** [comment]
@YurkoWasHere and I realized last night that the mapping is only important after the payroll run is created. The mapping allows the quickbooks integration to export details to quickbooks. So while it's important, it can be run after.

**Comment by patcon** [comment]
Had a call with wagepoint today.

## Call Notes

- summary of mindset for payroll
  - need to meet minimum requirements
  - need to pay percent to government on wages
  - the rest is about keeping employees happy and informed and with sense of fairness. often involves very fuzzy trade-offs ("we're offering 5% vacation instead of 4% required, but in exchange we're saying that you can't take vacation in the 4 weeks before xmas")
- annualizing stat holiday pay is not normal or especially recommended in longterm, but possible, and if doing, just document clearly
- any special conditions or shorthand calculations (e.g., 4% annualized stat holiday calculations for sporadic work) should be written down in employee handbook and signed off on
  - the is less important for owners, but very important for first non-owner hire
- was walked through how to use "jobs" and "departments" feature of wagepoint to set up "hourly" and "salary" departments
  - this allows us to give people various jobs with different hourly rates
  - since stat holidays are calculated here, i believe this is more intended for hours worked in the month itself, not for hours worked months before, or when a month's hours can't be paid due to client not paying yet.
- regardless of salary or hourly pay style, entering proper "hours" in payroll screens in important. e.g., can't simply push 173.33 for each person, even yurko who's only paid for 5 hours this run -- that would look like he was paid way below minimum

**Comment by patcon** [comment]
New information: **QBO "Easy Start" plan ($20/mo) doesn't support Wagepoint syncing**, only "Essentials" ($35/mo) and above does. (This was not documented, and Wagepoint is updating its docs.)

**Comment by benhylau** [comment]
## Tasks remaining

- [ ] Document the decisions made in previous meeting (e.g. if employees paid "to date" or "x week(s) in arrears") @benhylau 
- [ ] Document vacation and stat holiday policy @benhylau  
- Guides @patcon (due Feb 21)
    - [ ] Process to add employee @patcon
    - [ ] Process to run payroll @patcon 
    - [ ] Wagepoint <-> QB process @patcon 
- [ ] Collect people's SIN and TD forms (after pc documents the process, ben can follow) @benhylau

**Comment by patcon** [comment]
garry sent me his basic info and SIN, so it's in our system. ( @benhylau  if you'd prefer i didn't tread when something came to me from before, just say so)

**Comment by patcon** [comment]
Ok, so here's a rundown of the process for adding a new employee/worker:
https://hackmd.io/qwgEqqkGRc-gEso6rM12uw?view

And here's a general process for onboarding a new worker (mainly employee), which seemed to make sense to think about while working  on this: https://hackmd.io/wdNLfu84RoGaovhDbpLvBQ?view

Checklist for running payroll itself is incoming before bed.

**Comment by patcon** [comment]
Also, in running through this, I realized that perhaps we _do_ need to submit a blank payroll through wagepoint in order for them to process our "nil remittance": https://www.canada.ca/en/revenue-agency/services/tax/businesses/topics/payroll/remitting-source-deductions/report-nil-remittance-when-report.html

(I'm not seeing their system mention anything being sent [in their system](https://secure.wagepoint.com/remittanceReport#), but the Wagepoint support docs say we can confirm remittance in CRA MY Business portal. I suspect we'll want to submit a manual nil remittance through CRA My Business portal, and seems from above link that this must be within 2 months.

**Comment by patcon** [comment]
Here's the docs for running payroll, though I think we might want to run it differently this coming time. We processed it as "Salaried" last time, but hourly might make more sense after this first run-through, and seeing how it could work: https://hackmd.io/ru71u6cCRUevyAoFB0k5JQ?view

**Comment by benhylau** [comment]
## Public holidays

Relevant sections from https://www.ontario.ca/document/your-guide-employment-standards-act-0/public-holidays#section-1

### A. Calculating public holiday pay for variable hours of work per period

> Example: When there are no set hours and each pay cheque includes vacation pay
>
> Bertie does not work a set number of hours per day or days per week. Her pay varies from week to week, according to the time she has worked. She and her employer have agreed in writing that she will receive four per cent vacation pay on each pay cheque.
>
> 1. First, Bertie's regular wages earned during the four work weeks before the holiday are:
    $1,500 regular wages<
> 2. Second, her vacation pay payable is calculated:
    $1,500 X 4% = $60
> 3. Then her regular wages earned and vacation pay payable are added together:
    $1,500 + $60 = $1,560
> 4. Bertie's total wages earned and vacation pay payable are then divided by 20:
    $1,560 / 20 = $78
>
> Result: Bertie is entitled to $78 public holiday pay.

### B. Employee work on a public holiday

> When an employee who qualifies for the day off has agreed electronically or in writing to work on a public holiday
>
> Most employees have the right to get the public holiday off and get paid public holiday pay. However, if an employee agrees electronically or in writing to work on the public holiday, there are two options:
>
> - the employee is entitled to receive regular wages for all hours worked on the public holiday, plus a substitute day off work with public holiday pay;
>
> or
>
> - if the employee agrees electronically or in writing, they are entitled to public holiday pay for the public holiday plus premium pay for all hours worked on the public holiday. In this case, the employee will not be given a substitute day off.

### Summary

We maintain the recommendation for employees to _not_ work on a public holiday, but in the case where employees choose to do or under unexpected circumstances, here is how we'd handle it.

We will pay public holiday pay according to (A) on each paycheque, and then pay regular wages according to (B), where the "substitute day" is already included in the distributed amount (A). We will have this in the employment agreement (i.e. "in writing") that when employees decide to work on a public holiday they are agreeing to this policy, and with no expectation of "public holiday plus premium pay".

**Comment by benhylau** [comment]
https://github.com/hyphacoop/handbook/pull/53 is ready for review and resolves this ticket.
