### ISSUE TITLE
Research health insurance options

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#158]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** Those who would like insurance have easy access to it, either through the co-op or through conversations facilitated by co-op members.

- [CWCF: Member Benefits](https://canadianworker.coop/join/member-benefits/) ("Group Plans" section)

## To Do

- [ ] determine interest in a group buy
- research
  - [x] investigate Member Benefit Plan vs Co-op Guard
  - [ ] call Member Benefits plan contact: [Jason Bird](https://www.cooperators.ca/local/rjb-insurance-group)
  - [ ] email Co-op Guard group plan contact: StrategicClientManagement@cooperators.ca
  - [ ] email Kaye at CWCF: communications@canadianworker.coop
  - [ ] ...
- [ ] ...

**Comment by patcon** [comment]
Realized I need to be investigating this for myself in order for the coming year, and so figured I might as well investigate through CWCF and document for others as well.

- Member Benefit Plan = individual plans through CWCF
- Co-op Guard = group plans for full org

**Comment by dcwalk** [comment]
@patcon we did some early costing/discussion of this around business plan and I think we should look at a broader set of options if we are going to research this, including HCSA-only, or costing out private plans($60-100/mth i believe) and how that compares to group options.

**Comment by patcon** [comment]
Note: feels maybe like operations.
