### ISSUE TITLE
Working group year-end summary

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/organizing#164]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** Each working group to [share here](https://hackmd.io/Y9lEw0WtQPielG3Q3qCTuQ) a short year-end summary to wrap up accomplishment of 2019  

## To Do

Year-end summary added:

- [x] @hyphacoop/business-planning-wg 
- [x] @hyphacoop/finance-wg
- [x] @hyphacoop/governance-wg 
- [x] @hyphacoop/infra-ops-wg

**Comment by benhylau** [comment]
@hyphacoop/member-workers next week's stand-up has been extended to a 45 min call on our shared calendar.

**Comment by dcwalk** [comment]
These were added to the notes for the last meeting of the year, which we had. Closing as done!
