### ISSUE TITLE
Revisit/update business plan before AGM

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/organizing#167]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

Business planning WG spent a long portion of 2019 researching and preparing an initial business plan. It was shared out with the full co-op and an initial plan was adopted (with elements still in proposal form) on Dec 12, 2019 in the business planning WG. We agreed on the following steps relevant to this issue:

- give the doc a rest until AGM
- consult with external group closer to AGM
- aim for formal distribution/discussion at AGM

🎟️ **Re-ticketed from:** #85
🗣 **Loomio:** N/A  
📅 **Due date:** Prior to AGM, 2020 Q1
🎯 **Success criteria:** Revised business plan ready for discussion at AGM 

## To Do

- [x] discuss as part of bizdev co-work for AGM prep
- [x] archive initial business plan
- [x] @dcwalk ensure active policies/key language has been transferred to handbook
  - https://github.com/hyphacoop/handbook/pull/82
  - https://github.com/hyphacoop/handbook/pull/83
  - ... (more)
- [x] @dcwalk remove proposals in business plan (move to separate place): https://docs.google.com/document/d/1ZzoP2NbJxKWUW_-vN5H5e3RDbt8iJqhp_WWoBPoOSxM/edit#
- [x] @uditvira update business plan
-  ~seek review from [a local small business development centre](https://loomio.hypha.coop/d/sWnNveKO/public-communication-spaces#undefinedsmall-business-development-centres)~

**Comment by dcwalk** [comment]
Happened! post-AGM tasks in #308
