### ISSUE TITLE
Upgrade business phone number

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#168]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:**   
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** We have a business number we are comfortable using going forward and our service providers have it on file.  

## To Do

- [x] resolve issues with freephoneline.ca `urgent`
  - [x] re-activate existing hypha number -- @YurkoWasHere 
  - [x] re-enable voicemail to email -- @ASoTNetworks 
  - [x] re-record voicemail prompt on freephoneline.ca -- @dcwalk 
- [x] decide next steps

cc: @hyphacoop/infra-ops-wg

**Comment by patcon** [comment]
- :mag: Freephoneline.ca is run by Fongo.
- :mag: We currently use the free version.
  - :mag: We were using a neat trick that may have recently stopped working.
- :mag: Fongo Home is $5/month.
- :mag: Fongo also offers ["Fongo Works" for business](https://www.fongo.com/fongoworks/).
  - :mag: There's a free version.
    - :mag: It only works through their app, not direct VOIP access.
    - :mag: Their app supports up to 6 users
  - :mag: Fongo Works Pro is $10/month.
    - :mag: Allows access to VOIP credentials.
- :mag: Fongo is for "his/her own personal, residential use" -- [Fongo Terms & Conditions](https://www.fongo.com/legal/terms/)

**Comment by benhylau** [comment]
Since we're deciding on a paid option, we may wish to get one that can receive SMS and turn them into emails to our shared address in order to deal with 2-factor services for shared accounts. Not a hard requirement but hope @hyphacoop/infra-ops-wg will consider this.

**Comment by ASoTNetworks** [comment]
I also have been using Voip.ms for a while now and so far have no issues with it.

If we decided to use this we can have one number for both voicemail and Jitsi calls. 
For example you dial 2244 (call) before the voicemail prompt is ended it will forward you to the jitsi system and if nothing is entered you go to voicemail.

I just tested the SMS and it can set it to forward to our shared email.

And from what I know you only pay the porting into a provider and the old provider shouldn't charge anything.

**Comment by YurkoWasHere** [comment]
> Since we're deciding on a paid option,

There is also a non-paid option for now. It's to simple make an outgoing call every month.  This is for redundancy as they need a call every 90 days.  I will setup a reminder for the time being to do this.

>  we may wish to get one that can receive SMS and turn them into emails to our shared address in order to deal with 2-factor services for shared accounts.

I will also point out the MANY MANY service do NOT allow the use of known VOIP numbers for sms confirmation.  We got lucky for Waywise, but for example FreePhoneLine won't allow a VOIP based number to be used.

If you want to go down this path i would suggest getting a CELL number and porting it in.  This would mask the number better and give a better chance of it being accepted my most providers.

Personally i would rather wait and figure out what exactly we want form the telephone then starting to pay monthly fees for something we will probably not be using.

> And from what I know you only pay the porting into a provider and the old provider shouldn't charge anything.

You are right, normally. With Freephoneline there is a fee if the account is less than 90 days old.  This means we cant do this for a while or we have to pay. 
(Actually im not sure if even then it would be free. Details are a bit confusing)
Source https://support.freephoneline.ca/hc/en-us/articles/212430626-Transfer-my-Freephoneline-number-to-another-carrier

> For example you dial 2244 (call) before the voicemail prompt is ended it will forward you to the jitsi system and if nothing is entered you go to voicemail.

Don't think you can do this within voip.ms, voicemails don't have a IVR option built in. I would rather not have to lean on yet another self hosted service if we don't have to.

**Comment by YurkoWasHere** [comment]
Point of clarifications

There where TWO DIFFERNT numbers that we had a problem onl.

One was NOT Official, was for testing purposes and was shutdown because of the way we where using it.

The main HYPHA number  was disconnected due to inactivity, and there is a way to correct that.

**Comment by patcon** [comment]
> @YurkoWasHere: If you want to go down this path i would suggest **getting a CELL number and porting it in**. This would mask the number better and give a better chance of it being accepted my most providers.

:+1: for this when we seek long-term number.

:+1: what @ASoTNetworks said on voip.ms. :+1: what @benhylau said about SMS 2FA. And :+1: 

Voip.ms is what we use for the hacknight event doorbell. Allows any of (1) receiving incoming SMS via email, (2) sending incoming SMS to callback url, or (3) send outgoing SMS via API. [`CivicTechTO/hubot-sms-doorbell`](https://github.com/CivicTechTO/hubot-sms-doorbell/blob/master/README.md) uses (2) and (3).

:mag: If we transfer before Mar 15, there's a $25 fee. None after.

> @YurkoWasHere: Personally i would rather wait and figure out what exactly we want form the telephone then starting to pay monthly fees for something we will probably not be using.

:+1: Agreed.

###  Nice-to-haves

Running list of things we're tried to do or wished for.

- inbound calls for jitsi meet
- outbound calls for jitsi meet
- SMS to email for easier sharing of 2FA
- masking that it's a VOIP number (likely via port)
- anything else?

**Comment by YurkoWasHere** [comment]
> anything else?

To spec out what we need we need to know what we are going to use it for and its way to early to do this.

> inbound calls for jitsi meet
> outbound calls for jitsi meet

As mentioned in chat during the pilot of Jitsi no one has ever expressed a desire to use the number.  So i don't know how high that is on a "we need" it list. It would also only really support local users as others would incur long distance fees which may not be desirable.

If Jitsi Incoming Numbers are an important requirement i would suggest:

- Dropping self hosted jitsi and use public with all its numbers
- Continue to use self hosted and on the odd chance some one needs to call in we can switch over to public.

**Comment by patcon** [comment]
Updates:
- in the time since, i got a bit stressed by not having a phone number to call into when my tech was failing
- @ASoTNetworks set up an inbound number! :pray: (it's temporary, but it's documented)

**Comment by dcwalk** [comment]
literally just saw that I'm tagged on this issue. I think if I'm being signed up for something I need more of a ping rather than editing me into the top issue. I'll work on recording the voicemail message asap.

**Comment by benhylau** [comment]
Can @hyphacoop/infra-wg untag @hyphacoop/ops-wg or let us know what is needed from us? We don't have a good idea of status of this, or why it's not already closed.

**Comment by patcon** [comment]
It feels safe to untag ops.

@hyphacoop/infra-wg Going to bump to high prio, so we either move it or kill it. Sound ok?

**Comment by patcon** [comment]
>We don't have a good idea of status of this, or why it's not already closed.

(But also, this ticket might be just a future-problem we don't care to deal with now. Is there a preferred strategy to close things that aren't moving as a matter of course? Or can low-priority things just hang around and we don't care? I'm not clear on the task philosophy implied by the comment, but am happy to adopt an aggreesive tactic of closing if we'd all prefer that)

**Comment by benhylau** [comment]
I think whatever infra chooses is fine. Personally I think leaving in Backlog or Todo seems fitting, depending on what your internal process is to pick those up.

Just needed to know ops isn''t blocking it.

**Comment by patcon** [comment]
k thx, we'll revisit at meeting.

Question during meeting: Without getting bogged too much by current financial position, what's our ideal medium-term business phone situation?

We've gathered input here, so I think we can approve a proposal and hold acting on it for later, but at least have a plan confirmed :)

**Comment by YurkoWasHere** [comment]
Current number is working and there is no urgency re SMS or other features.

Leaving in backlog to revisit at a later time.

**Comment by ASoTNetworks** [comment]
Right now our services are tied to different phone numbers such as BBB ,Jitsi, SMS, and office. We want to move all of them into the main office number. 

- [ ] Confirm if [Free Phone Line](https://www.freephoneline.ca/) allows SMS after unlocking main office number for $100 CAD
- [ ] Unlock number or use another provider
  - [ ] Confirgure SMS to members email
  - [ ] Set up FreePBX to terminate incoming / outgoing calls
    - [ ] Configure voicemail to email
    - [ ] Extension for BBB
    - [ ] Extension for Jitsi
    - [ ] Extensions for members to use for outgoing calls using Hypha's number

**Comment by YurkoWasHere** [comment]
SMS does not work on free phone line
http://forum.fongo.com/viewtopic.php?f=8&t=19989#p78237

**Comment by benhylau** [comment]
Free Phone Line does not support SMS. We will be using VOIPms.

**Comment by YurkoWasHere** [comment]
Number was ported over the VOIP.MS on November 2nd

Following call flow was applied

`IVR` - "Hello you've reach Hypha worker coop learning and building technologies together since 2019"
`1 second timeout` -> `Voice mail - "Unfortunately we cant take your call right now please leave a message and we will return your call within 2 working days" <BEEP>
Voicemails are emailed to members at hypha.coop

`IVR` was added to allow additional menu options such as BBB or JITSI call in from the main number
