### ISSUE TITLE
OKR: Goal-setting exercises

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/organizing#173]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** Jan 2020  
🎯 **Success criteria:**  Cultivator for Jan 2020 to lead goal-setting exercises

In the December 18, 2019 All Hands, we discussed doing some personal and collective goal-setting as kick-off during our Jan 2020 sync time.

## To Do

- [x] Initial discussion at all hands (parked individual goal setting until AGM)
- [x] Discussion of working group-surfaced objectives/goals
- [x] Working groups review/discuss: "(1) objectives they wish to pursue for the year and (2) milestones that need to be hit/indicators that demonstrate success"
- [x] presentation at all hands
- [x] dc: migrate bizplanning and governance&ops WGs to [sheet](https://docs.google.com/spreadsheets/d/1hMFS3IhzZOFQA-yjt7lFcoVO0Ry6erFEH7D1NswvDtA/edit#gid=230139147)
- [x] @benhylau: clean up or migrate OKRs to proper public sheet
- [x] @dc: handbook PR with process, Os, link to spreadsheet => https://github.com/hyphacoop/handbook/pull/46
- [x] @patcon: spawn issue to discuss OKR process and/or role [ops]. "Shall we start with defining tasks/process before defining role?" https://github.com/hyphacoop/organizing/issues/199

**Comment by dcwalk** [comment]
Hey @uditvira , just to point to the places where we have our previous milestones:

- [December 2018 retreat](https://github.com/hyphacoop/organizing/blob/master/2018-december-retreat/2018-12-08-retreat-day-02.md#prioritizing-and-working-groups)
- [Strategic Plan in Business Plan](https://docs.google.com/document/d/1U8C1XZcDpu1r4ciecbKEZ6vOL41nTinfqPCbZDhkAWc/edit#heading=h.wxrk0oblag6u)

**Comment by patcon** [comment]
Note: Udit isn't in governance WG.

**Comment by dcwalk** [comment]
Review of this came up in gove working group 2020-01-29, @uditvira the todos are now accurate to what has been done, but would be good to identify some next steps for closing this out.

In particular, how will be document our goals? In the handbook maybe?

**Comment by uditvira** [comment]
Yes, handbook sounds great. Once we've collected goals from everyone, either business or governance wg's can take the task of word-smithing, matching format, and merging in to handbook

**Comment by dcwalk** [comment]
@patcon I'd like to take over your task to move this forward, I think we could have a PR ready ASAP for review, is that okay?

**Comment by dcwalk** [comment]
Done! Closing for now. Folks should feel free to re-open if they feel this hasn't been fully addressed
