### ISSUE TITLE
Improve practices of managing passbolt instance

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#175]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** Before end-of-year.  
🎯 **Success criteria:** We feel comfortable with the setup of Passbolt.   

We all have admin access on passbolt for daily affairs. These high privileges could result in accidental deletions of important groups or users.

## To Do

- [x] determine best tactic
- [x] inf: setup regular backup of the vault
- [x] inf: test restoring of the vault
- inf: ~~document groups (since we can't all see them)~~ _(edit: won't do)_
- [x] @benhylau document in handbook https://github.com/hyphacoop/handbook/pull/88/files
    - document that only admin account can see all the entries
    - document the responsibility of each individual member (backup priv key)
- [x] inf: communicate this to all members

**Comment by patcon** [comment]
This came up in the 2019-12-17 finance WG meeting.

Proposal for managing passwords on passbolt:

@benhylau proposal:
- choose 2 people to have full admin
- limit the rest to some subset of access

patcon's proposal:
- create a shared elevated admin user for managing
- share access to that account with a group for infrastructure
- de-escalate privileges for all other user accounts (we won't use an elevated account for day-to-day password adding/fetching/sharing)

**Comment by benhylau** [comment]
I am fine with either proposal above as @hyphacoop/infrastructure-wg sees fits. I would also like better documentation on "what happens if pass.hypha.coop is down and @ASoTNetworks @YurkoWasHere isn't around"?

**Comment by YurkoWasHere** [comment]
Export your passwords regularly.

**Comment by dcwalk** [comment]
Reading the comment above was actually fear-inducing. It also makes me not want to trust what we have/save passwords into my other password manager service, which I'd been avoiding.

**Comment by YurkoWasHere** [comment]
> Reading the comment above was actually fear-inducing. It also makes me not want to trust what we have/save passwords into my other password manager service, which I'd been avoiding.

What in particular is "fear inducing".

**Comment by benhylau** [comment]
I agree with @dcwalk that this statement gives me zero confidence, and @hyphacoop/infrastructure-wg is essentially saying we offer a demo with zero service guarantees, and at the same time expect users to store the most important keys in there.

>Export your passwords regularly.

Both the reliability of service and the attitude towards reliability of service expressed here is fear-inducing.

**Comment by dcwalk** [comment]
My feeling is that if something goes wrong I won't know how long until it is resolved, nor should I expect help resolving it, both things that help me gauge trust.

**Comment by YurkoWasHere** [comment]
> My feeling is that if something goes wrong I won't know how long until it is resolved, nor should I expect help resolving it, both things that help me gauge trust.

My statement about exporting passwords should not be taken as a sign of the system's stability and support, but rather a prudent thing to do. 

One very important thing to keep in mind
If you lose your `private key` then you loose access to your passwords. Having an export of your passwords stashed somewhere can save you. There is no "forgot password" in pass bolt!

Furthermore
The system is  backup-ed up nightly, and stored for several days in case of hardware failure etc.

However we recognize that this is a critical piece of infrastructure (as are some of the other services) and we are looking at a way to build a means be able to quickly redeploy these services if needed without a single point of failure.

**Comment by YurkoWasHere** [comment]
Backup phase 1 - Replication between @ASoTNetworks  and @YurkoWasHere

**Comment by ASoTNetworks** [comment]
Created a VM for backup in the Virtual Office and sent login infos to @YurkoWasHere

**Comment by YurkoWasHere** [comment]
@ASoTNetworks 
Built a script following guidelines in https://help.passbolt.com/hosting/backup 
TAR/GZ and SCP into server under `~/backup/passbolt`

Next step would be to try to restore an instance to make sure it works.

**NOTE** ( From the above link)
> Every user private key should also be backed up, this is however not something we/you can automate easily for now (passbolt might provide a functionality for this in the future). We believe it is best if this is the responsibility of the end user. There is a dedicated step during the extension setup to that purpose.

**Comment by YurkoWasHere** [comment]
Confirmed backup is uploaded

Next step - restore Test

**Comment by benhylau** [comment]
Updated subtask list and untagged @hyphacoop/operations-wg the rest is up to @hyphacoop/infrastructure-wg to implement :)

**Comment by ASoTNetworks** [comment]
To restore passbolt install normally then run the following commands:
`mysql -u root -p passbolt < passbolt.sql`
`rm -r /var/www/passbolt/config /var/www/passbolt/gpg /var/www/passbolt/img`
`cp -r wwwroot/config/ wwwroot/gpg/ wwwroot/img/ /var/www/passbolt/`
`chown -R www-data:www-data /var/www/passbolt/`
`su - www-data -s /bin/bash -c 'gpg --import /tmp/gpg.key'`

@YurkoWasHere the gpg.key isn't being exported as it is 0 bytes in the archives. I will try the restore again after that is fixed.

**Comment by YurkoWasHere** [comment]
`gpg --export-secret-key -a "passbolt server" > private.key` didn't work

copied `config/gpg` instead

Please check again

**Comment by ASoTNetworks** [comment]
I can restore the server but getting `An Internal Error Has Occurred` while trying to login. I am suspecting that the GPG key needs to have expiration time removed as stated in the doc.

Will try again tomorrow.

**Comment by ASoTNetworks** [comment]
I have tested the updated commands above to restore from the backup file

**Comment by benhylau** [comment]
BACKUP YOUR KEYS
