### ISSUE TITLE
New tags based on governance proposal for operations

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/organizing#182]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** N/A
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** New tags/labels/teams are created

During the All Hands meeting on Jan 9, the following proposal was made and achieved consensus:
* New tag for "in between" tasks (`needs-review`, `ownership-issue`, `boundary-object`)
* `wg:ops` as new tag, rename existing to `wg:infra` 
* "Ops" work (potentially) addressed at Governance WG for now.

## To Do

- [x] make new tags/labels [`wg:ops`](https://github.com/hyphacoop/organizing/labels/wg:ops) and [`review-wg`](https://github.com/hyphacoop/organizing/labels/review-wg)
- [x] rename to `wg:infra`
- [x] assign [`wg:ops`](https://github.com/hyphacoop/organizing/labels/wg:ops) to existing infra issues
- [x] quick review of [`wg:governance`](https://github.com/hyphacoop/organizing/labels/wg:governance) tags to add  `wg:ops` to
- [x] **stretch** add new team if required

**Comment by dcwalk** [comment]
I've done a pass thru of all the tags. Feeling a bit hesitant to go ahead and make the new team, so sitting on that awhile. Thanks for spawning this issue :))

**Comment by dcwalk** [comment]
Created @hyphacoop/ops-wg and currently has all the same members of @hyphacoop/infra-wg ... I'll leave it to folks to self-select whether they want to be represented on both teams, but will close this for now as we've developed the new tags and implemented.
