### ISSUE TITLE
Expense reimbursements

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/organizing#185]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** May 15, 2020  
🎯 **Success criteria:** Create reimbursement process for member expenses and pay them out with payroll  

## To Do

- [x] Create process for member expense reimbursements
- [x] Add process doc
- [x] Reimburse all member expenses to date
- [x] publish Posting Journal to Drive and email Rodica
- [x] confirm QB to make sure expense reimbursements are entered into correct accounts
- [x] add notes to handbook

**Comment by YurkoWasHere** [comment]
- [ ] Make expense reporting sheet
- [ ] Process for reporting
- [ ] Process for entering/remitting 


# Reporting Process [ wip ]
- Upload all receipts to ______
- Open Template `_Hypha Expense Sheet Template` in `Expense` folder in google drive
- Select `File`/`Make Copy`
- Enter the name in format `IN-YYYY-MM-DD` IE: `YJ-2020-27-02`
- Enter your Name and Date field provided in in row 1
- Starting on A5 
    - Column A `Date of Expense` the date on your receipt
    - Column B `Description of Expense` Short description of what the expense is for
    -  Column C `Currency` Should be CAD unless in Receipt in Foreign Currency (see note below)
    -  Column D `Total Amount` is the amount that shows on the receipt
    -  Column E `HST Amount` is the total HST that shows on the receipt 
    - Column I `Cost Center/Project` Indicates what project or area the expense is for. 
    - Column J `Receipt Link` is the link to the google drive where the receipt has been scanned to

- If Receipt if in Foreign Currency additional fields
     - Column C `Currency` Should indicate the currency of the receipt
     - Column F `Total Amount CAD` is the amount in CAD you are requesting back.  This usually can be found on your credit card bill if paid by credit card.
     - Column G `Exchange` AUTOMATICALLY Calculates the exchange rate between `Total Amount` and `Total Amount CAD`
    - Column H ` HST Amount CAD` AUTOMATICALLY calculates in HST in CAD
    - Confirm the totals at the bottom. Specifically column F which will be the amount reimbursed.

# Entering Process [ wip ]
 - Deal with quick books (TBD)
 - Transfer funds using "Send money" in dejardins
   - Requires banking information for each memeber

**Comment by benhylau** [comment]
From March 19 meeting:

- [ ] yj: make reimbursement sheet in finance gdoc
- [ ] yj: write out process in gh
- [ ] bl: theme new tab in gdoc
- [ ] bl: add https://link.hypha.coop/reimbursement
- [ ] bl: transfer steps to handbook

**Comment by YurkoWasHere** [comment]
GETPIVOTDATA used in "Employee Payroll"

`=IFERROR(GETPIVOTDATA("Amount CAD",'Employee Reimbursement Summary'!$A$2,"Employee",A6,"Pay Period",TEXTJOIN("",TRUE,$B$3)),"")`

`=IFERROR(xxx,"")`  <- if not found display "" instead of an error

`GETPIVOTDATA` - Gets specific aggregated data from pivot table

`"Amount CAD"` - Name of the arrogate field you want it to return

`'Employee Reimbursement Summary'!$A$2` - A reference cell IN the pivot table, usually the top left most one as its always there

`"Employee"` , `A6` - where 'Employee' column/row is = to  `A6`
`"Pay Period"`, `TEXTJOIN("",TRUE,$B$3)` -  and where `Pay Period` matches  `B3`
`TEXTJOIN("",TRUE,$B$3)` - Work around since `B3` is a DATE field so when converted to string it retuns a number. This weird formula keeps the assigned formatting making it March 2020.

*Excel note*
`$` in front of a reference makes sure it does NOT change when copied
For example
`A6` will change to A5 if copied to on row row higher
`$B$3` wont change when copied to a row higher. 
Hotkey if F4 to apply $ to both row and column

**Comment by YurkoWasHere** [comment]
# Reporting Process [ wip ]
- Upload all receipts to ______
- Open Template https://docs.google.com/spreadsheets/d/1sfWOQKogtGU83eIIVD0GQnFvRyJzaqzWvrtB3D0jy64/edit#gid=475791249 in google drive
- Open Employee Reimbursement sheet 
- Starting on A5 
    - Column A `Date of Expense` the date on your receipt
    - Column B `Employee` your name as it appears in `Employee Payroll` sheet 
    - Column C `Description of Expense` Short description of what the expense is for
    -  Column D `Currency` Should be CAD unless in Receipt in Foreign Currency (see note below)
    -  Column E `Total Amount` is the amount that shows on the receipt
    -  Column F `HST Amount` is the total HST that shows on the receipt 
    - Column J `Cost Center/Project` Indicates what project or area the expense is for. 
    - Column K `Receipt Link` is the link to the google drive where the receipt has been scanned to

- If Receipt if in Foreign Currency additional fields
     - Column D `Currency` Should indicate the currency of the receipt
     - Column G `Total Amount CAD` is the amount in CAD you are requesting back.  This usually can be found on your credit card bill if paid by credit card.
     - Column H `Exchange` AUTOMATICALLY Calculates the exchange rate between `Total Amount` and `Total Amount CAD`
    - Column I ` HST Amount CAD` AUTOMATICALLY calculates in HST in CAD
    - Confirm the totals at the bottom. Specifically column F which will be the amount reimbursed.

# Entering Process [ wip ]
 - Set Pay Period as it appears in `Employee Payroll`
 - Enter into wage point as part of payroll cycle
 - Deal with quick books (TBD)

**Comment by benhylau** [comment]
Added to handbook https://github.com/hyphacoop/handbook/pull/64

**Comment by benhylau** [comment]
@YurkoWasHere I think once we merge this, and I file all my expenses, the only thing remaining is `Deal with quick books`. You have any thoughts that we can write out to close this fully? I imagine it's along the lines of matching the expenses on the expense spreadsheet to appropriate accounts and making sure those are matched with the wagepoint deduction? Should we do that or should our bookkeeper do that as part of their existing process?

**Comment by benhylau** [comment]
Done!
