### ISSUE TITLE
Evaluate our conditions for interpreting employment relationships

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/organizing#190]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** N/A  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** Have written description and policy how we evaluate employer-employee relationships, assessment on whether someone is a employee vs. contractor, and understand dependent vs. independent contractors.  

Found a set of useful resources around Employment Relationships and Worker Co-operatives in AGM prep. I think we've likely under considered our interpretation (codified in the [Handbook](https://handbook.hypha.coop/co-operative.html#member-owners-and-employees)).

Look into case of perpetual contractor (individual vs. company, national vs. international, dependent vs. independent, etc.)

## To Do

- [x] review CWCF resources
  - https://canadianworker.coop/guidelines-for-determining-whether-or-not-there-is-an-employer-employee-relationship-in-a-worker-co-op/
  - https://canadianworker.coop/employment-law-and-worker-co-ops/
  - https://canadianworker.coop/worker-co-ops-and-employment-law-in-canada/
- [x] discuss as Ops
- [x] update handbook
  - [x] Member sign-off on changing language from `member-owner` to `member-worker`

**Comment by benhylau** [comment]
Also for _contractors_ and _prospective members_.

**Comment by benhylau** [comment]
I think "member-owner" is the wrong language. According to https://canadianworker.coop/wp-content/uploads/2012/12/EI_Brief.pdf the language used is "worker-member". This line:

>Every member-owner is both an employee and co-owner of Hypha. There are seven member-owners, all of which are founding employees, with four Directors.

Should read:

>Every **worker-member** is both an employee and **member** of Hypha. There are seven **worker-members**, all of which are **founding members**, with four Directors.

**Comment by dcwalk** [comment]
Yes, remember I threatened to make this a resolution at our AGM? I reviewed
this and thought the same thing a few months ago. I think we can bring to a
all hands and agree to the switch!

**Comment by benhylau** [comment]
Great! I recall you mentioned it, and checked that bylaws doesn't contain it. Should be easy switch.

**Comment by benhylau** [comment]
This is done.
