### ISSUE TITLE
Set up external doc-signing tool

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#195]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** https://github.com/hyphacoop/organizing-private/issues/13  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** We've signed the first doc and shared thoughts on experience here.  

We already have an internal signing process using PGP/Keybase (which we used for org resolutions https://github.com/hyphacoop/handbook/issues/21), but we should have a simpler one for external clients.

## To Do

- [x] try a tool with personal email: HelloSign -- patcon
- [x] send first doc to client -- patcon
- [x] share feedback on how it went (see below)
- [x] document how it worked in this issue
- [x] ask for consent to migrate account to org ownership
- [x] transfer account to org
  - [x] create `platform.hellosign@` forwarder to @hyphacoop/business-planning-wg  
  - [x] adjust profile to be general for org
  - [x] store in /passwords
  - [x] add to /inventory

**Comment by patcon** [comment]
From [chat convo](https://matrix.to/#/!bAlSVEPGHLWhmUfQRP:tomesh.net/$DbHoG6rsbgaQ-RiDzcztQ2ukz_vhrVBKjcPu18KbKKM?via=tomesh.net&via=elon.li):
- :bulb: can convert patcon's personal hellosign account into org account (patcon)
- :bulb: we could use Adobe's desktop software for signing (ben)
  - :mag: signers can sometimes sign in such a way that they edit document and corrupt it (yurko)
  - :heart: hellosign flow was really smooth and simple (patcon)
  - :mag: docusign can cost $30K for some orgs (yurko's)
    - :heart: nice that hellosign is free (yurko)
- ✅ decision: make hellosign account available, and others use it at will (patcon) :+1: ben, yurko

**Comment by patcon** [comment]
How I used HelloSign:
Screencast: https://recordit.co/X8whEde5IH

1. Sign in (see passbolt)
1. For "Who needs to sign?" choose **"Just Others"**
1. Upload the file (doesn't count to quota until sent)
1. Add all signers, including Hypha's rep first
1. Click "Assign signer order" to enforce order.
1. Click "Prepare docs for signing" to place/assign the fields.
1. Give the agreement a nice, human readable title, and nice message.
1. Send it along! (This will initiate sending, and use up 1 doc from our monthly quota)

**Comment by patcon** [comment]
How it went:
- HelloSign sends updates (to account owner, now business planning WG) whenever the doc moves through a step of the pipeline to completion, e.g., as each sequential recipient either **views** and/or **signs** their section.
- Every signer automatically **gets a copy** with **audit trail**.
- signers have **many options to sign**, including _upload_ of signature image (which this actual client used), _typing_, _drawing_ with trackpad, or _sending to touchscreen mobile device_ for finger sig.

**Comment by patcon** [comment]
We can move some of this into handbook when someone else uses it and validates that it's something we should keep doing. Seems out of scope for now, so we can just mark this as done and revisit :)
