### ISSUE TITLE
Add hypha to public tech co-op channels 

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/organizing#197]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** Hypha is added to existing tech worker co-operative channels and our online present reflects our brand  

Once our website & brand has launched we should more formally add/announce ourselves on public channels. Depends on #77 and #80 

## To Do

- [x] Update current communications channels (not website) to match brand
  - [x] twitter: https://twitter.com/hyphacoop
  - [x] linkedin: https://ca.linkedin.com/company/hyphacoop
- [x] Add ourselves to existing directories:
  - [x] tech-coops awesome list => https://github.com/hng/tech-coops/pull/44
  - tech-coop-network: https://techworker.coop/members (Sassafras Tech Collective maintains) -- emailed)
- Start new networks to join (?!)  :stuck_out_tongue_winking_eye: (e.g., [nobawc style](https://nobawc.org/))
  - Great Lakes region Network of Worker Co-operatives
  - GTHA Network of Worker Co-operatives

**Comment by benhylau** [comment]
It seems this will be unblocked when #219 finishes. @patcon @garrying eta on #219?

**Comment by dcwalk** [comment]
Discussed in `2020-03-11` Ops call, this is more Social Media role / @hyphacoop/business-planning-wg , re-tagging for you all!

**Comment by dcwalk** [comment]
@patcon are you able to step into this as some overlap with your work as Social Media and (now) in #219?

**Comment by dcwalk** [comment]
We've added and updated what we can. I emailed the tech-coop about what joining that network looks like, and got some nibbles on a more regional network. Will itemize issues separately as they arrive.
