### ISSUE TITLE
Create social media role

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#198]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** A defined social media role exists, and has been documented in handbook (or has been veto'd).

...

## To Do

- [x] Research role creation process from sociocracy.
- [x] Prepare mini explainer.
- [x] share-back with @hyphacoop/business-planning-wg
- [x] Request permission to generate role using process derived from sociocracy.
- [x] lead quick session to seek input on role
- [x] write role description
- [x] get consent on role description 
- [x] select role keeper by consent https://github.com/hyphacoop/handbook/pull/52#issuecomment-595289372
- [x] add role to handbook https://github.com/hyphacoop/handbook/pull/52

**Comment by patcon** [comment]
### Resources

- [Sociocracy 3.0: A practical guide > Clarifying Domains](https://patterns.sociocracy30.org/clarify-domains.html)
- [Sociocracy 3.0: A practical guide > Role](https://patterns.sociocracy30.org/role.html)
- Book: [Many Voices, One Song](http://gen.lib.rus.ec/book/index.php?md5=CDE3D9B78FDE65144FDDAEE4819403E0) (Section 3.6.1 Creating roles)

### Adapted Process

(Can be done all at once.)

1. Share info on _roles_ and _domains_ in Sociocracy.
2. Write a role description and accept by consent.
    1. **Understand:** Share perceived need and take clarifying questions.
    2. **Explore:** solicit generative ideas, esp on:
        1. role scope <sub>(see image below)</sub>
        2. role description ideas <sub>(e.g., time will be tracked under tag X; expected 1 h/wk; only Twitter will be used; can squat new social media accounts; what sort of interactions; etc.)</sub>
        3. synthesize into role description <sub>(delegate someone)</sub>
3. **Decide:** Select individual as role keeper by consent.

<img width="401" alt="Screen Shot 2020-02-13 at 12 35 10 AM" src="https://user-images.githubusercontent.com/305339/74405391-f5400e00-4dfa-11ea-965f-885dbe41e223.png">

**Comment by dcwalk** [comment]
Based on what we discussed in the governance&ops meeting I thought you were going to go ahead and submit a PR, I’m not sure you need to to the extra stage now if preparing an explainer and seeking permission before sharing what you have. 
I think a brief explanation verbally as you discuss would be sufficient

**Comment by benhylau** [comment]
@patcon seems done?

**Comment by patcon** [comment]
Touche. Slowly catching up. Feels good!
