### ISSUE TITLE
Define and steward our first OKR process

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#199]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** https://github.com/hyphacoop/organizing/issues/173 
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** We have clarity on how we get to the end of our first OKR process.  

Thanks to @uditvira, we're started into our first OKR process. Now we should figure out what we need in terms of process (and support role?) to help guide us through it.

## To Do

- [x] decide which WG "owns" the OKR process. -- discussed `2020-03-11`, @hyphacoop/ops-wg happy to take on
- [x] (start) archiving okr notes: https://hackmd.io/fb9JLJioRDqoGdP8DEsMfA?view => https://github.com/hyphacoop/organizing/pull/238
  - below "archive" could add OKR section to index, notes in own folder 
- [x] prepare update to OKR page in handbook with process
  - describe process, drafter here: https://hackmd.io/ImMcCS6hTQWcCStwHK8qRA
  - role needed? => cultivator for that month? or distinct operations task?
- [x] at all hands seek advice in meeting on how we could go about this
- [x] PR into handbook => https://github.com/hyphacoop/handbook/pull/63
- [x] run okr process 2020 Q2
  - [x] kickoff
  - [x] reminder to WGs
  - [x] wrap-up call

**Comment by patcon** [comment]
- Article: [What is an OKR champion?](https://gtmhub.com/blog/what-is-an-okr-champion/)
  - drives adoption
  - designs the process
  - offers support
  - chooses/maintains tools

**Comment by patcon** [comment]
> Shall we start with defining tasks/process before defining role? -- @uditvira

Wondering if we could collectively write a role description (like a job description), but leave the specifics of process up to the nominated role holder to decide (within constraints/criteria we offer)? 

(Related: Hoping to demo a role creation format here https://github.com/hyphacoop/organizing/issues/198#issuecomment-585565152)

**Comment by dcwalk** [comment]
We explicitly agreed to identify tasks, so I’d rather we started to do that? That seems to put us in the understand/discovery stage from your other issue.

Also tho, if we we’re collectively happy with that approach I’m a little wary to redirect into a “role” immediately after the call.

**Comment by dcwalk** [comment]
Here is way another coop has described their OKR process, this level of formality feels right for where we are: https://commonknowledge.coop/writing/weeknotes-1

**Comment by dcwalk** [comment]
And here is the definiton we used through the process:
```
### About OKR's

(adapted from [Trello blog](https://blog.trello.com/okrs-set-achieve-track-trello) shared by patcon in chat)

**OKR stands for Objectives and Key Results.** The Objectives tend to be the desired outcomes that you want, and the Key Results are the measurable ways you know you’re on track to reach them.

An **Objective** helps answer the question, _“Where do I want to go?”_
A **Key Result** helps answer, _“How will I know I’m getting there?”_

```

and our original planning sheet: https://hackmd.io/fb9JLJioRDqoGdP8DEsMfA?view

**Comment by dcwalk** [comment]
wound up having the last bit of process go to chat due to more pressing convos at allhands. Closing tho!
