### ISSUE TITLE
Develop peer feedback model for launching at AGM

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/organizing#202]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** N/A 
🗣 **Loomio:** N/A  
📅 **Due date:** start-May
🎯 **Success criteria:** Have a peer feedback process to use during AGM that has member buy-in  

As was discussed in [2020-02-12](https://hyphacoop.github.io/organizing/2020-02-12-governance-wg-meeting.html) governance WG meeting, we'd like to have a peer feedback process in our organization. This has come up at member all hands previously.

Plan by start-May, implement tonesetting throughout May and main discussion during AGM.

## To Do

- [x] research on other models
- [x] seek advice on models ppl have used/liked/disliked at all hands(maybe with a shortlist ourselves: 3 BULLETS POINTS MAX, NO EMOJI)
- [x] start drafting session format/proposal for individual feedback
  - some portion at AGM
  - interested in OKRs that go to group
  - space for two: professional goals and personal reflection? needing to accomodate both, could be different sesh, or format
- [x] check-in/discussion at future all hands
- [x] finalizing process and supporting materials for AGM meeting

**Comment by benhylau** [comment]
Added notes to allow time for pre-AGM exercises throughout May.

>Plan by start-May, implement tonesetting throughout May and main discussion during AGM.

**Comment by benhylau** [comment]
Relevant https://twitter.com/RichDecibels/status/1262271903449919488

**Comment by dcwalk** [comment]
This was developed and is currently documented in AGM meeting notes. Closing as documentation into handbook is happening in #307
