### ISSUE TITLE
Let domains expire

### ISSUE THREAD

**Issue by YurkoWasHere** [hyphacoop/organizing#212]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** March 20, 2020
🎯 **Success criteria:** Domains dont renew

Domains are expiring soon
```
hypha.codes
hypha.systems
hypha.club
```

## To Do

- [x] Decide what do do with them
- [x] Confirm they are all set to NOT auto renew
- [ ] Confirm they have not renewed

**Comment by YurkoWasHere** [comment]
Decided on all hands meeting that we do not wish to keep any of the domains.  

Confirmed with names cheap that they are all set not to auto renew.
