### ISSUE TITLE
Website and process for meeting notes + org repo

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/organizing#215]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

I would like to propose a replacement of our current [meetings index](link.hypha.coop/meetings), which I think has the following shortcomings:

- The pipeline of `hackmd -> PR -> github` issue requires a lot of manual overhead
- We don't make good use of templates, lots of manual editing, human errors have caused confusions in the past
- Does not handle private pads well (private hackmds are still public)
- We leave a lot of old hackmds (with pre-PR'd content) hanging even after we migrate to github, and often times index is never updated (bc it's manual and no one remembers to update it after the PR gets merged)
- Index is confusing and inconsistent
- Hard to tell what is in source control, what is in hackmd, and what is private vs. public
- Pages are slow to load
- Poor access control, anyone outside the org can edit our content
- Not easy to present to public / partner orgs

The proposed replacement is already mostly done, and should address all the issues above.

![org](https://user-images.githubusercontent.com/2261308/75541613-8aa7e880-5a1e-11ea-9096-91ce05d6bd77.png)

It uses the default jekyll theme with a custom _post_ layout, so when a new notes gets merged a new github page is built on the organizing repo. No modification of the notes need to be made (unless we want to add a tag to categorize them by WG).

With this new approach, a meeting will go like this:

- Each wg / meeting type gets a custom access-restricted hackmd which is recycled per meeting
- `@roobot <wg> reset` will reset the recyclable pad based on template
- `@roobot <wg> public` will file a PR to _organizing_
- `@roobot <wg> private` will file a PR to _organizing-private_ and create a stub PR to _organizing_ that says "This note is private, linking the post to the private repo's .md file", this way we have a global index that shows also private notes but through a access controlled link

In this model, we can decide access level per meeting (it's possible that a specific bizdev can be public and a governance needs to be private, although they usually aren't). The manual overhead is much less, and with little room for error bc we offload that copy-paste work to template + roobot. Everything will be in source control, there are no out-of-sync loose pads hanging, we have a fast website to share externally and no one can change the content. We can use frontmatter + liquid to build better categorize notes in the auto-built index and even add entries for retreat, interviews, resolutions, etc.

I am happy to work with @hyphacoop/infra-wg to get this implemented. As I mentioned, most of the work is already done and on my local.

## To Do

- [x] Clean up jekyll site and send PR to organizing
- [x] Update templates and create privileged hackmd pad per working group / meeting type
- [ ] ~~Update roobot to do these new tasks~~ (edit: https://github.com/hyphacoop/organizing/issues/222)
- [x] Set up https://meetings.hypha.coop and remap shortlink to it
- [x] Update handbook references

**Comment by uditvira** [comment]
Overall I like this idea. I'm not a block on this, if you want to move forward because it does address my issues around archiving private biz wg meetings. However, this doesn't address the critical issue dc raised around PR's not being merged.

**Comment by benhylau** [comment]
>However, this doesn't address the critical issue dc raised around PR's not being merged.

That's a ppl problem not tech stack problem :) but I hope this increases the pressure to merge things bc the hackmd is gone, if you want your index to work, better help to get things merged!

**Comment by patcon** [comment]
- sounds good as described
- heads up that I'm not certain what you describe for roobot is easily doable, since hackmf uses a confusing CRDT websocket protocol to update that I spent awhile trying to sort

**Comment by benhylau** [comment]
>I worry the manual PR process (pre-roobot) will get more complicated, esp for private notes

Pre-roobot v2, yes it'll be annoying, but once we get roobot to do that it should all be very simple

>cpuld the index include links to long-term pads, so it's still a landing spot for all meetings? I visit this page first whenever there's a call, and now it seems it doesn't support my usage

Yes it's a template file we have full control now

**Comment by benhylau** [comment]
Please review the site https://hyphacoop.github.io/organizing/

**Comment by patcon** [comment]
Perhaps not the best use of my time tonight, but here's a code spike for letting roobot modify a hackmd pad: Can point it at a pad, and it will show up, clear the whole thing, and add arbitrary text.
https://github.com/patcon/hackmd-edits-test

**Comment by benhylau** [comment]
Wow @patcon that looks complicated. I am creating a separate task to track roobot work as you suggested https://github.com/hyphacoop/organizing/issues/222

Require these merged to close:

https://github.com/hyphacoop/organizing/pull/221
https://github.com/hyphacoop/organizing-private/pull/29
https://github.com/hyphacoop/shortlinks/pull/25

**Comment by benhylau** [comment]
https://github.com/hyphacoop/organizing/pull/221 is merged and I will address all remaining feedback in a future PR:

- [ ] want a little more front matter/description copied over from meeting index.
in particular, wayfinding around link to template is not clear with the clipboard symbol (esp. as that doesn't follow the pattern of js copy to clipboard.) If we don't implement that, can we just add/switch that emoji to make clear we are linking out there. And/or add a section with links to the templates "spelled out" as they currently are.
- [ ] https://github.com/hyphacoop/organizing/pull/221#issuecomment-597935934
