### ISSUE TITLE
Implement workplace health and safety requirements

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/organizing#217]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #123  
🗣 **Loomio:** N/A  
📅 **Due date:** June 30, 2020
🎯 **Success criteria:** We have met our H&S requirements as employers

Picking up from #123, this issue covers the actual implementation of the requirements as employer.

## To Do

- [x] make a checklist of our requirements as employer from resources:
    - [duties as employers](https://www.ontario.ca/document/guide-occupational-health-and-safety-act/part-iii-duties-employers-and-other-persons#section-0)
    - [first aid kits](https://www.wsib.ca/sites/default/files/2019-09/0455_english_2014.pdf)
    - [WSPS take on employer responsibilities](https://www.wsps.ca/Information-Resources/Topics/Employers.aspx)
    - [WHSC description of training requirements](https://www.whsc.on.ca/Resources/For-Employers)
- [x] discuss optional WSIB coverage options (we will proceed with registering once we have a client project that requires it, or we decide to go ahead)
- [ ] implement for our (remote) office!
   - [x] add bulletin board  => https://github.com/hyphacoop/handbook/pull/68
   - [x] create policies => **DRAFTING** https://hackmd.io/B4C39Cw2SmehqEwX7WJeQw
   - [x] define health and safety point person/rep/supervisor role
   - [x] update bulletin board (pc: miro available. zoom)
   - [ ] do mass training
---

Checklist of employers responsibility:

- **ongoing** Keep a safe and well-maintained workplace; to take all reasonable precautions to protect your workers from illness and/or injury
  - Keep your workplace health and safety policies, procedures and programs current
  - Know what the hazards are in your workplace; encourage workers to report unsafe conditions or hazards
  - Respond promptly to all health and safety concerns
  - Demonstrate your commitment to health and safety 
  - Provide training: "Ontario law now requires awareness training for workers and supervisors"
- **ongoing** Provide information about the hazards in your workplace, proper safety equipment, training, and competent supervision
- [ ] [Display required notices](https://www.ontario.ca/page/posters-required-workplace)
  - [x] Post the WSIB's "In Case of Injury at Work" poster and to follow proper procedures in case of injury
  - [x] Post the Occupational Health & Safety Act in your workplace
  - [ ] Post a copy of **Hypha's** occupational health and safety, workplace violence, harassment, policies in the workplace, where workers will be most likely to see it
- [ ]  Develop Policy ("in workplaces in which more than five workers are regularly employed, prepare")
  - [ ] a written **occupational health and safety policy**  (5 or more workers)
  - [ ] **workplace violence policy** (6 or more workers)
  - [ ] **workplace harassment policy** ??
- [ ] Roles/representatives
  - [x] Have worker representation for health and safety- Workplaces with more than 5, but less than 20 are required to have a health and safety representative
  - [ ] Have a healthy and safety point person "supervisor"
- [ ] Training
  - [ ] ensure that workers complete a basic occupational health and safety awareness training program as soon as reasonably possible;
  - [ ] ensure that supervisors complete a basic occupational health and safety awareness training program within one week of working as a supervisor
  - [ ] ensure untrained or inadequately trained workers complete a Ministry of Labour-approved, working at heights training program before they work at heights and use fall protection equipment and systems.
- [ ] Operations   
  - [ ] Review policy at least once a year
  - [ ] set up and maintain a program to implement it
  - [ ] maintain a record of the training completed by workers and supervisors; and
  - [ ] provide a worker or supervisor with written proof of completion of the training, if requested by the worker or supervisor (up to six months after ceasing to work for the employer).

Resources:

- Guide to the Occupational Health and Safety Act: Duties of employers and other persons https://www.ontario.ca/document/guide-occupational-health-and-safety-act/part-iii-duties-employers-and-other-persons#section-0
- Workplace Safety & Prevention Services : OHSA Ontario and Employers Responsibilities https://www.wsps.ca/Information-Resources/Topics/Employers.aspx
- Workers Health & Safety Centre : Workplace Hazards https://www.whsc.on.ca/Resources/Publications/Hazard-Resource-Lines
- Workers Health & Safety Centre : HEALTH AND SAFETY DOCUMENTATION TOOLS  https://www.whsc.on.ca/Resources/For-H-S-Reps/H-S-Documentation-Tools
- Workplace Safety and Insurance Board (WSIB): First Aid Requirements (Regulation 1101) https://www.wsib.ca/sites/default/files/2019-09/0455_english_2014.pdf
- Occupational Health and Safety Awareness and Training Regulation: Supporting healthy and safe workplaces https://www.labour.gov.on.ca/english/hs/sawo/pubs/fs_trainingreg.php

**Comment by dcwalk** [comment]
RE: WSIB optional coverage:
"The business activity described for your business falls under Class/Subclass L and NAICS Code 541514, Computer systems design and related services (except video game design and development). The 2020 premium rate is $0.31 per $100 of gross payroll."

Doing some quick and bad math I think we could use a shorthand of ranging from $50.00-$200 per employee Maybe ~$600 annually in our Y2 modelling, growing to over $1000 in Y5.

**Comment by patcon** [comment]
Question came up in 2020-03-09 infra meeting https://github.com/hyphacoop/organizing-private/pull/30/, so relaying here:

> what is the coverage even like for WSIB? [what does it include]

**Comment by dcwalk** [comment]
Ergonomic and psychosocial

**Comment by LexaMichaelides** [comment]
Poster stuff:

> Employers must post a range of health and safety information including:
> - [x] [Occupational Health & Safety Act](https://drive.google.com/file/d/1q4MdcXMWcQ9InAaHRlUgR4E6MkH4fVlV/view?usp=share_link) and any explanatory material prepared by the MOL in English and the main language spoken in the workplace. [Technically this is a readable pdf in the Google Drive folder but just an image on the bulletin board)
> - [x] [Ministry of Labour’s Health & Safety at Work: Prevention Starts Here poster](https://drive.google.com/file/d/1xB9T_Y_cP_K7vSc9gq0WIk8jHMCjad0r/view?usp=share_link), and
> - [x] [WSIB’s In Case of Injury—1234 poster.](https://drive.google.com/file/d/1iayd0r1D9oeBjAefiN8prZixElujfiVv/view?usp=share_link)
> - [ ] workplace occupational health and safety policy [I don't think we have one]
> - [ ] workplace violence and harassment policies [I don't think we have one]
> - [ ] names, work locations and contact information for JHSC members [I don't think we have a JHSC]

Additional functional posters we use:
- [Employment standards in Ontario](https://drive.google.com/file/d/1b2stZyIXaCsNZ0EDaIM-PmBdu611yyRl/view?usp=share_link)
- [Ergonomic poster](https://drive.google.com/file/d/1XJ8KfGk_dzgIU5_fL9sswvgJcJ74S784/view?usp=share_link)
- [Right to refuse unsafe work](https://drive.google.com/file/d/1kZO-la08D5Epdpr9MZl_FV6aN-E4ojox/view?usp=share_link)
- [covid safety](https://drive.google.com/file/d/1k3eaVPB3KblXOk6n0hDM8D0mSdVrELFi/view?usp=share_link)


**Things we need:**
- [For a workplace with 6 - 19 workers](https://www.ontario.ca/page/guide-health-and-safety-committees-and-representatives#section-3): You are required to have **one health and safety representative** who is selected by the workers they represent. If a designated substance regulation applies to your workplace, you are required to have a JHSC.
- [ ] workplace occupational health and safety policy [I don't think we have one]
- [ ] workplace violence and harassment policies [I don't think we have one]

**Comment by LexaMichaelides** [comment]
Seek templates or standards for OHS policy and violence/harassment policy for remote-first workplaces. 

@writerly03 to address the code of conduct and violence/harassment policy.

**Comment by writerly03** [comment]
What level of detail do we want for our Code of Conduct? The EDGI CoC is great, but quite detailed: https://docs.google.com/document/d/1zqFPVjQ__x3tfcSlir-jeO7O-mcCh4oKyNNlJEpJMOU/edit

The RSF project CoC is much simpler, but also covers off the basics: https://docs.google.com/document/d/1KlvsinjNGPpF25aKxWJpG8jv8aHk7uLguIbmciX16xo/edit#heading=h.xlbievl76h5f

 @LexaMichaelides pls add your thoughts on the above
