### ISSUE TITLE
Generate first-pass brand assets from intro deck

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#219]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** https://github.com/hyphacoop/organizing/issues/77  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** We've got a website and invoices that match our emerging brand.  

This came up at all hands.

Related: https://github.com/hyphacoop/organizing/issues/136

## To Do

- [x] adjust [hypha.coop website](https://github.com/hyphacoop/organizing) color scheme, font and background image to match deck. -- @garrying 
  - https://github.com/hyphacoop/hypha.coop/pull/8
- [x] create square screencap of hypha logo for invoices, social media, etc. -- @garrying 
- [ ] update logo where nounproject placeholder was used -- @patcon 
    - see: https://docs.google.com/spreadsheets/d/1D27I7edzwpDMpw8R0XIrgz-u_O6kyCRGl8cbmG7x1IE/edit#gid=1091051786

**Comment by benhylau** [comment]
I am so excited this stretch goal in moving ahead so quickly :D

**Comment by patcon** [comment]
@garrying happy to be advised of a preferred hi-res background image for Twitter or Linkedin banner as well, but otherwise will just use a background image from deck :)

https://twitter.com/hyphacoop
https://link.hypha.coop/linkedin

**Comment by garrying** [comment]
@patcon use a background from the deck for now.

Also, were we expecting the square screencap to include "worker co-operative" below "Hypha"? It looks like this:
![Artboard 1](https://user-images.githubusercontent.com/227587/76372275-43213680-6313-11ea-8e9f-dffe5b639334.png)

The second line probably not display well at smaller sizes.

**Comment by patcon** [comment]
Thanks! Happy to use that

For now or later, would something like this fit a possible aesthetic? 😜 

```
## ##
##### ==
## ##
WORKER
CO-OP
```
(with a big "H" and hyphen, and "worker" "co-op" sized smaller)

**Comment by patcon** [comment]
## Quickbook Invoice

Ok, so I'm seeing these two hex colors in hyphacoop/hypha.coop#8: `#F30CFB`  `#9900FC`

The darker one in the bill template looks alright, but lemme know if there's a better or more intentional way to discuss/do :)

<img width="1322" alt="Screen Shot 2020-03-11 at 3 12 29 AM" src="https://user-images.githubusercontent.com/305339/76391886-d32ca380-6346-11ea-8b67-19d9a71b8424.png">

---

## Cover Images

Currently using this image as the cover image where its needed, since its natural colors seems to best match:

[![mushrooms growing on tree: abhijeet-5y1YGhrsH0c-unsplash](https://user-images.githubusercontent.com/305339/76393245-8a2a1e80-6349-11ea-98eb-7403b2061395.jpg)](https://drive.google.com/file/d/1lYWCZM1zhLwj4dwOj19IGP-g-CJs9G3n/view?usp=sharing)

---

With the offered image, I've updated main logos tracked in https://link.hypha.coop/migrations:
- [x] https://twitter.com/hyphacoop (+ cover image)
- [x] Quickbooks (excl invoice style)
- [x] https://github.com/hyphacoop
- [x] https://link.hypha.coop/linkedin (+ cover image)

## Potential To Dos
- [ ] customize quickbooks invoice style/layout

**Comment by dcwalk** [comment]
@patcon think this issue morphed and started to overlap with https://github.com/hyphacoop/organizing/issues/197, can you take that one on too and re-scope as needed?

**Comment by patcon** [comment]
Ah gotcha. Thanks dc!

Ok, here's what I need to close this out for our interim logo and colors:

1. @hyphacoop/finance-wg member: decide go-or-no-go on general idea of modifying invoice style (since finance systems are under your authority)
2. @garrying vet this proposal for invoice style (since branding is de facto under your authority rn):
  - style: Fresh (was "Airy Classic")
  - color: `#9900FC`
  - font
    - ~~Arial Unicode MS,~~ Courier, ~~Helvetica, Times New Roman~~ (was Helvetica)
    - ~~8pt~~ 10pt ~~12pt~~ (same)

<img width="1327" alt="Screen Shot 2020-03-18 at 4 48 56 PM" src="https://user-images.githubusercontent.com/305339/77006440-d9b7ae00-6938-11ea-9c15-2f3ff628785c.png">

We can then close this out. It might change when Garry has time to finalize logo and colors, but I'd expect is would prob be a simple color/image-swap at that point.

**Comment by dcwalk** [comment]
Could we stay in a font family that is similar to what we are using on the website?

**Comment by patcon** [comment]
Sure, there's only 4 though. Just choose monospace as throwback to our early brand riffs. Personal preference for Courier was only because others lack much character, but happy to defer to others on this

**Comment by benhylau** [comment]
I have slight preference for sticking with same font family as @dcwalk mentioned. Also a little concerned about purple on purple readability, especially when printed in greyscale and with a font that seems really thin.

**Comment by patcon** [comment]
Ok, assuming Helvetica then, right?

I'll leave readability call to garry then. I don't have much insight on balancing vibes vs contrast. I really don't have much insight, just thought we could brand more than B&W, and thought the colors we chose on slides might already be safe in terms of contrast?

Can we give garry login to Quickbooks and he can toy around and make a call? Or @garrying, you and I could just jump on a quick call and I could fidget while you make designy-decisions? (Also, happy to just leave it as-is if you'd prefer.)

**Comment by garrying** [comment]
Helvetica is probably the closest to what's on the website. I'd opt for sparse use of the purple colour and not do the purple-on-light-purple treatment for now.

**Comment by patcon** [comment]
Can only set one color, so I'll take it that Helvetica and black (as before) are the way to go. Thanks Garry!

I'm still unclear on which template is preferred ("Fresh" template in screenshots, or original "Airy"), so happy to just close this for now :)
