### ISSUE TITLE
Update roobot with new commands for organizing site

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/organizing#222]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #215   
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** Add new commands to roobot and document for Cultivators to use.  

>- `@roobot <wg> reset` will reset the recyclable pad based on template
>- `@roobot <wg> public` will file a PR to organizing
>- `@roobot <wg> private` will file a PR to organizing-private and create a stub PR to organizing that says "This note is private, linking the post to the private repo's .md file", this way we have a global index that shows also private notes but through a access controlled link

@patcon already started some of this work https://github.com/patcon/hackmd-edits-test

## To Do

- Get @roobot to talk to hackmd:
  - [ ] Access private hackmd pads
  - [ ] Copy text from a pad
  - [ ] Copy text from a template and overwrite a pad
- Get @roobot to talk to GitHub:
  - [ ] Send PR with plaintext to public organizing repo
  - [ ] Send PR with plaintext to private organizing repo
- [ ] Implement commands and document

**Comment by garrying** [comment]
WONTDO. We might evaluate roobot later if it is part of an initiative.
