### ISSUE TITLE
Initiate our response to COVID-19

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/organizing#229]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** Wed, Mar 18 
🎯 **Success criteria:** Develop hypha action plan for response to COVID-19

Per request from @benhylau we should discuss COVID-19 & hypha.

The current Toronto message: (from Councillor M. Layton Mar-12-2020):
> At this moment in time, the Chief Medical Officer of Health is working with her staff in Toronto Public Health and other health partners to plan for the potential of local spread.
>
> To help facilitate communication on this important issue, the City has set up a website with best advice, up-to-date information, frequently asked questions, and a series of contacts for a variety of questions.

- https://www.toronto.ca/community-people/health-wellness-care/diseases-medications-vaccines/coronavirus/
- https://www.canada.ca/en/public-health/services/diseases/coronavirus-disease-covid-19.html
- https://www.canada.ca/en/public-health/services/diseases/2019-novel-coronavirus-infection/health-professionals/assumptions.html#a1

And local health information (from TTC Riders): 
> Toronto Public Health at 416-338-7600, Monday to Friday, from 8:30 a.m. to 8 p.m. and Saturday and Sunday from 10 a.m. to 6 p.m., or Telehealth Ontario at 1-866-797-0000, 24 hours a day, seven days a week to ask questions. Translation is available in many languages.

## To Do

- [x]  Discuss our mutual aid solidarity approach 2020-03-14
- [x] Draft materials/approach 2020-03-15
  - [x] uv: TOC for call tomorrow
  - [x] dc+uv: first draft - hackmd pad on Sunday
  - [x]  gi: talking thru site with general content Mon
  - [x]  bl + el: review Mon, can transform pad into website or work with someone to do that
  - [x] bl + @llunacreixent: Tues, translate copy to `es`
- ~@hyphacoop/infra-wg list of what infra actually run if we need to. knowledge/estimate of effort and cost to bring to Wed all hands~ (`wont-do`)
- [x] @hyphacoop/member-owners Review collectively at all hands, Mar 18
- [x] Take time at an all hands to discuss our approach to COVID-19 for us as workers, our clients & projects
- [x] Launch on ~Wednesday, Mar 18~ Friday, Mar 19 (?)
  - [x] Contributing guidelines copy still links to edgi, and that section is generally not fully implemented (@ASoTNetworks working on)
  - [x] Navigation is not showing up, @garrying to follow up
- [x]  Announce on Social Media

**Comment by dcwalk** [comment]
Copying comment/quote from our public chat:



> Lipsitch is far from alone in his belief that this virus will continue to spread widely. The emerging consensus among epidemiologists is that the most likely outcome of this outbreak is a new seasonal disease—a fifth “endemic” coronavirus. With the other four, people are not known to develop long-lasting immunity. If this one follows suit, and if the disease continues to be as severe as it is now, “cold and flu season” could become “cold and flu and COVID-19 season.”

https://www.theatlantic.com/health/archive/2020/02/covid-vaccine/607000/

**Comment by dcwalk** [comment]
From NP article (I KNOW 🙄):
> According to a disease-transmission model developed by University of Toronto researchers, the virus’ overall attack rate in Canada, without public health interventions, could exceed 70 per cent. That number drops sharply, by about half, “if we add modest control,” said epidemiologist Dr. David Fisman, one of the model’s creators, but it will take “aggressive social distancing and large scale quarantines” to reduce it further, he said.
>
> “That’s still a huge number of people ill, and critically ill people are a large fraction in this disease,” Fisman said in an email. “I’m not going to share more specific numbers because I think they will scare people to no particular end.”
https://nationalpost.com/news/canada/coronavirus-could-infect-35-to-70-per-cent-of-canadian-population-experts-say

**Comment by dcwalk** [comment]
My notes from NCBA webinar 2020-03-13: "COVID-19 and the Co-op Business Community":

- **TOP 5** things:
  1. Come up with a scheduling/remote work/cross-training plan NOW 
    - Stress test!
    - Consider data security 
    - Lots of phishing related to COVID-19 mailouts
  2. Tell your employees the plan 
    - Communicate early and often
  3. Monitor closings/things affecting employees so you can respond 
    - e.g., not a lot of advance in some jurisdictions with school closures 
  4. Inform/re-assure employees options for sick leave 
    - Consider unlimited sick leave plan for duration ("legally permitted" in US)
    - Consider loss of earnings/wages
    - Can **require** folks not to work if exhibiting symptoms
  5. Have a plan for if an employee develops symptoms for is diagnosed with COVID-19 
    - Have a PLAN for how to handle people testing positive
    - Do more than required about notifying customers, being proactive, etc...
- Planning for preparedness 
  1. Document review -- what do we have, when was is updated?
  2. Facilitated planning -- generally good to incl. outsider to bring org together. "Risk management" included biz dev (procurement), ops, finance
  3. Plan development -- what are the risks? Blue sky unknown unknown plans 
  4. Plan rollout -- educate <> exercise ("train animals, educate people)
- Key components of a plan 
  - Communications / miscommunications
  - Policies and Processes
    - Specific to COVID-19: PPE, self-quarantine
    - HR, OHSA, what are jurisdiction requirements implemented
    - Mitigation
  - Critical Processes 
    - Loss of people, sites 
  - Alignment 
  - Educating and exercising
- "Pain of discipline or pain of regret"
- For risk mitigation, and to understand impact: Documenting clearly! 
- Impacts:
  - services unavailable? worse than normal?
- NCBA Making a co-operative focused resource on this (tho US-focused), will share

**Comment by dcwalk** [comment]
Implications for **travel**: the [Canadian Federal Government] announced a series of other new measures to limit the spread of COVID-19: 
- International flights will only be permitted to land at a smaller number of airports. Those locations have not yet been announced.
- Boats and cruise ships carrying more than 500 people will be banned from docking at Canadian ports until July.
- All travellers arriving in Canada from international points are being asked to self-isolate for 14 days as a precaution. People arriving from Hubei, China, Iran and Italy already have been asked to self-isolate.
- Enhanced screening measures at airports as well as marine, land and rail points of entry.

https://www.cbc.ca/news/politics/trudeau-covid-19-1.5496367

**Comment by dcwalk** [comment]
Good operations statement from TekSavvy to customers (of which I am one): 
> TekSavvy is closely monitoring the global and national developments in relation to the COVID-19 pandemic. Contingency plans and processes are in place with a focus on ensuring the safety of our employees and the continuity of service to our customers.
>
> Our core business, network, and customer service functions are enabled to work remotely to continue providing our services in the event that employees are unable to access their work spaces.
>
> All non-essential business travel for employees has been restricted. Return to work protocols are in place for employees who have recently traveled abroad. TekSavvy has increased janitorial services in our offices to regularly disinfect work stations and shared surfaces. Additionally, employees have been educated on appropriate hygiene, social distancing techniques, and the actions to take should symptoms arise, including self-isolation precautions.
>
> With these precautionary measures and business contingency plans in place, please be assured that TekSavvy is doing all that we can to continue delivering the service you expect from us, should the COVID-19 situation worsen.
>
> Thank you,
> TekSavvy

**Comment by dcwalk** [comment]
And, inspiring as always, May First's take on a solidarity-based response:
> As a movement, however, we have to do a lot more than cancel things.
> 
> For example, we need to explore more actively and expansively using currently available forms of communication. At May First, our members use mumble (an audio meeting program with the capability of multiple rooms and unlimited users) and Jitsi meet (an audio/video program with more limited users). We offer these resources, which enable any organization to hold on-line meetings, to all movement people and organizations. All you have to do is contact us at info@mayfirst.org and we'll help you get set up.
> 
> But we also feel we have to do more such as to develop new meeting software that is so critical for our movement. We also know that foundations are already thinking about ways to funnel money to for-profit and corporate-connected development groups and companies to look for solutions. Those solutions aren't going to be movement solutions and, at some point, they won't be free. They don't seek to keep us or our data safe, rather, they will ultimately exploit our communities. We have to pressure foundations to start investing in the development of free and open software by funding the people who are working on its development.
> 
> Finally, we have to change movement culture. Whether or not you feel you can hold large convergences right now, you are going to be challenged in holding them in the future. In-person gatherings have always excluded people who cannot afford to come or who have disabilities excluding them from certain venues, travel or accommodations. As our movement grows and becomes more economically and socially diverse, these challenges will also grow, excluding more and more people. Additionally, as the impact of climate change becomes more central in our struggle, the use of air travel to attend gatherings is an increasingly important factor in our planning. In the new more just world we seek, accessibility across all identities matters. Lastly, large gatherings increase our dependence on foundations for money and the government for protection and that makes us extremely vulnerable to disruption.
> 
> If we're to be successful as a movement, we must solve these problems. What are we going to do?
> 
> May First thinks that the answer is, in part, to use tried and tested technology we have developed thus far and will continue to develop in the future.
> 
> We also need to continue to fight for a free and liberatory internet. Our movement needs to talk about this and how to make our meeting and discussion culture more accessible and resistant to these types of disruptions. If we are always dependent on someone else's infrastructure for liberation, how complete will that liberation be?
> 
> We think our movement should start planned conversations about these issues now and May First Movement Technology is willing to be involved in helping make that happen.

**Comment by dcwalk** [comment]
(Hopefully) final dump, ways to think about supporting folks, and examples of existing support that has been pulled together and shared across my networks:

- Accessible Teaching in the Time of COVID-19: https://www.mapping-access.com/blog-1/2020/3/10/accessible-teaching-in-the-time-of-covid-19
- Team-building on remote calls: https://twitter.com/flohdot/status/1238458234815614977 ; https://twitter.com/pzlr/status/1238489261248217089
- Refunding copies of book "REMOTE" [ENDED]: https://twitter.com/jasonfried/status/1237773562322259970 ; https://twitter.com/jasonfried/status/1238134519737319425
- Online conferences: https://twitter.com/tinysubversions/status/1233107955584626688?s=20; https://twitter.com/The_Maintainers/status/1237393550980997120?s=20
- "our internet capabilities: https://twitter.com/People4Bernie/status/1238672035066204162
- Zoom "cheat sheet" / guide: https://twitter.com/dannagal/status/1237474786844041217
- Humorous/opinionated takes on remote work: https://apenwarr.ca/log/20200309

**Comment by patcon** [comment]
Pad shared from dc: https://hackmd.io/D_EFCPkpTeKyAuYJ_C-3Cw?both

**Comment by benhylau** [comment]
- I made some edits to pad, and there was some name out of sync in diff places for our WhatsApp group, I have named everything to same as the actual name in WhatsApp

- I also moved trello up above github, we should update text to emphasize trello waaaay better if ppl aren't alrdy on gh

- I would recommend that we add two additional resource links:
    - meetings site to show archive as example of how we use templates
    - service inventory as format for ppl to keep track of the tools that ppl are about to register for

  As I brought up before, I think showing examples of what we've been going, over time, will help inform many of the choices, and it is a good addition to the comparison tables. I propose we also use an emoji to denote where we make references of our own practices, maybe 🌱 ?
 @dcwalk @udit and others are +1 on these I will go ahead and add these sections

- I am now convinced we need a nav bar to all the subsections!

**Comment by uditvira** [comment]
@benhylau all these sound good. As for using emoji's can we just stick to the 🍄 where it's required, just to avoid confusion?

**Comment by benhylau** [comment]
Here are some of my thoughts about goals:

- **Short-term**: help orgs to quickly become minimally functional as a remote org, so small businesses aren't having to choose to work / force workers to work during the pandemic, or possibly to close shop / layoff workers. Keeping orgs functional is critical to prevent societal collapse.

- **Medium-term**: as community mutual aid efforts sprung up, we may have opportunities to help amplify their impact and contribute to their infrastructural resiliency. Looking at some links that @dcwalk @uditvira shared in chat, like https://covidmutualaid.org and https://docs.google.com/spreadsheets/d/1r-8rr27mPHO3-5M4Rs_oiQFacgZh_lMvwlkVv7bxQDA/edit#gid=0 the heavy reliance on facebook and google infrastructure creates a huge risk that if any major outage occurs, it'd be catastrophic to local community efforts globally.

- **Long-term**: as covid may become a long-term reality, we need to help many orgs transition to remote-first work. This may present additional challenge for resource-constraint orgs that have little budget investing in tech support, advice, and infrastructure. It's also a huge opportunity for FANG and silicon valley to expand their ecosystem capture, so we must represent alternatives that are more resilient and sustainable, and compatible with the values of those we serve.

**Comment by llunaCreixent** [comment]
I am translating your text about [Solidarity for Workers during the COVID-19 Pandemic 
](https://hackmd.io/D_EFCPkpTeKyAuYJ_C-3Cw?both) to Spanish. Let me know how you would like to handle the translated copy. 

This is the draft of the first paragraphs.

---

### Solidaridad a lxs trabajadorxs durante la Pandemia COVID-19

Como otra gente de la región de Great Lakes y Toronto, hemos estado siguiendo de cerca la situación del Nuevo Coronavirus a través de la [Salud Pública de Toronto](https://www.toronto.ca/community-people/health-wellness-care/diseases-medications-vaccines/coronavirus/) y del [Ministerio de Sanidad de Ontario](https://www.ontario.ca/page/2019-novel-coronavirus). Con el ritmo con el que la situación ha evolucionado desde el 11 de Marzo, cuando la Organización Mundial de la Salud [declaró el COVID-19 como una pandemia](https://www.who.int/dg/speeches/detail/who-director-general-s-opening-remarks-at-the-media-briefing-on-covid-19---11-march-2020), podemos asumir que continuará cambiando rápido durante las próximas semanas.

Como cooperativa de trabajadorxs que funciona por defecto en remoto, Hypha ha estado debatiendo cómo dirigir esta situación internamente, como miembros co-propietarios, y externamente, como miembros de la comunidad, cuando las expresiones de solidaridad y apoyo mutuo son más necesarias que nunca. Ahora estamos  haciendo caso de los consejos de [distancia social](https://hub.jhu.edu/2020/03/13/what-is-social-distancing/)  y [autoaislamiento](https://www.canada.ca/en/public-health/services/diseases/2019-novel-coronavirus-infection/being-prepared.html) de los funcionarios de la salud pública y los profesionales médicos. Sin embargo, los consejos no incluyen cómo afrontar la enfermedad a nivel de comunidad. Como gesto inicial, aunque pequeño, hemos preparado esta guía con ofertas de ayuda para compartir nuestra experiencia trabajando en remoto. Reconocemos que esto no aborda los asuntos más generales sobre el trabajo de quiénes puede convertirse en remoto, a qué inseguridad económica se están enfrentando muchxs trabajadorxs canadienses, o cómo lxs trabajadorxs por obra y servicio están ahora siendo forzados a cambiar a puestos de salud en primera línea por encima de sus reponsabilidades actuales. En las próximas semanas esperamos pensar colectivamente y más en profundidad cómo podemos afrontar estos y otros asuntos urgentes.

**Comment by benhylau** [comment]
Status update:

@garrying @ASoTNetworks and I did the following:
- Ported hackmd to website, covid19.hypha.coop is the official domain
- Copy edit of final copy, moved things around and added some 🍄 (copy now out of sync with hackmd)
- Hypha theming applied, prepared to add translations and @garrying started Navigation work
- Added ics calendar with all dates
- Added jitsi link for calls, based on WhatsApp group name
- Pulled contributing guidelines from edgi and added license

Things left to do before launch:
- [ ] Contributing guidelines copy still links to edgi, and that section is generally not fully implemented (@ASoTNetworks working on)
- [ ] Navigation is not showing up, @garrying to follow up

**Comment by dcwalk** [comment]
Updated top! I'm going to spin out the developing internal policy in another issue

**Comment by benhylau** [comment]
- Tracking `es` translation on new issue https://github.com/hyphacoop/remote/issues/16
- Tracking updates to infrastructure and data policy on #246 
- @hyphacoop/business-planning-wg responsible for stewarding next steps discussion

This is done, thanks all!
