### ISSUE TITLE
Try using NextCloud to coordinate project

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/organizing#239]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** Spin up NextCloud and try using it while coordinating a potential Hypha project.  

Since @hyphacoop/infrastructure-wg is already spinning this up, I'd rather we track this process than not.

## To Do

- [x] @hyphacoop/infrastructure-wg to spin up service and drop notes here about setup
- [ ] @hyphacoop/infrastructure-wg to determine backup policy
- [x] @hyphacoop/infrastructure-wg to research and integrate document co-editing software (e.g. onlyoffice)
- @benhylau to report on experience (vs. gdrive)
    - [x] as general file store
    - [x] drafting documents
    - [x] with permission management

**Comment by benhylau** [comment]
What features we need when using gdoc:

- Permission control by account (hopefully less confusing than gsuite's)
- gdoc `Suggestion Mode` equivalent is most important, allowing each account to propose edits, and hold a discussion thread on each comment / edit, then resolve / approve change. The closer to the gdoc experience the better!
- sheets, we use a lot of sheets!

Thanks!

**Comment by ASoTNetworks** [comment]
I have set up a Nextcloud instance with notes here that is currently work in progress https://hackmd.io/Nt-veeH7Sq-onr8dApEHhA?view

Currently the VM is backed up each night with a maximum of 4 backups = 4 nights of backup.

Initial testing it seems to support the above mention features but the suggest change / discussion thread is a manual process where gdocs you can click the check button and it will do the change for you.

**Comment by benhylau** [comment]
I think the "upload only" option is very useful:

<img width="335" alt="Screen Shot 2020-03-24 at 6 45 31 PM" src="https://user-images.githubusercontent.com/2261308/77459227-ade86c80-6dff-11ea-8cd1-a9e82e5a270d.png">

**Comment by benhylau** [comment]
I had a really strange issue, where if I open a file through the top "recently edited" icon:

<img width="965" alt="Screen Shot 2020-04-02 at 1 36 07 AM" src="https://user-images.githubusercontent.com/2261308/78196360-72464600-7482-11ea-9f31-64b217e1cfae.png">

All the suggestion text appear in the wrong places:

<img width="1274" alt="Screen Shot 2020-04-01 at 10 33 01 PM" src="https://user-images.githubusercontent.com/2261308/78196395-8db15100-7482-11ea-942d-fc05c7a4560f.png">

My collaborators see the document properly, but not me. It's like I have a corrupt view of the document.

When I go through the normal folder structure to open the same doc, I can see the same view as my collaborators. But if I now open through the "recent menu" again, in another browser tab, I get the corrupt view again. Very strange.

**Comment by ASoTNetworks** [comment]
I was trying to reproduce that issue but if I click on the recently edited files from there it brings me to the directory where the file is.

After opening it looks normal. Did you manage to open the file by clicking the icon there directly?

**Comment by benhylau** [comment]
Yes it didn't happen afterward for me too, but when it was in a bad state, it stayed in that state. But eventually that link started working. Not sure why. It was using OnlyOffice too, not Collabora. Not sure what to do about it, but maybe keep watch for it for now :)

**Comment by benhylau** [comment]
We have to disable Collabora, I gave out the sharelink and it opens with Collabora by default, so my friend is seeing a completely different UI than I -> https://cloud.hypha.coop/nextcloud/s/GZpxi3rZz5D7zEg and we couldn't figure out the view to iterate thru the comments. It's a UX nightmare to have both running.

**Comment by ASoTNetworks** [comment]
I have disabled the Collabora plugin

**Comment by benhylau** [comment]
Onlyoffice seems really broken at times. Accessing a doc sometimes take us to a previous version of the doc, or fails to open after taking a minute trying.

<img width="590" alt="Screen Shot 2020-05-08 at 1 05 59 AM" src="https://user-images.githubusercontent.com/2261308/81659846-64e58980-943a-11ea-9f89-92e9ec2130a8.png">

One time the file just got corrupt altogether. One person was editing it, using some more complex layouts (tables), and the link would not open for me, even downloading the doc (instead of opening with onlyoffice) would give me a very old version of the doc (I downloaded and opened with local office client).

At this point, we were afraid to lose all the content we spent hours writing, so he exported it and we imported into gdocs 😢 the NextCloud file did eventually fix itself, with all the updated content. I think after everyone left the doc / collab mode.

**My guess is that when someone is editing or using collab mode, the link points to some early version of the doc for everyone else (which of course, is a completely broke implementation). Once everyone leaves the doc, the link points to the new version. What happens if people access the older version and start making changes? I have no idea and don't want to try.**

**Comment by ASoTNetworks** [comment]
I was looking at OnlyOffice and it looks like the file is only synced to NextCloud when everyone closed / left the document on OnlyOffice or the NextCloud version will be outdated.

**Comment by benhylau** [comment]
This seems to break all collab use modes, is there an issue about this on their repos?

**Comment by benhylau** [comment]
Sync up with Chris from Webarchitects about his experience on this

**Comment by benhylau** [comment]
I was informed today that the issues I encountered were not reproducible during early testing on the [libre.brussels](https://cloud.libre.brussels) instance. They are running Nextcloud 18 with Onlyoffice 5.5.3, installed using https://yunohost.org/#/install_on_vps on a dedicated server.

I checked the Hypha instance has Nextcloud ? (@ASoTNetworks can find the version since I am not admin) with Onlyoffice 5.5.1, and the issue I experienced may be related to https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/254 but it is not 100% reproducible. For example, I cannot really reproduce it now on our instance. It happened with two different groups I was working with within a month of using it, so it's also not some rare edge case.

**Comment by benhylau** [comment]
Feedback:
- Nextcloud + OnlyOffice corrupt our docx and sheet files repeatedly (at Toronto Mesh's server run by Rob) consistent with our experience with our instance
- At Meet.coop, Webarchitects runs a diff version that we still rely on, and has been robust, but we run into UX issues that force us to still use GDocs at times

Based on this, we are shutting down our Nextcloud instance.

**Comment by benhylau** [comment]
See this thread re: data loss https://apps.nextcloud.com/apps/documentserver_community
