### ISSUE TITLE
Implement internal COVID-19 response

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/organizing#240]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #229  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** Accepted internal policy for "Hypha-to-Member" COVID-19 response for members and develop plan for ongoing monitoring and updates for members on new information.

Resources:
- 2020-03-18 All Hands notes
- https://www.canada.ca/en/department-finance/news/2020/03/canadas-covid-19-economic-response-plan-support-for-canadians-and-businesses.html

## To Do

- [x] Document review -- what do we have, when was is updated?
    - [x] Check existing contracts & insurance benefits (jokes, we have none!)
    - [x] Health and Safety (also none!)
- [x] ~~Facilitated~~ planning -- "Risk management" included biz dev (procurement), ops, finance
    - [x] Ops planning kickoff
    - [x] bizdev discussion
    - [x] finance
- [x] Draft org approach @hyphacoop/operations-wg   -- what are the risks? Blue sky unknown unknown plans
  - [x] first draft: https://hackmd.io/EdvBv_45TjW8sq1aKZgKcA
    - [x] revise
- [x] Plan rollout -- educate <> exercise ("train animals, educate people)
    - [x] discuss at all hands (April 08)
    - [x] assign continue monitoring tasks -- operations, dc
- [x] @hyphacoop/finance-wg investigate subsidy, payroll, and tax implications => #261 
- [x] add plan into handbook => https://github.com/hyphacoop/handbook/pull/65

**Comment by dcwalk** [comment]
Copying over notes that are most relevant from #229: 
My notes from NCBA webinar 2020-03-13: "COVID-19 and the Co-op Business Community":

- **TOP 5** things:
  1. Come up with a scheduling/remote work/cross-training plan NOW 
      - Stress test!
      - Consider data security 
      - Lots of phishing related to COVID-19 mailouts
  2. Tell your employees the plan 
      - Communicate early and often
  3. Monitor closings/things affecting employees so you can respond 
      - e.g., not a lot of advance in some jurisdictions with school closures 
  4. Inform/re-assure employees options for sick leave 
      - Consider unlimited sick leave plan for duration ("legally permitted" in US)
      - Consider loss of earnings/wages
      - Can **require** folks not to work if exhibiting symptoms
  5. Have a plan for if an employee develops symptoms for is diagnosed with COVID-19 
      - Have a PLAN for how to handle people testing positive
      - Do more than required about notifying customers, being proactive, etc...
- Planning for preparedness 
  1. Document review -- what do we have, when was is updated?
  2. Facilitated planning -- generally good to incl. outsider to bring org together. "Risk management" included biz dev (procurement), ops, finance
  3. Plan development -- what are the risks? Blue sky unknown unknown plans 
  4. Plan rollout -- educate <> exercise ("train animals, educate people)
- Key components of a plan 
  - Communications / miscommunications
  - Policies and Processes
    - Specific to COVID-19: PPE, self-quarantine
    - HR, OHSA, what are jurisdiction requirements implemented
    - Mitigation
  - Critical Processes 
    - Loss of people, sites 
  - Alignment 
  - Educating and exercising
- "Pain of discipline or pain of regret"
- For risk mitigation, and to understand impact: Documenting clearly! 
- Impacts:
  - services unavailable? worse than normal?
- NCBA Making a co-operative focused resource on this (tho US-focused), will share
- Some existing US Co-op resources: https://institute.app.box.com/s/5nh2wdm5ih7f94nmxu11lrw1gmaeum4v

**Comment by dcwalk** [comment]
Clipping notes from gov and all hands meetings: 
- priorities, risks and needed supports...think on multi-month scale of disruption
- understand priorities as business 
  - member-owner safety, 
  - community safety, 
  - business/operating continuity. 
- surfacing risks
- are there worker needs/supports?
     - helpful to get info via Hypha, Hypha navigate/digest info incl. package announced:  business income supports.
       https://www.canada.ca/en/department-finance/news/2020/03/canadas-covid-19-economic-response-plan-support-for-canadians-and-businesses.html
- agreement: Hypha the ability to block member activities if they are considered unsafe for either members or the community at large, but tightly scoped to COVID-19

**Comment by benhylau** [comment]
@YurkoWasHere
- Personal CERB eligibility https://www.canada.ca/en/services/benefits/ei/cerb-application.html
- 75% wage subsidy https://www.canada.ca/en/department-finance/news/2020/04/the-canada-emergency-wage-subsidy.html
- Co-operative resources
    - https://myemail.constantcontact.com/News-From-CWCF--March-2020.html?soid=1102941868059&aid=vzZoJPh_yP4
    - https://canadianworker.coop/covid-19-virus-resources/

@dcwalk you mentioned support opportunities from CWCF from [this meeting](https://meetings.hypha.coop/2020-03-25-governance.html) can you elaborate here?

**Comment by dcwalk** [comment]
Documented in draft implementation doc I mentioned: https://hackmd.io/EdvBv_45TjW8sq1aKZgKcA

**Comment by benhylau** [comment]
Another resource for @hyphacoop/finance-wg https://blog.wagepoint.com/all-content/coronavirus-covid-19-key-resources-for-small-business-owners

**Comment by benhylau** [comment]
Spawned #261 for @hyphacoop/finance-wg and untagged @hyphacoop/finance-wg here. This ticket can close when @hyphacoop/operations-wg feels ready.

**Comment by dcwalk** [comment]
Merged in Handbook! We have a plan, it is implemented, any new Ops tasks can be spawned as new issues. :tada:
