### ISSUE TITLE
Tuning our publicly available BBB instance

### ISSUE THREAD

**Issue by ASoTNetworks** [hyphacoop/organizing#246]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** June 30, 2020  
🎯 **Success criteria:** Once we are able to deploy Meet.coop's Ansible on our own stack, we will close this issue and move ongoing work to Meet.coop spaces.  

Address the following BBB issues.

## To Do (from meeting notes)

- [x] el: change default presentation
    - yj: a PDF file on server you replace
        -  The file for the default presentation is located in `/var/www/bigbluebutton-default/default.pdf`
    - bl: to provide the PDF
- [x] presentation uploading, can’t upload large files
    - yj: fixed to 10/20 MB now
- [x] el: can we turn off the “you are now muted” voice each time we mute and unmute
- [x] el: where do notes live?
    - notes uses Etherpad which are stored in a Redis database 
    - yj: if you do a recording, you can jump to the convo bc the notes are timelogged
    - el: might be in database
    - bl: has export function
    - yj: can we replace with a hackmd (pass a URL)
- [x] el: shared notes OR chat, not both
    - yj: old one, you can limit which windows are available, a xml file gets passed to define these 
things
        - `http://docs.bigbluebutton.org/client-configuration.html` <- old client
        - `http://docs.bigbluebutton.org/2.2/customize.html#html5-client-configuration` <-new html5
        - it's a yml file now (bl: yay)
     -  el: disabled notes
- [x] el: ~echo test happens every breakout, very annoying~ Wont Fix
    - yj: might be in yml file
- [x] el: retention policy => https://github.com/hyphacoop/handbook/pull/76
    - logs - default logs, use it for trouble shooting only, current retention is default
    - uploaded content - PDFs, etc.
    - in-session content - chat, video, etc.
    - others
- el: deploy new instance _(edited at June 8 Infra meeting)_
    - ~~go over yj's docs on BBB deployment~~
    - ~~looking at public BBB ansible~~
    - ~~write our own~~
    -  ~~collab on the Meet.coop ansible, referencing yj and el's docs, and deploy it on our own server~~ Re ticket #317

**Comment by ASoTNetworks** [comment]
Regarding echo test happens on every breakout it looks like BBB already have a PR open for that.
https://github.com/bigbluebutton/bigbluebutton/pull/8696

And a ticket https://github.com/bigbluebutton/bigbluebutton/issues/8387

**Comment by ASoTNetworks** [comment]
All BBB user generated content is stored in /var/bigbluebutton and a cronjob script `/etc/cron.daily/bigbluebutton` will run daily to delete old content.

The days to keep the content is defined in the script:
```
#
# How N days back to keep files
#
history=5
unrecorded_days=14
published_days=14
log_history=28
```
By default presentations, kurento streams, FreeSwitch recordings, raw of published recordings are kept for 5 days
Raw recordings without recording marks are kept for 14 days
Raw of published recordings are also 14 days
BBB logs are kept for 28 days

**Comment by benhylau** [comment]
Tried to have a call with Burak, he kept getting a `Error 1007 ICE... Failed joining audio conf.` in both Chrome and another browser, and couldn't get past the audio check. Any idea?

All my other calls, no one has a problem. Jitsi with Burak works.

**Comment by benhylau** [comment]
- [ ] our jitsi main landing page keeps history and is made public, pls disable :)

**Comment by benhylau** [comment]
>Tried to have a call with Burak...

Burak and @uditvira both experienced similar errors at one point, but I got them to try it again over the last two days and it was working fine. Maybe during peak times the TURN server was having issues? Not sure. Continuing to monitor. But we know this isn't a client-specific problem with BBB.

**Comment by benhylau** [comment]
@ASoTNetworks to confirm:
```
history=5 (for presentations)
unrecorded_days=14 (not used)
published_days=14 (not used)
log_history=28
```

and write a paragraph to describe the policy, and note that the server is not backed up.

**Comment by benhylau** [comment]
Two issues observed on one of my calls with Burak:

1. Burak's desktop has multiple microphones, there is no UI to change which one except when you first enter the room, you have to click the 👎 on the echo test, then get into the mic settings menu to select. Super awkward...
2. I, as host, couldn't let Burak present his screen. I made him moderator, he refreshed, we tried everything... but he still doesn't see the "present screen" button that I see from his browser

**Comment by benhylau** [comment]
Are there good mobile clients for BBB?

**Comment by ASoTNetworks** [comment]
There is no mobile app from the BBB docs they say the web version will run on mobile devices.

https://docs.bigbluebutton.org/#mobile-support

**Comment by benhylau** [comment]
I suggest somewhere in handbook and link from covid doc.

**Comment by benhylau** [comment]
Top level nav in handbook underneath Guides, called `How We Use Data`. Then ping @dcwalk for review as it unblocks https://github.com/hyphacoop/hypha.coop/issues/5

**Comment by benhylau** [comment]
From our Toronto Mesh [Virtual Meet and Greet](https://tomesh.net/2020-04-30/meet-and-greet/) that lasted ~2 hours:

![bbb-stats](https://user-images.githubusercontent.com/2261308/80866451-02002f80-8c8f-11ea-914e-e8ad7f01042b.png)

13 people called in (2 from India, 1 Spain, 1 Boston, others likely Toronto), 6 with video on, we hit about 32% capacity on a 100 Mbps connection. The call experience was smooth and no one complained about the experience.

**Comment by YurkoWasHere** [comment]
Script created to monitor BBB via Nagios

Polls every 5 mins to get a list (XML) of active call stats. 
if API does not return SUCCESS throws alert

Otherwise it records:
meetings - number of meetings active (including break outs)
users - total number of people participating
video - number of people sending video stream
audio - number of audio stream being transmitting
listen - number of people listing only

```
#!/bin/bash
URL="https://bbb.hypha.coop/bigbluebutton/api/"

# Requires shared secret to use APIs
SECRET="$1"

# API settings
APINAME="getMeetings"
APISTRING=""

# Calculate checksum to be passed as authentication 
CHECKSUM=$(echo -n "$APINAME$APISTRING$SECRET" | openssl sha1 | awk '{print $2}')

# Create final API url
URLFINAL="$URL$APINAME?$APISTRING&checksum=$CHECKSUM"

# Get XML
xml=$(curl -s $URLFINAL) 

# Check for SUCCESS
if [ -z $(echo "$xml" | grep "<returncode>SUCCESS</returncode>") ]; then 
	# If Failed
	echo "API ERROR"
	exit 1  # warning to nagios
else
	# If Success format NAGIOS string
	meetings=$(echo "$xml" | grep meetingID | wc -l)
	users=$(echo "$xml" | grep participantCount | cut -d ">" -f2 | cut -d "<" -f1 | paste -sd+ | bc)
	video=$(echo "$xml" | grep videoCount | cut -d ">" -f2 | cut -d "<" -f1 | paste -sd+ | bc)
	audio=$(echo "$xml" | grep voiceParticipantCount | cut -d ">" -f2 | cut  -d "<" -f1 | paste -sd+ | bc)
	listen=$(echo "$xml" | grep listenerCount | cut -d ">" -f2 | cut -d "<" -f1 | paste -sd+ | bc)
	echo "OK $meetings active| meetings=$meetings;users=$users;video=$video;audio=$audio;listen=$listen;"
	exit 0 # everything is OK
fi
```

**Comment by benhylau** [comment]
## BBB on Mobile

Had a bunch of calls with people on mobile platforms, here's a summary!

- BBB web client works on mobile, no app is needed
- **iPad and Android** devices work even better than I expected! Clear audio, video, drawing on whiteboard, PDF upload and presenting, everything works great :D first time users who aren't especially tech-savvy had no trouble
  - One Android phone, from an unknown manufacturer, has Chrome crashing whenever trying to enable video
- **Microsoft Surface (I assume Edge browser)** seems to be audio-only
- Phones with tiny screens may be more problematic, but that seems like a general problem

**Comment by benhylau** [comment]
## Related Resources

These came up in my Cooperative and DWeb networks.

- "hostsharing.de (one of the libreho.st hosting service groups ) [published results of some testing they did of Big Blue Button](https://www.hostsharing.net/blog/2020/03/30/bigbluebutton-im-lasttest/)"
- [scaling to large meetings](https://github.com/ffdixon/scalelite) (see also [blindsidenetworks](https://blindsidenetworks.com))
- bbb.nzoss.nz on CatalystCloud.nz (see [this comment](https://community.coops.tech/t/moving-away-from-zoom-collocall-co-op-hosted-solution/2056/33?u=benhylau))
- [CoTech discussion thread](https://community.coops.tech/t/moving-away-from-zoom-collocall-co-op-hosted-solution/2056) -> the beginning of [The Online Meeting Co-operative](https://www.org.meet.coop/about/)

**Comment by YurkoWasHere** [comment]
Some results from nagios

Bandwith (*note* note BBB exclusive)
![image](https://user-images.githubusercontent.com/39072689/81943761-c8ea8800-95c9-11ea-86d5-1ad74c685c4b.png)
![image](https://user-images.githubusercontent.com/39072689/81943822-dc95ee80-95c9-11ea-9605-2bc55b3b76d5.png)

Meeting data
![image](https://user-images.githubusercontent.com/39072689/81943857-e9b2dd80-95c9-11ea-8e91-0d979dfd9f82.png)
![image](https://user-images.githubusercontent.com/39072689/81943892-f5060900-95c9-11ea-88ee-e53625e307be.png)

**Comment by benhylau** [comment]
@ASoTNetworks to send final draft of data policy to @benhylau in hackmd by Thursday noon, and we finalize the PR Friday (peer) for broad review.

**Comment by dcwalk** [comment]
This sounds good! Just want to be clear tho— the data policy I think requires more than BBB (though will be an important part). Have you all been working on the whole thing of just that section?

I offered to help with broader document. Do you need that support still?
