### ISSUE TITLE
Develop hiring process

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/organizing#250]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** Have a plan to hire contractors as need arise.  

From @hyphacoop/business-planning-wg meeting on 2020-03-26 we discussed:

>- hiring process
>    - CV/resumes on file 
>    - networks/word of mouth
>    - templates of job desc.
>    - how do we hire in our values 

## To Do

- @hyphacoop/finance-wg recordkeeping, tax reporting, payment
  - [x] research above
  - [x] can we use transferwise to do foreign currency payment?
  - [x] verify with accountant
  - [x] summarize plan in handbook
- @hyphacoop/operations-wg agreements
  - [x] dc: grab descriptions of hiring process, job descriptions from elsewhere
      - [x] ask uv
      - [x] add to gdrive
  - [x] create template of job desc.
  - [x] contractor outreach
  - [x] make notes on hiring process =>DRAFTING :lock: 
      - if needed: selection process @dcwalk @benhylau 
  - [x] PR to handbook onboard and exit process
      - (currently language in guide, skips "onboarding" section of handbook (!?))
  - create contracts @benhylau =>#274 
  - IP assignment/transfer @benhylau => #95

**Comment by dcwalk** [comment]
This might be higher priority/non-backlog item due to COVID-19 implications

**Comment by benhylau** [comment]
@dcwalk we didn't assign a person to this but it seems urgent now, I understand you're working on it

Seems to have some @hyphacoop/business-planning-wg cross let's make sure we decide this at that WG meeting tmr cc. @uditvira

**Comment by benhylau** [comment]
## Taxes

### Domestic Contractor
- Need to sort **contracting** vs. **subcontracting**

- [CRA Subcontracting Reporting Requirements](https://www.bookkeeping-essentials.com/cra-subcontracting-reporting-requirements.html)
  >If an employer hires someone else to do the work on their behalf (maybe you?), this would be considered subcontracting. This means you may need to issue a T4A or T5018 slip.
- Some dates from [Hiring Independent Contractors Canada versus U.S.](https://www.bookkeeping-essentials.com/hiring-independent-contractors.html)
  >Threshold over $500
  >- T4A slip to subcontractor services deadline February 28
  >- T4A Summary to CRA deadline February 28
- [An In-Depth Guide for Independent Contractors in Canada](https://www.canadaone.com/ezine/oct11/independent_contractor_guide.html)
  >Being an independent contractor...
  >Your clients will benefit as well. Since you will not be on payroll, they will not have to deduct taxes, make EI and CPP contributions, pay statutory holiday pay or follow employment standards legislation.

### Foreign Contractor
- I imagine if we contract for services from foreign contractors who are non-residents of Canada, they would not be performing the work within Canada, so the following applies
- [The Tax Implications of Hiring Foreign Contractors](https://quickbooks.intuit.com/ca/resources/taxes/the-tax-implications-of-hiring-foreign-contractors/)
    >Where will the foreign contractor render services – in Canada or elsewhere? As a general rule, if a non-resident of Canada renders services outside of Canada, then there are no tax obligations even if the person receiving the services is Canadian.
- [Canadian companies using independent contractors in the US](https://www.canadaone.com/ezine/expert/expert_qa.html?id=10Dec17_1)
  >**How does a Canadian company need to support payments made to contractors for tax reporting?**
  >As a general rule, the Canada Revenue Agency (CRA) does not specify the books and records to be kept by taxpayers. Books and records must permit taxes collected, remitted or payable and any credits claimed, to be determined, and be supported by source documents that verify the information contained within. An appropriate source document to support a payment made to a contractor could be a sufficiently detailed invoice or contract from the contractor, along with proof of payment or liability.
- If the work ends up being performed in Canada, we may need to withhold and [file](https://www.canada.ca/en/revenue-agency/services/tax/international-non-residents/payments-non-residents.html) depending on some details, which we can explore when the time comes

## General Contractor vs. Employee Resources

- https://blog.wagepoint.com/all-content/employees-or-contractor-mini-guide-canadian-small-businesses
- https://www.hr.ubc.ca/administrators/managing-staff/independent-contractors-vs-employees/

**Comment by dcwalk** [comment]
PR was opened in https://github.com/hyphacoop/handbook/pull/119, closing as that isn't about the hiring process anymore, will follow up there
