### ISSUE TITLE
Launch initial (full) website

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/organizing#252]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #77  
🗣 **Loomio:** N/A  
📅 **Due date:** **April 5**  
🎯 **Success criteria:** Live website has explanation of our offerings etc...

Update website to reflect the service offerings from an earlier phase of our branding process (tracked in #77)

## To Do

- [x] @garrying updates from co-work
     - Who we are section
        - trying other images
        - [x] padding to image
    - [x] footer
        - [x] cc license
            - "This website content is licensed under a Creative Commons Attribution-ShareAlike 4.0 International license." https://creativecommons.org/licenses/by-sa/4.0/
        - dc: something abt placement of social "graph"
    - hypha brand/word mark colour? => to elicit feedback
        - black
        - purple
    - mobile -- might do a first pass that is less great for smaller viewports
        - add stacking, hide edge cases 
- [x] @garrying presentation at all hands
- [x] @garrying revisions after feedback
- [x] @hyphacoop/business-planning-wg review by Friday
- [x] @hyphacoop/infrastructure-wg help switch DNS by Friday

**Comment by garrying** [comment]
Deployed

- The old repo is archived here: https://github.com/hyphacoop/hypha.coop-archived
- https://github.com/hyphacoop/hypha.coop is a new repro. Re-clone the repository if you were using the previous forked repo
