### ISSUE TITLE
Move internal infra to production env

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/organizing#253]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** Develop a process for @hyphacoop/infrastructure-wg to ensure reliability of our hosted services.  

Discuss expectations and processes for:

- Spin-up
- Monitoring
- Backup
- Upgrade
- Rollback
- Incident response

This will probably involve moving pieces of our infrastructure into source control to start, and discussion of [ development vs. staging vs. production ] environments, adoption of monitoring and notification systems, and move us towards infra-as-code and automation tools that will let us spin up service instances rapidly.

```
+---------+   +---------+                    +-----------------------+
| Fact    |   | Service | (dev, stg, prd)    | Dedicated   | Proxmox |
| Finding +-->| Config  +------------------->| Server      |---------|
| Form    |   | Store   | REPO               |             |     KVM |
+---------+   +---------+  Ansible provision +-----------------------+
                           Service monitor
```

[Details here.](https://github.com/hyphacoop/organizing/issues/253#issuecomment-611456334)

## To Do

- [x] list of things we are running and where they are at current state, check with [service inventory](https://link.hypha.coop/inventor) but also include "new stuff" like BBB
- [x] compare and propose early hosting providers and what products [sheet](https://docs.google.com/spreadsheets/d/12CwJYvy7vaZ-EHJlGN8RjkUW0S5yTMdCOsltIJPmy4A/edit#gid=0) :lock: 
  - [x] recommend a server from soyoustart @YurkoWasHere 
  - [x] 2020-05-28 update sheet with offerings after all hands... "update spreadsheet with koumbit and actual soyoustart server" @YurkoWasHere 
  - [x] @YurkoWasHere  fill row 33 
  - [x] inquire with koumbit @benhylau 
  - [x] @hyphacoop/business-planning-wg assess value criteria
- [x] @YurkoWasHere put a server spec and let bizdev counter-propose something within budget
- [x] ~~draft internal proposal~~ (edit: made Milestone) with timeline @benhylau 
- [x] deployment docs and estimate of how much time it'd take to automate (e.g. on ansible)

**Comment by ASoTNetworks** [comment]
[Service inventory](https://link.hypha.coop/inventory) have been updated with the latest services.

**Comment by dcwalk** [comment]
Can we include looking at companies that provide more ethical (and sustainable) hosting practices?
Criteria could include:
- good employers
- green energy
- data sovereignty (e.g., stuff doesn't transit in the US so much) -- legal implications here 

Some examples of hosts:
- https://www.ethicalhost.ca/ (not exactly a fit for some offerings)
- https://whc.ca/canadian-cloud-servers 

There are more, some places aggregate lists: https://b2evolution.net/web-hosting/green/

**Comment by benhylau** [comment]
## Target Architecture

Admin access to all hosts should be accessed from behind a VPN, with Service VMs exposing selective ports to the public Internet. _Controller VM_ is the control centre for all manual/CI interactions with _Service VMs_.

```
+----------------------------------------------+
| Dedicated Server                             |
|                                              |
| +---------------+ +-------------------+----+ |
| | Controller VM | | dev | Service VMs | .. | |
| |---------------| +-------------------+----+ |
| | Repositories  | +-------------------+----+ |
| | CI builder    | | stg | Service VMs | .. | |
| +---------------+ +-------------------+----+ |
| +---------------+ +-------------------+----+ |
| | Monitoring VM | | prd | Service VMs | .. | |
| +---------------+ +-------------------+----+ |
+----------------------------------------------+
```

### Repositories:
- **PLAY**book repo (Ansible playbook)
- **CONF**iguration repo (client config and credentials, build-dependent on PLAY merges)

### Environments & Workflow:

1. `<service>-<uuid>.dev.hypha.systems` is deployed anywhere from behind VPN
2. `<service>-<org>.stg.hypha.systems` is deployed by CI manually/on-merge from `CONF/staging` branch
3. Manually verify `staging` features on `stg` environment before merging to `master`
4. `<service>.<org>.hypha.systems` (or custom domain), aka. `prd`, is deployed by CI manually/on-merge from `CONF/master` branch

## MVP Architecture

- PLAY repository on public repo (this will always be open source and public)
- CONF repository in private repo, manually deploy to `stg` and `prd` environment (CI as stretch goal)
- Minimal monitoring (not as a separate VM but prepare for Prometheus, etc.)
- No support for custom domains

**Comment by benhylau** [comment]
@ASoTNetworks some scenarios to consider, would like a step-by-step from you:

1. Provision 3 new Jitsi instances
2. Update firewall rules on 2 of 3 Jitsi instances
3. Dedicated server self-destruct and we need to re-instantiate the whole stack and with backup

**Comment by benhylau** [comment]
Adding to list of providers, a Montreal based coop we met at meet.coop's call https://www.koumbit.org/en/services/vps

**Comment by benhylau** [comment]
- [ ] @benhylau add meeting discussion from infra meeting to here

**Comment by benhylau** [comment]
## Timeline

- Set up a dedi with proxmox that we can carve out stg (on VPN only so we save IPs) and prod VMs (June)
- VM3: website + nginx + dns + link shortener + vision 💧 (June)
- VM11: passbolt 💧 (July)
- VM1: bbb 💧💧💧💾 (July)
- VM2: jitsi 💧💧💧 (August)
- VM5: backup server 💧💾💾 (August)
- VM6: prom monitoring 💧💾 (September)
- VM7: loomio 💧 (October)
- No plans
    - VM8: email 💧💾💾💾
    - VM9: matrix + whatsapp bridge + chatbot 💧💧💾
    - VM4: nextcloud + onlyoffice 💧💧💾💾
    - VM10: android vm 💧

**Comment by benhylau** [comment]
We need something like this with 32 GB RAM, at least 8 IPv4s (5 usable) but ideally 16, with IPv6. Unmetred bandwidth with backup space. Located in Canada.

<img width="1165" alt="Screen Shot 2020-05-28 at 1 31 56 AM" src="https://user-images.githubusercontent.com/2261308/83082217-10b9e680-a083-11ea-903c-181c39a9a43a.png">

**Comment by benhylau** [comment]
Since we have already received the quote from Koumbit, I'd like to ask we make a final decision on server vendor on Wednesday's call.

The above soyoustart server and discount is no longer available, here is a comparable one (but in USD): https://www.ovh.com/world/dedicated-servers/rise/rise-1/

Note that all these OVH and soyoustart servers are in the Beauharnois datacentre and hydropowered (with 2 other sources as power redundancy):
- https://www.datacenterknowledge.com/archives/2013/01/17/ovhs-big-green-hydro-powered-facility-in-quebec-opens
  >Beauharnois is just outside of the island of Montreal and uses renewable energy from a hydro-electric dam located just 300 meters away from the building. It was also architected to not use air conditioning, using proprietary cooling technology developed in-house. All of this results in a claimed Power Usage Effectiveness of less than 1.1.
- https://business.financialpost.com/news/cheap-hydroelectric-power-draws-data-warehouse-companies-to-quebec-b-c

**Comment by ASoTNetworks** [comment]
After looking at the above products I like the [OVH rise-1](https://www.ovh.com/world/dedicated-servers/rise/rise-1/) option more as it comes with newer hardware, IPMI access, and 500G of backup space that can be mounted over Samba and NFS.

**Comment by ASoTNetworks** [comment]
I have updated our internal server comparison spreadsheet highlighted with colors with the 3 choices we looked at.

[Server comparisons sheet](https://docs.google.com/spreadsheets/d/1XxUd7By5f9Aefqyh3N_qj8ZsV6Y8eQQJZ5PouQeO0ZQ/edit#gid=0)

**Comment by benhylau** [comment]
@ASoTNetworks can you also fix the infra ranks? They seem to not be consistent what 1-5 means. Also some of the costs seem wrong with setup cost and stuff.

**Comment by ASoTNetworks** [comment]
Fixed it and only rated the ones that we can use.

**Comment by benhylau** [comment]
This is a huge task. I have made [a milestone](https://github.com/hyphacoop/organizing/milestone/1) to track this so we can close this thread off.
