### ISSUE TITLE
Create bank of images we can use on website, etc

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/organizing#254]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #77  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** We will have an image bank with a set of images we can use for marketing, put on our website, etc...  

This was identified in [`2020-03-30` @hyphacoop/business-planning-wg branding meeting](https://meetings.hypha.coop/2020-03-30-business-planning-branding.html) as part of the next phase of our branding/website process

## To Do

- [x] decide where these go
- [x] move in initial set of images (incl. info on licensing/credit)
- [x] get feedback from business-planning-wg

**Comment by benhylau** [comment]
Look and Feel folder -> https://drive.google.com/drive/folders/1URLZzO0P2IuLjRzvmg_C3ecV0N54GbeJ

**Comment by uditvira** [comment]
Moved images in and created a spreadsheet tracking relevant details https://docs.google.com/spreadsheets/d/1c_RahF4QAn7JWfkchQSbjF-caz8Xlbjp4reAtjmfH2w/edit#gid=0

**Comment by dcwalk** [comment]
Took a quick look -- I think looks good. Tho not all the images from our deck are there, could we have them all added?

**Comment by uditvira** [comment]
This done. Here's the spreadsheet (with image previews!) https://docs.google.com/spreadsheets/d/1c_RahF4QAn7JWfkchQSbjF-caz8Xlbjp4reAtjmfH2w/edit#gid=0

**Comment by dcwalk** [comment]
these look good! Yay! I'm gonna actually close out this issue :tada:
