### ISSUE TITLE
Publish "How to bear coronavirua capitalism" on IPFS

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/organizing#258]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** Publish content onto IPFS and announce.  

## To Do

- [x] Request permission from Haymarket Books to publish YouTube content publicly
- [x] Download and publish content onto IPFS
- [x] Respond back to Haymarket Books
- [x] Announce on Twitter (with timecode bookmark to relevant segment)

**Comment by benhylau** [comment]
Published `QmZREJUyVjE1z15ks7mxfw2MLnXR5qTme4PZAtPVNAJvad`

Available on:
- https://ipfs.io/ipfs/QmZREJUyVjE1z15ks7mxfw2MLnXR5qTme4PZAtPVNAJvad
- https://ipfs.infura.io/ipfs/QmZREJUyVjE1z15ks7mxfw2MLnXR5qTme4PZAtPVNAJvad
- (with bookmark) https://live.groundupworks.com/?vod=QmZREJUyVjE1z15ks7mxfw2MLnXR5qTme4PZAtPVNAJvad&from=1170
- (host-at-home) https://github.com/tomeshnet/meshstream

**Comment by dcwalk** [comment]
Proposed tweet: "We are inspired by what Naomi said at the teach-in, about the urgent need to develop information redundancies and new tools of civil disobedience without relying on corporate platforms."

**Comment by benhylau** [comment]
I tweeted something from personal and RT'd with the org account, but you can direct tweet the above with this link which I didn't use in mine, makes sense to come from hypha account:
https://live.hypha.coop/?vod=QmZREJUyVjE1z15ks7mxfw2MLnXR5qTme4PZAtPVNAJvad&from=1170

**Comment by dcwalk** [comment]
I won't make a new tweet for this version then. If you want to put the next video on IPFS  I can tweet with this plan: https://www.youtube.com/watch?reload=9&v=6Gi5qGHRJ9c
