### ISSUE TITLE
Apply for COVID-19 financial support programs

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/organizing#261]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #240   
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** Continue monitoring COVID-19 support programs we are eligible for and apply to them.  

Discussed Finance WG responsibilities with @dcwalk at _2020-04-09 Hypha Worker Co-op: Finance_.

Resources:
- https://blog.wagepoint.com/all-content/coronavirus-covid-19-key-resources-for-small-business-owners

## To Do

- [x] call wagepoint to try and apply for 10% wage subsidy this payroll period
- [x] make sure we are set up for 10% wage subsidy in the next 2 (or more) pay periods
- [x] investigate eligibility for 75% wage subsidy
- [x] BCAP $40,000 loan - review in 2 weeks to see if requirements have changed and if we can apply https://github.com/hyphacoop/organizing-private/issues/35
- [x] ~complete Toronto business impact survey: https://s.cotsurvey.chkmkt.com/?e=192083&d=e&h=C10B481F4DB6030&l=en~ Expired
- [x] keep watch of Ministry of Finance, consultations soon: https://news.ontario.ca/mof/
- [x] keep watch of Toronto (municipal) support programs
   - responded to #309 Recovery & Rebuilding Toronto survey
- look into CWCF support programs after federal options (tracked in separate issue)

**Comment by YurkoWasHere** [comment]
> call wage point to try and apply for 10% wage subsidy this payroll period

Contacted Wage Point regarding rolling it back. Have not heard back yet.

Doing some research I don't think they will be able to backdate it to march 18. However it seems we can apply to CRA for it at the end of the year if we keep track of it
(https://www.canada.ca/en/revenue-agency/campaigns/covid-19-update/frequently-asked-questions-wage-subsidy-small-businesses.html#h9)

**Comment by YurkoWasHere** [comment]
> investigate eligibility for 75% wage subsidy

**Comment by YurkoWasHere** [comment]
> :heavy_check_mark:  call wage point to try and apply for 10% wage subsidy this payroll period

Seems march's subsidy was applied.

**Comment by benhylau** [comment]
## CERB update

This is a personal application.

- https://duttonlaw.ca/canada-emergency-response-benefit/
    >Update April 15: The Government of Canada announced on April 15 that CERB eligibility will be extended to workers earning $1000 or less and workers who have exhausted their EI regular benefits and are unable to find work as a result of the COVID-19 outbreak. Read more here.
    - Also contains some info about employer responsibilities
- To apply: https://www.canada.ca/en/services/benefits/ei/cerb-application.html

**Comment by benhylau** [comment]
To speak with an agent about CERB, or CRA My Account:
I called CRA at 1-800-959-8281, waited more than 1 hour, eventually connected but microphone died :(

Then I called the CERB line **1-833-966-2099**, and after going through the menu, connected immediately. So if you have personal questions around CERB, call this number :)

Q: **Variable work** what if in a 4-week period, we are engaged in occasional work, but never paid more than $1,000 in the period?

A: Initially, you couldn't work at all. Now with the updated requirements, even if you work one or two days a week, as long as you don't make more than $1,000 in the 28-day period, and you meet other requirements, you are 100% eligible.

Q: **Employment status** we are a worker co-operative, so everyone working is also an owner. Would that make us self-employed?

A: If you are getting T4s you all all employees, not self-employed. If you are getting a T4A, it's a bit more complicated. (Everyone at Hypha is getting a T4, so we are all employees.)

Q: **Corporate income tax return** as a new company, Hypha hasn't filed our first annual return, but some people have income in last 12 months from other sources. That's okay even if they are currently employed at Hypha?

A: Yes. $5,000 income from all sources for the person.

Q: **Resident status** is this [tax resident](https://www.canada.ca/en/revenue-agency/services/tax/international-non-residents/information-been-moved/determining-your-residency-status.html) or have to be physically in Canada right now?

A: Eligible as long as you are a resident of Canada for income tax purposes. It does not matter where you physically are during the period.

Q: **CEWS** Do you have information about the CEWS?

A: Not right now, but it's rolling out. Call back next week :)

**Comment by benhylau** [comment]
- [ ] @YurkoWasHere follow up on CEWS this week
- [ ] @YurkoWasHere follow up on BCAP in June

**Comment by benhylau** [comment]
From April 30 meeting:
- [ ] @YurkoWasHere call Desjardins and inquire about BCAP + other credit availability based on our situation

**Comment by YurkoWasHere** [comment]
**CEWS**

Work book to calculate eligibility
- https://www.canada.ca/content/dam/cra-arc/serv-info/tax/business/topics/cews/cews-calculation.xlsx

On Sheet:
**Employee  at arm's length: yes/no**   - All of us are NO since we are owners.
This means is that employees MUST have been on the payroll during Jan1 - March 15.  Prevents owners from adding themselves and family to the payroll now and collect the money from the GOVT.

**Average   weekly gross pay Jan 1 to Mar 15 2020** - We need to re-calculate our payroll to WEEKLY AVERAGES.  Strong recommendation to keep this calculation available for audits.

Eligibility: An employee must not have gone 14 or more days without remunerations during the claim period

**Comment by YurkoWasHere** [comment]
CEWS Call
:computer:  [Slides](https://docs.google.com/presentation/d/1FT_qq7YM4EGD_p-C7vOcTfXY_IfIrnJorjl52W_Xkvg/edit#slide=id.g7718f475e4_0_469) :notebook:  [rough notes](https://hackmd.io/iR-iZLCsRkaH-tSwXhH4PQ?edit)

Summary
- TWS - 10% payroll subsidy
  - Already collecting it 10% given back from source deductions

- CEWS - 75% payroll subsidy
  - Because we are OWNERS and a STARTUP the amount we can get back is minimal ($65)
  - We an apply to BOTH, could bump up how much we get by a little
  - Lots of math to get to the numbers that WILL most likely by audited

- CEBA - 40k Loan 25% Forgivable
   - Don't Qualify
  - :x:  Proove 20k to  1.5M payroll in 2019

- BCAP - "line of credit" like loan
  - :x: Credit worthy company
  - :x: They ask for 3 years of tax returns 

- CECRA - Rent subsidy for commercial 
  - :x: we have no rent

- IRB,"EYARB" :question:  - Some sort of other benefits
 - Maybe applicable to us as tech workers and startup
 - Via Industry Canada
 - Not sure spelling or name, was said verbally
 - Asked for clarification

**Comment by YurkoWasHere** [comment]
The amount we can get back now that payroll has been completly filled out is
- We will continue with TWS 10% Payroll Subsity
- We will confirm actual numbers
- Run this by the ACCOUTNANT
- Submit CEWS end of June

**Comment by YurkoWasHere** [comment]
CEWS is NOT an option after all 
Closer examination of our books (previous numbers where based on projections)

NO invoices issues in JAN-FEB (Accrual Method)
NO payments received JAN-FEB (Cash Method)

This means we have NOT had a 15-30% reduction

We will continue with 10% TWS

**Comment by YurkoWasHere** [comment]
Look into CWCS Grant

**Comment by YurkoWasHere** [comment]
CWCS Emergency Relief/Survival Planning Funding [Source](https://canadianworker.coop/wp-content/uploads/2020/05/Emergency-Relief-Technical-Assistance-information-sheet_fnl-1.pdf)

-Up to $ 2,000
- hire a worker co-op developer or other consultant to enable the worker co-op to develop and/or navigate their survival or continuity plan
- A co-op’s prospects for survival will need to be evident in order to qualify for the grant. 
- must be a CWCF member✔️ 
- Merit of assistance sought is judged likely to help the co-op survive the pandemic

[Application Form] (https://canadianworker.coop/wp-content/uploads/2020/05/Emergency-Relief-Technical-Assistance-application-form_fnl-1.pdf)

- Amount Requested
- Name of Co-op Developers’ Network developer or other consultant who has been asked to carry out the work: (Please provide a short bio of qualifications about your selected Developer/consultant. 
- Describe how COVID19 has affected the coop: current state and tentative future plans
- Proposed work to be carried out by the co-operative developer or consultant
- Project Budget (source of revenue, amount$, confirmed Y/N
- Expenses
