### ISSUE TITLE
Request OHSA Training Compliance Audit

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/organizing#266]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #217  
🗣 **Loomio:** N/A  
📅 **Due date:** June 30, 2021  
🎯 **Success criteria:** Have audit with report of how we are doing on OHSA policies and training  

From Workers Health & Safety Centre:
> The province's Occupational Health & Safety Act and its regulations include literally hundreds of references pertaining to the employer's duty to provide training, education and information to workers, supervisors and other workplace parties.
> 
> To assist you, **the Workers Health & Safety Centre offers a free training compliance audit and written report.** The audit consists of a 30-minute consultation. A highly qualified WHSC compliance coordinator will come to your workplace, at your convenience. They will help guide a focused discussion on equipment, work stations, work processes, chemicals and any other potentially hazardous aspects of your workplace.

See more: https://www.whsc.on.ca/Resources/For-Employers/Training-Compliance-Audit

## To Do

- [ ] Q1 2021 request training from https://www.whsc.on.ca/Resources/For-Employers/Training-Compliance-Audit

**Comment by LexaMichaelides** [comment]
Backing this up to "Trying to comply with OHSA standards:

> Employers must post a range of health and safety information including:
> - [x] [Occupational Health & Safety Act](https://drive.google.com/file/d/1q4MdcXMWcQ9InAaHRlUgR4E6MkH4fVlV/view?usp=share_link) and any explanatory material prepared by the MOL in English and the main language spoken in the workplace. [Technically this is a readable pdf in the Google Drive folder but just an image on the bulletin board)
> - [x] [Ministry of Labour’s Health & Safety at Work: Prevention Starts Here poster](https://drive.google.com/file/d/1xB9T_Y_cP_K7vSc9gq0WIk8jHMCjad0r/view?usp=share_link), and
> - [x] [WSIB’s In Case of Injury—1234 poster.](https://drive.google.com/file/d/1iayd0r1D9oeBjAefiN8prZixElujfiVv/view?usp=share_link)
> - [ ] workplace occupational health and safety policy [I don't think we have one]
> - [ ] workplace violence and harassment policies [I don't think we have one]
> - [ ] names, work locations and contact information for JHSC members [I don't think we have a JHSC]

Additional functional posters we use:
- [Employment standards in Ontario](https://drive.google.com/file/d/1b2stZyIXaCsNZ0EDaIM-PmBdu611yyRl/view?usp=share_link)
- [Ergonomic poster](https://drive.google.com/file/d/1XJ8KfGk_dzgIU5_fL9sswvgJcJ74S784/view?usp=share_link)
- [Right to refuse unsafe work](https://drive.google.com/file/d/1kZO-la08D5Epdpr9MZl_FV6aN-E4ojox/view?usp=share_link)
- [covid safety](https://drive.google.com/file/d/1k3eaVPB3KblXOk6n0hDM8D0mSdVrELFi/view?usp=share_link)


**Things we need:**
- [For a workplace with 6 - 19 workers](https://www.ontario.ca/page/guide-health-and-safety-committees-and-representatives#section-3): You are required to have **one health and safety representative** who is selected by the workers they represent. If a designated substance regulation applies to your workplace, you are required to have a JHSC.
- [ ] workplace occupational health and safety policy [I don't think we have one]
- [ ] workplace violence and harassment policies [I don't think we have one]

**Comment by benhylau** [comment]
Call 1.888.869.7950 to see what we must absolutely do given our remote + sw env.
