### ISSUE TITLE
Publish document templates

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/organizing#273]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** 30 June 2020  
🎯 **Success criteria:** Publish template documents publicly.  

Document templates like our _Client Agreement_ and _IP Agreement_ are currently in a private gdrive folder. According to our [working open](https://handbook.hypha.coop/working-open.html) policy these should be made public:

- Client Agreement
- Employee and Contractor Intellectual Property Agreement
- Job Description
- Letterhead
- Employee Agreement
- (Person) Contractor Agreement
- (Organization) Contractor Agreement with Intellectual Property Agreement

There are a couple possible places we can put these: (1) public gdrive, (2) as markdown in handbook, (3) as markdown in new repo (maybe with build scripts to output PDFs using markdown-pdf based on yml input).

## To Do

- [x] Finish writing all the documents
- [x] Decide on how to make them public
- [x] Publish documents
- [x] Add README that contains disclaimer and jurisdiction information as they apply
- [x] Redirect all our shortlinks to their new home

**Comment by benhylau** [comment]
- End-June link to all the above docs in gdoc (move templates to public)
- Q3 revisit

**Comment by patcon** [comment]
dc suggested doc sprint to wrap this

**Comment by benhylau** [comment]
@writerly03 there is already a start of this from @dcwalk https://github.com/hyphacoop/handbook/pull/150

**Comment by writerly03** [comment]
Sorry - someone will have to walk me through how to update the pages that Dawn has already started. The templates required are gathered in a public GDrive folder here: https://drive.google.com/drive/folders/1w-s-HH0J01ZI2sFTv1__tmoDPt9On0Ay?usp=sharing

**Comment by benhylau** [comment]
@LexaMichaelides @benhylau will finish this ticket and merge https://github.com/hyphacoop/handbook/pull/150

**Comment by benhylau** [comment]
Updated shortlinks: https://github.com/hyphacoop/configurations/commit/1e0802cda4abf3d650ee3f65a1127e896b808bea

Updated and merged PR:
- https://github.com/hyphacoop/handbook/pull/150/files
- https://github.com/hyphacoop/handbook/pull/184/files

Have a look at the new page!
https://handbook.hypha.coop/templates.html
