### ISSUE TITLE
Set up prometheus server

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/organizing#276]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #253  #172
🗣 **Loomio:** N/A  
📅 **Due date:** end-Sept  
🎯 **Success criteria:** Our staging and production infrastructure is monitored on a Prometheus dashboard and we are notified if problems occur.  

In our discussions, this was:
>- VM6: prom monitoring 💧💾 (September)

## To Do

- [ ] @YurkoWasHere will host a workshop in February prometheus setup
  - [ ] Produce deb package for redistribution (via workshop)
- [ ] Build Anisible script to deploy server

**Comment by garrying** [comment]
This might get bumped to early March. Pending the workshop. @YurkoWasHere to create follow up tasks in March/April.
