### ISSUE TITLE
Member loan as emergency credit

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/organizing#278]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** Get better understanding of member comfort with member loans.  

Finance WG has two KRs in our OKR:
- "Devise strategy to secure support funding and credit for business to cope with uncertainties"
- "Capture evaluation of our capacity to support members and neighbours"

As part of fulfilling these two KRs, we want to explore the option of **"member loan as emergency credit"**. To be clear, we are not asking to raise funds immediately, but to get (1) a general understanding, and (2) a commitment, from members of when and how much money they are willing to put in to the co-operative as a member loan.

## To Do

- [ ] Discuss if this is appropriate
- [ ] Define conditions where we will collect this money
  - e.g. if Hypha cannot pay our bills
  - e.g. if a member has a personal emergency
- [ ] Poll member on amounts

**Comment by benhylau** [comment]
Haven't needed this. Won't do for now.
