### ISSUE TITLE
Review and update our Working Open Statement

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/organizing#280]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** Approved and merged iteration of our working open guidelines that reflects our current practices in Q2 2020.  

Coming out of our drafting of the intellectual property agreeement, a comment thread around confidential information (vs. our working open statement) came up that merits a review of how we codify our practices.

Copying here:
> B: Rewrite this section with... "while we have a Working Open culture, and... there are confidential information involved, for example in client work..."
>
> A: If we say have a working open culture and we want to have a confidentiality clause, we should be explicit with the scope of confidential information.
> Shall we start by making a list?
>
> These should definitely be confidential:
> - passwords, credentials, etc.
> - sensitive personal information
> - client/partner information that we don't have consent to share
>
> items that might need discussion:
> - pre-sales deals
> - accounting and pay information
>
> B: I think we should refer to the Working Open page as this is a changing list and perhaps overly specific. We can also take a snapshot as exhibit.
>
> C: Reading this we need to update our working open statement. Can be much more robust now. I'm copying over stuff here to an issue, makes sense to do in tandem with data/privacy policy

And (current) language from IP agreement:
> 8. Confidentiality. As an employee or contractor of the Co-operative, you will have access to sensitive confidential information that is important to the Co-operative's business. You are responsible for keeping this information confidential, including after you end your work for the Co-operative.
>
> The Co-operative has a _working open_ culture and clear guidelines on the scope of confidentiality and confidential information, as well as our practices of consent and privacy. You are expected to adhere to the current version of these guidelines in your work, which are available in our handbook: https://handbook.hypha.coop/working-open.html. 
> 
> The Co-operative's confidential information is sensitive and you are expected to treat it as such. You agree to only use the Co-operative's confidential information for the purpose of performing your job and for the benefit of the Co-operative. You will do your best to keep confidential information secret. If you are not sure if something is confidential information, you should assume that it is, until you can confirm otherwise.
> 
> A snapshot of the _working open_ guidelines is included as Exhibit B. You acknowledge you have reviewed Exhibit B and will adhere to the guidelines and its future revisions.

## To Do

- [x] review working open guidelines
- [x] brainstorm / document updated data types and existing practices
  - [x] ensure confidential info from IP agreement accurately reflected
  - [x] look at client projects cases
- [x] Update handbook https://github.com/hyphacoop/handbook/pull/79

**Comment by benhylau** [comment]
Did a first pass https://github.com/hyphacoop/handbook/pull/79/files @uditvira @dcwalk

**Comment by dcwalk** [comment]
Reviewed and feels okay for a first pass. I think there is more to deal with down the road as a future iteration

**Comment by benhylau** [comment]
Thanks and updated based on comments. @dcwalk feel free to merge if looks ok to you now.

**Comment by dcwalk** [comment]
@benhylau merged!

**Comment by dcwalk** [comment]
Going to close this, think this unblocks #95
