### ISSUE TITLE
Retire Rebrandly and transfer to new shortlinks implementation

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/organizing#282]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #262  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** We've successfully sunsetted/retired Rebrandly and adopted our new shortlink service. 

## To Do

- [x] update services inventory to reflect new shortlinks process
   - rebrandly moved to retired and shortlinks-site added
- [x] update handbook to reflect new shortlinks process
  -  information seems generic (https://handbook.hypha.coop/guides.html#managing-shortlinks)
  -  [x] PR https://github.com/hyphacoop/handbook/pull/75 (Fixed broken mailcow example)
- [x] scrub circle-ci job 
  - https://github.com/hyphacoop/worker-coop-scripts/blob/master/.circleci/config.yml#L85-L99 
  - [x] PR - https://github.com/hyphacoop/worker-coop-scripts/pull/9
- [x] add README to describe what this is and how it's deployed (can be 2 sentences)
  - [ ] PR - https://github.com/hyphacoop/shortlinks/pull/33
     - [x] Update any changes made to code in https://github.com/hyphacoop/shortlinks-site
     - [x] Document changes as needed
  - [x] Create Readme for https://github.com/hyphacoop/shortlinks-site
-  ~~style new shortlinks site: https://github.com/hyphacoop/shortlinks-site~~

**Comment by dcwalk** [comment]
Is there any way we can integrate the two shortlink repos? I'm a little confused as to why we need two @YurkoWasHere?

 - https://github.com/hyphacoop/shortlinks-site
- https://github.com/hyphacoop/shortlinks

**Comment by YurkoWasHere** [comment]
@dcwalk 

Before we had shortlinks -> worker-coop-scripts -> rebrandly

shortlinks-site 
- replaced worker-coop-scripts
- self contained processor
- to be forked by others

shorlinks 
- "database" of hypha's shortlinks list

**Comment by YurkoWasHere** [comment]
not sure who to flag for PR requests..

**Comment by benhylau** [comment]
I _think_ we can merge them and have `shortlinks` as an "example". But I think this is a small example of the larger convo on how infra likes to separate "common infra" (like ansibles) and "config" (hypha-specific). Let's make this an infra discussion in next meetings.

Even if we don't merge them, we should definitely change to names, now it's hella confusing :)

**Comment by dcwalk** [comment]
There are patterns for having them in the same place common to other projects, e.g. having a .env sample, having a config file with meaninful variable names, strong documentation and separation of where config is stored, etc...

Given how small the nature of this is it seems a candidate for having in a single repo over two

**Comment by benhylau** [comment]
@ASoTNetworks is working on the ansibles for website and this. It's being worked on as part of this.

**Comment by benhylau** [comment]
1. Move the [configurations csv](https://github.com/hyphacoop/shortlinks/blob/master/shortlinks.csv) into new `configurations` repo under `hyphacoop/shortlinks/`
1. Rename [shortlinks-site](https://github.com/hyphacoop/shortlinks-site) to links.hypha.coop
1. Archive `shortlinks`
1. Update both README files to reflect current status

**Comment by benhylau** [comment]
@ASoTNetworks https://github.com/hyphacoop/shortlinks/pull/33 links to a deprecated repo, and https://github.com/hyphacoop/link.hypha.coop doesn't tell me how it gets deployed (I assume is thru https://github.com/hyphacoop/link.hypha.coop/blob/master/.travis.yml to https://github.com/hyphacoop/ansibles/blob/master/deploy-hypha-sites/deploy-site-link.hypha.coop.yml) but that's never mentioned in the README.

I suggest that you handle to two existing PRs on the repo, then send a new PR to reflect the actual deployment setup.
