### ISSUE TITLE
Hire, onboard, and plan supervision for summer internship

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/organizing#286]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** Complete internal hiring process, University requirements, and project/supervisory plan for summer work

...

## To Do

- [ ] @benhylau Review and sign initial paperwork
    - [ ] WSIB Form
    - [ ] Practicum Agreement form
    - [ ] add to acknowledgement "email to Dawn Walker <operations@hypha.coop>"
- [ ] @benhylau complete hiring and on boarding process
- [ ] @uditvira develop summer plan with student
    - [ ] review and finalize internship project
    - [ ] set OKRs
    - [ ] determine check-in schedule

**Comment by uditvira** [comment]
@benhylau can you check if these tasks look accurate on your end?

**Comment by uditvira** [comment]
@benhylau wondering if you've had a chance to look at this issue? We should send back to WSIB/Practicum Agreement form

**Comment by benhylau** [comment]
Thanks for the reminder, I will have everything signed and returned this week. Let me know if you want to be the signer/reply to, otherwise I will sign and reply.

I also should have all Hypha docs for Hank to review next week.

**Comment by benhylau** [comment]
We don't need to do this anymore. Hank got the placement that @dcwalk forwarded :)
