### ISSUE TITLE
Deal with Matrix history/Purge room job

### ISSUE THREAD

**Issue by YurkoWasHere** [hyphacoop/organizing#288]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** # 
🗣 **Loomio:** N/A  
📅 **Due date:** 8/19/2020
🎯 **Success criteria:** Create a cron job to purge rooms

## To Do

- [x] Investigate how to purge content from a room
- [x] Get direction on 
  - [x] Which rooms should be purged
  - [x] How long should we keep content
  - [x] How often to purge (daily, weekly, monthly, etc)
- [x] Tell everyone `@room` we'll start the purge
- [x] Create script
- [x] Create cron job
- [x] Document/Repo

**Comment by YurkoWasHere** [comment]
Script to purge room

```
# User MUST be server admin
USERNAME="@yurko:networkedserver.net" 
TOKEN=$(sudo -u postgres -i psql -d synapse -A -t  -c "select token from access_tokens where user_id='$USERNAME' limit 1;")

# If Alias figure out the roomid
#ROOMID=$(sudo -u postgres -i psql -d synapse -A -t  -c "select room_id from room_aliases where room_alias='$ROOM';")
# Manually specify roomit
ROOMID='!GQKeTRbkXcglrIiFMI:networkedserver.net'

# How far back to go

FROMDATE="12 month"
TIME=$(date "+%s%N" -d "FROMDATE" | cut -b1-13) 

curl -k  -XPOST -d"{\"delete_local_events\": true,\"purge_up_to_ts\": $TIME}" "https://localhost:8448/_synapse/admin/v1/purge_history/$ROOMID?access_token=$TOKEN"
```
# TODO
- [ ] Read list of rooms (maybe in github?)
- [ ] Parse list
- [ ] Loop through and apply

**Comment by garrying** [comment]
From the [2020-05-20 standup](https://github.com/hyphacoop/organizing/pull/291/files#diff-f72e628ca5856951fafcb620086af30aR72):
- `#todo documentation of process`
- `#todo set in topic`

**Comment by benhylau** [comment]
@ASoTNetworks v

`@room` we will be starting to wipe all Hypha rooms periodically to keep only the most recent 3 months of history on this homeserver. Please refer to our handbook's [How long we keep data](https://handbook.hypha.coop/data.html#how-long-we-keep-data) for details.

**Comment by ASoTNetworks** [comment]
I have created a script that will loop through `hypha-rooms.txt` which contains a list of channel IDs that will be purged. It will be put onto github when we decided on where to put config data for scripts.

Below is the crontab that runs at 3AM every Sunday.
`0 3 * * 7 /root/bin/purge-matrix-room.sh /root/bin/hypha-rooms.txt`

**Comment by ASoTNetworks** [comment]
Here is the script:
```
#!/bin/bash 

# Change to script directory
cd "$(dirname "$0")"

# Check if file is defined
if [ ! $1 ]
then
	echo "No room file defined"
	exit 1
fi
if [ ! -f $1 ]
then
	echo "Defined path is not a file"
	exit 2
fi

# Admin user token
TOKEN="8Y9OvLjAR0gAY45MZe3...."

# Set the timestamp 3 months ago
FROMDATE="-3 month"
TIME=$(date "+%s%N" -d "$FROMDATE" | cut -b1-13)

# Loop through defined file
while read ROOMID
do
	echo "Purging: $ROOMID"
	curl -k  -XPOST -d"{\"delete_local_events\": true,\"purge_up_to_ts\": $TIME}" "https://localhost:8448/_synapse/admin/v1/purge_history/$ROOMID?access_token=$TOKEN"
done < ${1}

# Purge remote content
echo "Purging remote content"
curl -XPOST -d '{}' "http://localhost:8008/_matrix/client/r0/admin/purge_media_cache?before_ts=$(echo $(($(date -u +%s%N)/1000000)))&access_token=$TOKEN"
```

**Comment by benhylau** [comment]
Where should we put it? This is the time to figure out where we're gonna put everything lol

**Comment by benhylau** [comment]
Make public repo called `configurations` and put loose scripts in there. This doesn't need to be pulled by hypha since it runs on tomeshnet VM, but in the future configs like BBB server config custom for us, will live here.

```
root/
  -> hyphacoop/
  -> tomeshnet/
```
