### ISSUE TITLE
Jitsi reconnection loop

### ISSUE THREAD

**Issue by YurkoWasHere** [hyphacoop/organizing#289]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** Find cause and successfully run *1* month without issue

Scenario
- First user joins and creates room. Everything is fine.
- Second users joins and both users are removed from chat with a "Something went wrong" error, attempting to re-connect without success.

## To Do

- [ ] ~~Collect logs when issue occurs~~
- [ ] ~~Identify what component is causing issue~~
- [ ] ~~Find an implement solution~~
- [ ] ~~Monitor~~

**Comment by YurkoWasHere** [comment]
to be clear
- connected to prosody - first person no problem
- connected to prosody - second person - kicked out both uses with reconnect message.
- logs showed the following during second person join

```
Jicofo 2020-05-16 21:47:20.779 INFO: [65] org.jitsi.jicofo.xmpp.FocusComponent.handleConferenceIq().401 Focus request for room: fireeverywhere@conference.jitsi.hypha.coop
Jicofo 2020-05-16 21:47:20.834 INFO: [93] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Chat room event ChatRoomMemberPresenceChangeEvent[type=MemberJoined sourceRoom=org.jitsi.impl.protocol.xmpp.ChatRoomImpl@529ab212 member=ChatMember[fireeverywhere@conference.jitsi.hypha.coop/a62e7c3d, jid: null]@1183411608]
Jicofo 2020-05-16 21:47:20.834 INFO: [93] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Member fireeverywhere@conference.jitsi.hypha.coop/a62e7c3d joined.
Jicofo 2020-05-16 21:47:20.835 WARNING: [93] org.jitsi.jicofo.bridge.BridgeSelectionStrategy.log() Failed to select initial bridge for participantRegion=null
Jicofo 2020-05-16 21:47:20.835 SEVERE: [93] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Can not invite participant -- no bridge available.
Jicofo 2020-05-16 21:47:20.836 WARNING: [93] org.jitsi.jicofo.bridge.BridgeSelectionStrategy.log() Failed to select initial bridge for participantRegion=null
Jicofo 2020-05-16 21:47:20.836 SEVERE: [93] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Can not invite participant -- no bridge available.
Jicofo 2020-05-16 21:47:21.143 INFO: [93] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Chat room event ChatRoomMemberPresenceChangeEvent[type=MemberLeft sourceRoom=org.jitsi.impl.protocol.xmpp.ChatRoomImpl@529ab212 member=ChatMember[fireeverywhere@conference.jitsi.hypha.coop/a62e7c3d, jid: null]@1183411608]
Jicofo 2020-05-16 21:47:21.143 INFO: [93] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Member fireeverywhere@conference.jitsi.hypha.coop/a62e7c3d is leaving
Jicofo 2020-05-16 21:47:21.143 INFO: [93] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Removed participant: true, fireeverywhere@conference.jitsi.hypha.coop/a62e7c3d
Jicofo 2020-05-16 21:47:21.207 INFO: [93] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Chat room event ChatRoomMemberPresenceChangeEvent[type=MemberLeft sourceRoom=org.jitsi.impl.protocol.xmpp.ChatRoomImpl@529ab212 member=ChatMember[fireeverywhere@conference.jitsi.hypha.coop/8a8baba2, jid: n4k3yvwuwnm__cxr@jitsi.hypha.coop/WOhDdt-E]@1144287934]
Jicofo 2020-05-16 21:47:21.207 INFO: [93] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Owner has left the room !
Jicofo 2020-05-16 21:47:21.208 INFO: [93] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Member fireeverywhere@conference.jitsi.hypha.coop/8a8baba2 is leaving
Jicofo 2020-05-16 21:47:21.208 INFO: [93] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Removed participant: true, fireeverywhere@conference.jitsi.hypha.coop/8a8baba2
Jicofo 2020-05-16 21:47:21.211 INFO: [93] org.jitsi.jicofo.FocusManager.log() Disposed conference for room: fireeverywhere@conference.jitsi.hypha.coop conference count: 0
```
- restarted videobridge2
- experience did NOT change
- restarted Prosody
- re joined with two people immediately
- lasted for about 5-10 seconds before being kicked out (don't know if related)
- re joined about 10-15 seconds after
- seemed to work fine
- had a ~3 hour call with 4 video streams without interruptions (less remote signal strengthdegradations)

**Comment by benhylau** [comment]
Think this happened to me multiple times at hypha's jitsi, and one time at http://meet.mayfirst.org (that's an audio-only instance).

**Comment by benhylau** [comment]
The problem occurs quite often and we will leave Jitsi as is for now. Reconsider spinning it up when new version comes up, and after everything else is moved to Prod.

**Comment by benhylau** [comment]
Hasn't seen it happen lately, and @ASoTNetworks thinks it only happens on reboots which we don't do now.
