### ISSUE TITLE
Improve workflow to receive invoices and bookkeep

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/organizing#298]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** Q3 2020  
🎯 **Success criteria:** Explore options and implement what we decide.  

Since we started, platforms have added:

- Transferwise now supports
  - Quickbooks integration (done)
  - auto-deposit money we receive to our bank (done)
- Desjardins now supports
  - etransfer payment out (prev only in)

We also acquired new accounts:

- Open Collective
- Stripe
- Paypal

We also have a new Finance mission, to be a fiscal host thru Open Collective. We should re-evaluate how our platforms are integrated and the processes to make sure we utilize the tools to minimize overhead.

## To Do

- [x] Evaluate new features offered by our platforms
- [x] Discuss integrations and processes
  - Update Transferwise setup?
  - ~~Set up Desjardins to auto-deposit transfers?~~ (no support)
  - ~~Update payment options on invoices?~~ (not necessary)
  - Update Open Collective integrations?
- [x] TransferWise <> QB integration
- [x] Wagepoint <> QB integration ([steps](https://wagepoint.kayako.com/article/58-quickbooks-online-integration)) @benhylau 
- [x] Integrate Open Collective with Transferwise ([steps](https://docs.opencollective.com/help/fiscal-hosts/payouts/payouts-with-transferwise)) @YurkoWasHere 
- [x] upgrade from Quickbooks Essentials ($35) to Plus ($50) plan (Classes & Projects)
- [x] CRA MyBusiness auto-deposit to bank
- [ ] Implement and document

**Comment by benhylau** [comment]
Since we upgraded QB to support multi-currency, I have enabled it in QB and integrated TransferWise as follow, with 3 new accounts pulling data beginning **July 1, 2020**:

<img width="652" alt="Screen Shot 2020-07-15 at 8 07 01 AM" src="https://user-images.githubusercontent.com/2261308/87510165-56eaf980-c673-11ea-92f7-737819603146.png">

I also enabled some other new features by TransferWise:

- Marked our Desjardins recipient as [primary account](https://transferwise.com/help/12/managing-your-profile/2932129/nominating-a-primary-account) so other TransferWise users can simply pay us by our email, and the money will directly go to our Desjardins account
- Multi-admin is now supported, I made @YurkoWasHere admin

**Comment by benhylau** [comment]
>Set up Desjardins to auto-deposit transfers?

@YurkoWasHere do you know if this is possible? So if people send us email transfers, they get auto-deposited.

**Comment by benhylau** [comment]
Suggestions from Rodica:
- get a corporate credit card to put all expenses and sync into QB
- QB email inbox for sending receipts that automatically get into our books
- Rodica to hide unused accounts in Chart of Accounts
- Rodica to see if we can match Chart of Accounts to Posting Journal without conversations

**Comment by patcon** [comment]
Hopefully ok that I captured allhands todo for QB upgrade here above

**Comment by benhylau** [comment]
QB upgrade here is correct and CRA one I just added tks

**Comment by benhylau** [comment]
Paypal is tied to CC and bank account, for paying other people, or receiving payments.
