### ISSUE TITLE
Run biweekly pcc / coop reading group until end Jul

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/organizing#303]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  hyphacoop/organizing-private/issues/43
🗣 **Loomio:** N/A  
📅 **Due date:** Fri, June 12, 2020  
🎯 **Success criteria:** Have a standing time for a biweekly reading group.  

#### TO Platform / Co-ops Reading Group 

📅 Time:       Bi-weekly, 5:00-6:30pm ET  
🎯 Location:   https://bbb.hypha.coop/b/hyp-dpa-tpz 
📔 Notepad:    https://hackmd.io/pyS5mn7tQ5qXMkg5aq0dOg?view  
Cultivator:    dc for first one  

Bi-weekly reading group for Tkaronto-ish folks interested in platform / co-ops.

## To Do

- [x] create poll
- [x] send email
- ~chat @patcon RE: first readings~
- [x] pick time **Fri, June 12**
- [x] send calendar, set up pad: https://hackmd.io/pyS5mn7tQ5qXMkg5aq0dOg?view
- [x] crib / send instructions around moderating, borrow from Data Together reading group?
- [x] run sessions
  - [x] jun 18 Inequality and Gig Labour
  - [x] jul 2 Co-ops and Platform Co-operativism
  - [x] jul 16 
  - [x] jul 30
- ~schedule final call end of September @dcwalk~

**Comment by dcwalk** [comment]
Tracking readings here:

## Sessions - [Kickoff] Jun 18 Inequality and Gig Labour

Readings:

- 📚 Platform Capitalism by Nick Srenicek, chapters: “The Long Downturn”  (Links to an external site.)and “Platform Capitalism"  https://mudancatecnologicaedinamicacapitalista.files.wordpress.com/2019/02/platform-capitalism.pdf
- 📚 It’s Not Technology That’s Disrupting Our Jobs by Louis Hyman https://resources.platform.coop/resources/its-not-technology-thats-disrupting-our-jobs/


Optional material:

- 🎬 Reclaiming Work: The Cycle Couriers Subverting The Gig Economy (8') https://www.youtube.com/watch?v=I0Z5PBgwu60&feature=youtu.be
- 🎬 AWAKE Manifest - MTA-LEINN call in the mist of COVID19 #YOUTHinCHARGE (3') https://www.youtube.com/watch?v=z0CBgUTZEcg&t=4s
- 🎬 W1 Lecture (50'): https://archive.org/details/pc-course-platform-coop-gig-economy-inequality-week-1


### Jul 2 - Co-ops and Platform Co-operativism

Readings:

- 📚 Humanity at work. MONDRAGON a social innovation ecosystem case study. The Young Foundation https://agirrecenter.eus/eu/dokumentuak/txostenak/mondragon
- 📚 The Cooperative Moment by Doug O’Brien http://online.fliphtml5.com/caqv/dlan/#p=28
- 📚 Building the Next Economy by Doug O’Brien https://ncbaclusa.coop/journal/2019/fall/building-the-next-economy/
- 🎬 Welcome to MONDRAGON Co-operative Experience (14'): https://www.youtube.com/watch?v=Nw6Kbx6x1c8

Optional material:

- 🔉 Inequality and Precarity in the Platform Economy By Juliet Schor (90') https://soundcloud.com/harvard/hbs-digital-seminar-with-juliet-schor-inequality-and-precarity-in-the-platform-economy
- 🎬 W2 Lecture (50'): https://www.loom.com/share/9b37daf6571745bea2cba580920ea6a4
    - Presentation: https://www.slideshare.net/jmluzarraga/cooperative-entrepreneurship-the-case-of-mondragon-19562019-235135879



### Jul 16

### Jul 30

**Comment by dcwalk** [comment]
I'm in favour of letting this one settle and closing for now. We should plan a follow-up call in the new year with pcc course folks?
