### ISSUE TITLE
Wrap-up from AGM

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/organizing#307]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #102
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** Post-AGM tasks are completed 

After the AGM there is some minor work outstanding based on resolutions for three working groups: `governance` `operations` and `business planning`. This issue is just for immediate post-AGM tasks, not the larger work those WGs will take up

## To Do

- [x] set up final poll on loomio
- [x] file decks/docs used in gdrive
- [x] clean up notes and merge => https://github.com/hyphacoop/organizing/pull/327
    - [x] create appropriate tasks for larger issues: #308 #322 
- [x] do little report back / what worked / what didn't in planning doc
- [x] ensure all members meeting resolutions are properly documented
- [x] ensure bod resolutions are properly documented
- [x] share bylaws where needed (acct)
- [x] update handbook with:
   - [x] bylaws (from #101)
   - [x] board roles and checklist (from #101 we have board role desc) => https://github.com/hyphacoop/handbook/issues/13
   - [x] good member => https://github.com/hyphacoop/handbook/issues/14 (drafted "accountability statement" from AGM)
   - [x] peer feedback (from #202) => https://github.com/hyphacoop/handbook/pull/124

**Comment by dcwalk** [comment]
Rough peer feedback notes (rest in AGM notes):

```
# Peer feedback

Take:
1. Collectively draft good member chat
2. Solicit peer recognition (shoutouts to members) for public sharing
3. Pair / pod folks for feedback, this can be randomly

...

Mechanism:

1. 5 minutes to reflect on your work over last year and areas to identify: 
    
2. choose what to share with your peer/pod (ideally you can share something you want to improve)
3. spend time discussing how to address 
    - peer, pleae follow this 
5. periodic check-in (at quarterly calls)




Anti review:
https://blog.bonus.ly/6-research-backed-reasons-rethink-annual-employee-evaluation
- Negative feedback NEVER GOOD (even is "constructive feedback")
- One-sided is a "blind-spot"
- Always subjective
- Avoid any type of "ranking" or "comparison" ("")


---

Example language (TOP DOWN):
https://www.cultureamp.com/blog/employee-feedback-examples/

1. “Something I really appreciate about you is….”

Example: “Something I really appreciate about you is your aptitude for problem solving in a proactive way.”

2. “I think you did a great job when you…[insert specifics] it showed that you had….”

Example: “I think you did a great job when you ran the all hands meeting. It showed that you are capable of getting people to work together and communicate effectively. I admire your communication skills.”

3. “I would love to see you do more of X as it relates to Y”

Example: “One of your most impactful moments were the insights you gleaned based on Project X. It showed the power of user testing in shaping a feature roadmap and increases the likelihood that we satisfy and delight our users. I’d love to see you do more of this.”

4. “I really think you have a superpower around X”

Example: “I really think you have a superpower around making new hires feel welcome.”
5. “One of the things I admire about you is…”

Example: “One of the things I admire about you is your ability to manage a team remotely.”
6. “I can see you’re having a positive impact in…”

Example: “I can see you’re having a positive impact in your new office, people seem happy.”
7. “Can I share with you a bit of feedback that I/we have been hearing?”

Sometimes a manager will receive feedback on their direct report. This is a tricky situation, because feedback should generally avoid hearsay and focus on an individual’s unique experience. However, you should also have a plan to discussing third party feedback (especially if it comes up often). This phrase is a great way to get the conversation started, and share that it is coming from a third party.
```

**Comment by benhylau** [comment]
@dcwalk think we can get these by Monday to unblock #323?
- AGM minutes approved and merged
- New board resolution signed

**Comment by dcwalk** [comment]
Process for last PR merge to handbook initiated. I'm gonna jump ahead a little bit and merge this so I'm not whelmed with open issues (a break from form, I know!)
