### ISSUE TITLE
Finalize business plan and strategy for Y2 coming out of AGM

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/organizing#308]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #167 
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** Updated business plan for Y2 of Hypha.  

We did a round of updating the business plan before our AGM, but there is some post-meeting work that needs to happen to polish and finalize

## To Do

- [x] review and discuss approach
- [x] brainstorm RE: strategic goals with notes from strategy session at AGM
- [x] cowork to respond to comments / resolve any suggestions and update strategic plan in doc AT NEXT BIZDEV

**Comment by dcwalk** [comment]
Brought this up at our 2020-11-11 bizdev call, comitted to a 30 min co-work to wrap this up next @hyphacoop/business-planning-wg meeting

**Comment by dcwalk** [comment]
Per above, this is done and filed a PDF copy in our folder! ticketing out new activity for future bizdev cowork #376

Parked topics:
- Competitive Positioning
- Budget activity
- "True cost of labour" and how we account for different work styles / efficiency friction
