### ISSUE TITLE
Server setup and access

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/organizing#313]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** Nov. 6, 2020
🎯 **Success criteria:** All members should have VPN access and at least 2 members have tested their access to Production area, and 4 members have tested their access to Staging area.   

Set up dedicated server with Proxmox and network routing. Running docs currently on [here](https://hackmd.io/pElXZTnUTRO1zApxpdBWDw?view).

## To Do

📅 **Due date:** 8/20/2020
- [x] Install Proxmox
- [x] Create Staging and Production areas
- [x] Give VPN access to all members

📅 **Due date:** 9/24/2020
- [x] SSH access distribution 

📅 **Due date:** 11/06/2020
- [x] Develop documentation (keep on hackpad, link from private repo)
    - [x] cowork to transfer docs longterm format -- @yurkowashere ~~@patcon~~ @ASoTNetworks 
    - 2 members follow docs to read a text file on Production
        - [x] ~@benhylau~ gi
        - [x] @YurkoWasHere  
 
📅 **Due date:** 02/02/2021
- [x] Only allow SSH (ip and hostname) through VPN network @ASoTNetworks
- [ ] Drop instructions members follow docs to read a text file on Staging on 02/03/2021

**Comment by benhylau** [comment]
Summary from last infra meeting:
- VPN access for all members
- Deploy keys to all service VMs should be stored locally in each environment's deploying VM, and they should never be copied elsewhere
- Every service we deploy through those have a single `admin` user
- SSH access to the Staging deploying VM is granted to all members via access keys
- SSH access to the Production deploying VM is granted as needed via access keys

Immediate TODOs:
- [ ] @ASoTNetworks research best practice to store secrets outside of source control
- [ ] @ASoTNetworks publish code to public repo (after stripping secrets)

**Comment by ASoTNetworks** [comment]
For OpenVPN to use VPN provided DNS server on Ubuntu based distros install `openvpn-systemd-resolved` using `sudo apt install openvpn-systemd-resolved`

Then add the following lines under `compress` option in the OpenVPN file
```
script-security 2
up /etc/openvpn/update-systemd-resolved
down /etc/openvpn/update-systemd-resolved
down-pre
dhcp-option DOMAIN-ROUTE .
```

**Comment by benhylau** [comment]
Everyone to put SSH pubkey in a place on `configurations` repo. @ASoTNetworks to email with instructions.

```
# patcon
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCvsoPRoJHVXZiXD1iYK13Xx0rhsAL7WQRMdhLYgkw/5vPxWwT+dR4q3Z1zoVWRZHTRsfWQFO+GpqVm9noKtYD6Bjp5FMTwjoWFUrn5rgXS4HviXT0pI1cYcPFpKApTpK40IopbwcNsPF2o8n3J3adJ0rapWhRKFnwcdDtgsrPwg6EGUoqzo/hhSf6vhljOHAPYdgSyQMmkBedU7ndnUPr3uj7zIp3N0j3ytMiyLwsD4Yn0OT3nhByiz7rjHdDEAl3IAaJhf5KvWpLdYcXXG+ITG9dB/CpORpminV4Clu/TJo12uimjwQjKBQm4jiIf6FQQ16C8IHYeC+HazT4yVMDQVBmqODFSkD/+fF174arZStZs3LmqBhlKboPUBAgOS4nZOpmY6RzfEJx2uy01SL2ae6DVGvXiHg2hYYRWPUVgb6Yn2z1xWfowQECkQlEPzRkkhDRlPtZDw9gslw1jOIt5a2vBrSSnLkV/q/mkQisWnJ7m5ren4Eadxi9joZTeOJRuz6/OjTV8Dv3MXVLfABG38wAZy4tmTs3fOx8oRerKSeW/HouYgoouluRoBw/XqBaxdDz/AJ4rwZQni6xIwoAEgHI4dXCWL8hnrFb1Arw3WX/P5bHTZcKHPTOuKfFOGNp2hp/SyeG/EHiYWTgpOK/xbPd+Y7zv8EqmH3ETTcH82Q==
```

**Comment by benhylau** [comment]
@patcon to review https://hackmd.io/pElXZTnUTRO1zApxpdBWDw?view and figure out best way to document this.

**Comment by benhylau** [comment]
@ASoTNetworks can you provide a place where I can commit my pubkey for access?

Also, SSH access should only be via local addresses on the VPN right? I understand that isn't yet implemented, but is that the goal or not?

**Comment by ASoTNetworks** [comment]
SSH to Ansible and front end webservers for both staging and production can be accessed without VPN as they are authed with SSH keys and needed by Travis. All other backend services need to be accessed over VPN or jumped through Ansible host.

For those that want access to staging they can put the pubkey in https://github.com/hyphacoop/configurations/tree/master/hyphacoop/ssh-public-keys and open a pull request.

**Comment by benhylau** [comment]
>All other backend services need to be accessed over VPN or jumped through Ansible host.

This is exactly what I'd like, thanks :)

Is it via a single `admin@` account for these?

**Comment by patcon** [comment]
Yeah, agreed, it sounds great.

One thing for docs might be to give an example of an `ssh-config` file snippet that would make the jumphost happen automatically when ssh'ing to final dest, as explained here:
https://jloh.co/posts/dynamic-ssh-jump-hosts/

**Comment by benhylau** [comment]
That sounds like something useful to link to, and it links to not using Agent Forwarding that led to -> https://matrix.org/blog/2019/05/08/post-mortem-and-remediations-for-apr-11-security-incident#ssh perhaps we should also emphasize don't do Agent Forwarding. Leaving docs up to @ASoTNetworks.

**Comment by patcon** [comment]
I'm removing myself as it was suggested I leave infra wg

**Comment by garrying** [comment]
This is done. We decided to defer the CFT event to another time.
