### ISSUE TITLE
Develop and deploy Ansible for website and light-weight services

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/organizing#314]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** October 1, 2020  
🎯 **Success criteria:** All the public sites and now going to our server and steps to update are clearly documented.  

In our discussions, this was:
>- VM3: website + nginx + dns + link shortener + vision 💧 (June)

## To Do

- Develop ansible roles and deploy to staging
  - [x] Website
  - [x] Link shortener
  - [x] Vision board
- [x] Discuss where to put Nginx and DNS
- [x] Deploy to production
  - [x] Website
  - [x] Link shortener
  - [x] Vision board
- [x] Update existing documentations in current repos about deployment steps

**Comment by benhylau** [comment]
NGINX runs on a VM, website/link/vision runs on a different VM with an internal IP. Once we have loomio, same NGINX will point to that. DNS is on Digital Ocean.

**Comment by benhylau** [comment]
Research persistent volume for vision board.

**Comment by ASoTNetworks** [comment]
I talked to a friend that does dev stuff and says we can have the playbook and see if there a backup tar file in a directory on deploy if there is it will restore those content if not it will continue to set up the instance default state.

For services like vision board there should be a crontab that backup the content each night to a remote server.

When we have more infra in the future he say we should look at something like [MinIO](https://min.io) where it uses S3 API to store files so it doesn't have to be restored on each re-deploy.

So for the time being I will continue to provide backup space to store backup archives for services like currently we have for Passbolt.

**Comment by benhylau** [comment]
- So when someone uploads content to vision board, it goes to where? Is there a mount that the VM sees as a separate disk drive?
- What exactly goes into the nightly tar? I assume the mount right?
- If we are backing up a lot of stuff, wouldn't nightly create a lot of traffic since the drive is not diff'd?

It would help me understand if you can go into details for the vision board example.

**Comment by ASoTNetworks** [comment]
I am planning that the vision board will be deployed like it is currently and will only mount the SSHFS during backups which then I can rsync the images in the `<site-dir>/files` directory to the remote side for backup so that it will only sync the new files.

On the remote side I can then create archives locally for each day.

**Comment by benhylau** [comment]
Adding this resource for the approach to data storage we are considering: https://pve.proxmox.com/pve-docs/pve-admin-guide.html#chapter_storage

**Comment by patcon** [comment]
You're good to close this out
