### ISSUE TITLE
Develop and deploy Ansible for Passbolt

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/organizing#315]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** end-Jan  
🎯 **Success criteria:** Passbolt is now going to our server with automated backups and steps to restore from backup are clearly documented.

In our discussions, this was:
>- VM11: passbolt 💧 (July)

## To Do

- [ ] Develop ansible roles and deploy to staging
- [ ] Deploy to production
- [ ] Migrate database
- [ ] Configure automated backup
- [ ] Update existing documentations in current repos about deployment steps

**Comment by patcon** [comment]
Existing ansible roles:
| name | stars | contribs | notes
|---|---|---|---|
| [`neuroforgede/passbolt_ansible`](https://github.com/neuroforgede/passbolt_ansible) | 10 | 1 | [active, recent.](https://github.com/neuroforgede/passbolt_ansible/graphs/contributors)
| [`laxathom/ansible-role-passbolt`](https://github.com/laxathom/ansible-role-passbolt) | 2 | 2 | [stale for year](https://github.com/laxathom/ansible-role-passbolt/graphs/contributors)
| [`nfrastructr/ansible-role-docker-passbolt`](https://github.com/infrastructr/ansible-role-docker-passbolt) | 0 | 1 | [very new.](https://github.com/infrastructr/ansible-role-docker-passbolt/graphs/contributors) |

**Comment by patcon** [comment]
Unassigning myself as it was suggested I leave infra wg

**Comment by garrying** [comment]
WONTDO for now. Infra is considering Passbolt Ansible as part of an initiative.
