### ISSUE TITLE
Develop and deploy Ansible for Loomio

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/organizing#316]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** October 30, 2020
🎯 **Success criteria:** Loomio is now going to our server with automated backups and steps to restore from backup are clearly documented.

In our discussions, this was:
>- VM7: loomio 💧 (October)

## To Do

- [x] Develop ansible roles and deploy to staging (with up-to-date Loomio version)
- [x] Deploy to production
- [x] Migrate database (make sure it works with updated Loomio version)
- [x] Test new Loomio instance
- [x] Configure automated backup (VM image backup)
- [x] Update existing documentations in current repos about deployment steps

**Comment by patcon** [comment]
- digital ocean droplet shut down
- needs people to go on and test whether things working properly
- #todo find oldest thread and try to load it all -- @patcon

**Comment by patcon** [comment]
K went to a long thread and all seems to be there, so 👍 from me
