### ISSUE TITLE
Develop and deploy Ansible for BigBlueButton + Greenlight

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/organizing#317]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** end-Feb  
🎯 **Success criteria:** Have a working BBB instance deployed by ansible and understand the relationship with meet.coop.  

In our discussions, this was:
- VM1: bbb 💧💧💧💾 (July)

It is unclear how we will implement this because of our involvement in Meet.coop. It will largely depend on some near-term decisions about how Meet.coop plans to offer service. Here are some scenarios I can imagine:

1. Hypha spins up an internal instance based on a fork of the Meet.coop Ansibles, and keep that only for internal use. Whether we have a Meet.coop Greenlight container separately for clients is a separate issue.

2. Hypha does not spin up a BBB instance at all, and completely rely on Meet.coop Greenlight container for our internal use and clients.

There are of course other ways we can approach this. Ideas?

## To Do

- [ ] Decision on how this is coupled to / separate from Meet.coop
- [ ] Decision on how to handle Staging vs. Production (for resource intensive apps)
- [ ] A bunch of subtasks based on that decision...
- [ ] Decision on what to do with existing users of bbb.hypha.coop
- [ ] Communicate with existing clients
- [ ] Migrate database (if needed)
- [ ] Update existing documentation and data policy if needed

**Comment by garrying** [comment]
WONTDO. Deferring to meet.coop initiative.
