### ISSUE TITLE
Develop and deploy Ansible for Jitsi

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/organizing#318]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** 2022  
🎯 **Success criteria:** Jitsi is now going to our server and we can easily deploy new instances via Ansible.  

In our discussions, this was:
>- VM2: jitsi 💧💧💧 (August)

We should re-evaluate whether to continue hosting Jitsi before we start this.

## To Do

- [ ] Develop ansible roles and deploy to staging
- [ ] Deploy to production
- [ ] Update documentations including COVID-19 Solidarity page

**Comment by garrying** [comment]
WONTDO
