### ISSUE TITLE
Automated data backup

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/organizing#319]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** Dec 4th 
🎯 **Success criteria:** Have automated backup of our essential data from all services, and trust that backup restore is documented and can be performed reasonably easily.  

In our discussions, this was:
>- VM5: backup server 💧💾💾 (August)

One of the requirements is the backup is on a separate host. It seems we have something currently set up through OVH. We need to discuss whether this is sufficient, what is backed up and discuss any security and privacy risks.

## To Do

- [x] Discuss current solution and what else needs to be done
- [x] Discuss how this fits into ansible workflow and how new services can use it
- [x] Documentation on what is backed up, how frequently, and how to restore
- [x] Do a walkthru to make sure WG members all know how things are backed up and to restore

**Comment by ASoTNetworks** [comment]
We have 500G backup space that can be mounted over CIFS which we can use to store Proxmox VM images.

Concern is the files are not encrypted should these files be stored encrypted?

**Comment by benhylau** [comment]
Versioning. Look into GFS retention policy. Also need to update data policy if we do this.

**Comment by benhylau** [comment]
Once the backup space is provisioned, investigate whether we can encrypt the VM image before sending over so its rest-state encrypted, and is kept via some GFS type policy.

**Comment by ASoTNetworks** [comment]
I wonder if we can make a 500G LUKS image in the 500G storage space and have it mounted at boot that way anything you put in to it will be encrypted and can easily be use in Proxmox backup and restore.

As researching GFS it looks like a daily backup and keep the last 14 backups would work for us as we would most likely see an issue in the first few days and restore a broken VM.

**Comment by benhylau** [comment]
I don't know enough to comment on LUKS image. re: GFS it's quite possible we don't notice anything for a month. Is it possible to retain one backup per month for a long time, and only keep last 7 days instead?

**Comment by ASoTNetworks** [comment]
Yup we can run a script each month and copy the latest backup of when it ran to another directory to keep monthly archive and 7 days working backups.

**Comment by ASoTNetworks** [comment]
OVH backup space have been provisioned and it is configured to use CIFS and mounted using `fstab` to `/media/ovh-backup/`

To encrypt we use gocryptfs which uses a FUSE layer to encrypt which is mounted to `/mnt/pve/ovh-backup-gocryptfs/`.
Anything that is written there will be encrypted on the fly as if you are using it normally like any other directories.

We currently have Proxmox automatically backup to `/mnt/pve/ovh-backup-gocryptfs/` which stores our VM images.

**Comment by ASoTNetworks** [comment]
We are currently using OVH backups for encrypted VM image dumb. 

We have a FreeNAS VM that is a file server for VMs to mount data over NFS for persistent storage such as file level backups and dynamic data. The ZFS dataset is incrementally backed up to @ASoTNetworks infra every hour.

**Comment by benhylau** [comment]
Document party next week for @ASoTNetworks and @YurkoWasHere

**Comment by benhylau** [comment]
**Notes from @ASoTNetworks's live demo:**

1. SSH into ProxMox then connect to ProxMox UI from browser
2. Find list of VMs with VM ID (e.g. `1000` is pfSense)
3. `9000` VMs are templates
4. To restore, refer to ProxMox VM ID to find the right VM

We currently keep 5 copies through time and they roll over daily (no GFS). Now 80% of 500 GB backup space used.
