### ISSUE TITLE
Budgeting for next year

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/organizing#322]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** end-September
🎯 **Success criteria:** Create a budget for next year.  

Finance wants to start a process to come up with our FY2 budget with all members. This will involve getting each WG to propose areas where we should spend money, then go through a prioritizing process with all members on Loomio.

Proposed budgets should be tiered, and we can spend at higher tiers when revenue goals are reached:

small: absolutely what you need to live with
medium: what you like to spend modestly to accomplish your goals
big: if we have extra cash it'd be really useful to do these things

This will happen in parallel with strategic planning by bizdev.

## To Do

- [ ] ask each WG to budget for next year [ small, medium, big ] (with justification)
- [ ] finance to forecast (revenues - core operation budget), 
- [ ] solicit feedback on loomio
- [ ] propose plans, with associated revenue milestones, then vote

**Comment by benhylau** [comment]
The new re-org may re-open a variation of this. We'll revisit this when the time comes.
