### ISSUE TITLE
File corporate tax return

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/organizing#323]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** August 2020  
🎯 **Success criteria:** File our FY1 corporate tax return with accountant and deliver all necessary documents to members.  

This task includes filing of our first corporate tax return, along with all first year-end obligations.

## To Do

- [x] Send bylaws to Hema and Rodica
- [x] Initiate process to file our tax return
- Items ready for Bookkeeper **due July 21**
  - [x] all FY1 expenses in
  - [x] upload June statements including payroll
  - [x] complete GST/HST for June
- Items ready for Accountant **due July 27**
  - [x] reconciled bank statements ~~with board approval~~ (edit: no board approval needed)
  - [x] completed books
  - [x] full names, address, date of birth, phone number their position on the board and date elected (revised to **August 10**)
  - [x] meeting minutes including the AGM (revised to **August 10**)
- [x] Discuss reserve and the capital accounts with Accountant when starting year-end ~~**week of August 10**~~ (revised to **week of August 31**)
- [x] Board approval of financial statements
- [x] File tax return with CRA through accountant
- [x] Create reserve accounts with accountant
- [x] Create all documents to members with accountant, as according to our bylaws

Related:
- Formalize relationship with accountant #124 and bookkeeper
- Define scope of responsibilities #218
