### ISSUE TITLE
Report our first GST/HST remittance

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/organizing#324]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** 31 July 2020  
🎯 **Success criteria:** File HST and remit to CRA.  

We have GST/HST fiscal year-end on the 30th, so we have to file by July 31st the latest.

## To Do

- [x] ~~Calculate our GST/HST and ITC claims~~ Get GST/HST report from Rodica
- [x] ~~Ask Rodica to review if needed~~ Rodica to provide remittance figures
- [x] File with CRA
- [x] Add CRA HST remittance to our Dejardins
- [x] Submit Payment
  - [x] Create Payment
  - ~~Get another member to approve~~
  - [x] Pay
- [x] Save report to Drive

**Comment by YurkoWasHere** [comment]
- Rodica provided report and remittance values.
- we netfiled with the values provided
- Investigated method of payment
  - Dejardins has a link to government of Canada remittance system
  - Linked hypha's account for CRA HST account
  - Created payment
  - System asked for approval Assuming from another person
  - Asked in room for some one else to approve as deadline is soon


![image](https://user-images.githubusercontent.com/39072689/88568759-76850900-d007-11ea-9a5c-8a2eafc888cb.png)
https://matrix.tomesh.net/_matrix/media/r0/download/networkedserver.net/TYMuShHnFiPvQPaVIZeTbtKC
