### ISSUE TITLE
Hypha request ASN's from ARIN on behalf of TCN

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/organizing#329]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** Before Toronto Mesh deployment begins in summer 2020
🎯 **Success criteria:** Make request to ARIN or document reasons for not pursuing

During our all hands meeting on July 8th, @ASoTNetworks proposed requesting ASN's for Hypha on behalf of Toronto Mesh. Members requested more details on risks and benefits for Hypha.

## To Do

- [x] Make an [internal proposal](https://handbook.hypha.coop/guides.html#internal-proposal-template)
- [x] Review and approval from members
- [x] Create account
  - [x]  Add Contact information
  - [x]  Request a quote
- [ ] Formalize SoW by Dec 11 @dcwalk
  - [x] Draft SoW
  - [ ] Sign
- [ ] Process order

**Comment by ASoTNetworks** [comment]
ARIN responded about registering for OrgID which we need to send more information to them but since business lookup in Ontario database is behind paid services I sent them a screenshot of the HST number record and link to where they can find the record.

I hope they will accept that.

**Comment by benhylau** [comment]
Heh yea not ready yet -> https://www.ontario.ca/page/ontario-business-registry

**Comment by ASoTNetworks** [comment]
ARIN accepted our OrgID request next step is to drift a ticket for a quote on pricing.

**Comment by benhylau** [comment]
You can probably gather enough info to put together a request from https://github.com/tomeshnet/toronto-community-network/issues/20

**Comment by patcon** [comment]
tomesh apporved and has money for it now

**Comment by YurkoWasHere** [comment]
Tomesh approved 
https://github.com/tomeshnet/toronto-community-network/blob/master/operations/hardware-budgets/2020-09-18-ip-asn.md

**Comment by patcon** [comment]
Notes from all-hands:

#todo talk to Felix
#todo break up process
#todo add to Hypha card (blocked by limit)

**Comment by dcwalk** [comment]
@ASoTNetworks can this issue be updated to reflect current status? Also -- I just trying to understand where docs etc... are living for this project. Maybe we can sync on this on a call?

**Comment by ASoTNetworks** [comment]
We are at the stage of applying for the ASN but before that we need to figure out what to put into the application such as start date and peers. We will discuss this in tomesh network meeting.

**Comment by ASoTNetworks** [comment]
We submitted requests for /23 IPv4 and ASN to ARIN and waiting for reply.

**Comment by benhylau** [comment]
Ask @hyphacoop/operations-wg to review contract then @hyphacoop/finance-wg can pay

**Comment by ASoTNetworks** [comment]
We got the ASN approval from ARIN.
@hyphacoop/operations-wg please review ARIN ASN contracts [here](https://drive.google.com/drive/u/0/folders/1y6Q-TUAjAmD7FOVniJyjZJ0P9ewlBB8b)

**Comment by dcwalk** [comment]
@ASoTNetworks can you create a Statement of Work/ SOW for Hypha and Tomesh? I've set up here: 
https://docs.google.com/document/d/1Ff42OAFSi0lHehCbQX66XXblgLxhHlbT5m_WpRzL864/edit#heading=h.30j0zll

**Comment by benhylau** [comment]
Retracted offer. Abandon ship.
