### ISSUE TITLE
Run OKR process with all working groups for Q3

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/organizing#330]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** 
* Shared understanding among members
* Updated OKR spreadsheet (each WG and org-wide), with names assigned
* Updated page on handbook

...

## To Do
- [x] 1. Recap and review (Week 1)
  * Host at end of all-hands (~30 minutes)
  * Look at OKRs from previous period
  * Review current annual Strategic Plan (temporarily, the business plan) and Financial Forecast
  * Check-in on other relevant information (e.g., our mission, values, time-sensitive information) and reflect on process
  *Session outcomes:* This was completed during our AGM

- [x] 2. Brainstorm of organization and Working Group goals (Week 2)
  * Host at end of all-hands (~10 minutes)
  * Conduct individual brainstorming of goals, encourage people to add in more after call
  * Group goals into existing working groups
  *Session outcomes:* Early goals are captured in Appendix B of [business plan](https://docs.google.com/document/d/1U8C1XZcDpu1r4ciecbKEZ6vOL41nTinfqPCbZDhkAWc/edit#)

- [x] 3. Working Groups refine goals into OKRs (Week 2 WG meetings)
  * WGs take these goals and previous OKRs and discuss during their own meetings
  * WGs convert goals into "objectives" and identify "key results" and update OKR spreadsheet

- [x] 4. Present and agree on OKRs (Week 3)
  * During all hands, instead of WG updates each WG presents their OKRs and Cultivator presents org-wide OKRs
  * Use OKR spreadsheet to discuss and make minor adjustments

- [x] Updated page on handbook @uditvira
