### ISSUE TITLE
Open Collective fiscal hosting

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/organizing#336]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** start September, end October  
🎯 **Success criteria:** Develop our Open Collective into a CAD fiscal host for non-Hypha Collectives.  

We already have half of this set up through [this internal proposal](https://github.com/hyphacoop/organizing-private/blob/master/internal-proposals/2020-05-15-opencollective-fiscal-host.md) and now we can move on to Phase II:

>- w4-8 **Phase 2** Establish process/policies and identify "role" for other orgs to be listed as a collective 
    - what kind of Collectives you host, and if you're open to applications from new Collectives. 
        - What are your requirements, such as geographical location, nonprofit status, or mission area.
    - Expense Policy: https://docs.opencollective.com/help/fiscal-hosts/fiscal-host-settings
>- w8 **Phase 2** Able to host other organizations

A couple projects such as Toronto Mesh, Distributed Press, Meet.coop, CTTO projects, etc. can potentially utilize this service in the immediate to 6 month timeframe.

We also have an opportunity to apply to CWCF to subsidize professional consultation (mostly accounting) needed to implement this.

## To Do

- Schedule research call with OC to clarify
  - ~~Automated sending of invoices (per host / collective)~~
  - [x] Tax implications (donation vs. service)
  - [x] Use as a transparent grant administration tool (large deposits)
  - [x] Discuss OC 5% fee
  - ~~Discuss roadmap for inter-host transfer fees~~
- [x] Integrate our TransferWise for direct payment to bank accounts
- [x] Develop @hyphacoop/finance-wg processes with accountant and bookkeeper
  - logistics of processing many small payments (incomes and bills)
  - invoicing requirements (donations vs. service)
  - tax implications (hosting a Collective in Ontario vs. Canada vs. international)
  - legal obligations as a fiscal host
- [x] Decide on a host fee
- [x] Publish policy, see examples:
  - [OCNZ](https://docs.google.com/document/u/2/d/e/2PACX-1vRjqttNINUqiMoJ08wmF2s9r_PGDoaQxuUti-4MHwTBrLIZfRhPB_NrULkpI-ecNSGUQFH-4_GB-KIY/pub) (New Zealand, legally reviewed)
  - [Platform 6](https://platform6.coop/oc-terms-of-service) (UK)
- [x] Add CWCF acknowledgement for their financial support
- [x] Configure OC to start accepting applications
- [x] Onboard projects

**Comment by benhylau** [comment]
Start with donations-only, then discuss with OC and Platform 6 about Collective needs.

**Comment by benhylau** [comment]
@YurkoWasHere thinks we should make a separate bank account for this.

**Comment by benhylau** [comment]
Notes from call with Rodica:
- make sure contribs from OC go into separate account in QB (can share same bank account)
- do not record as income, it's a liability account
- make rules (e.g. everything from Stripe goes to donation account)
- rule should split host fee into income account and money of Collectives into a liability account
- check with Hema whether payouts to Collectives need an invoice

**Comment by benhylau** [comment]
I made a _Trust Account_ to hold funds as a liability.

![Screen Shot 2020-09-02 at 7 23 36 PM](https://user-images.githubusercontent.com/2261308/92016112-2578db00-ed52-11ea-99fa-d5bdfb1c6f19.png)

I also made a rule to get all the deposits coming from Stripe (which seems to happen on the first of each month) to automatically go into the liability account:

![Screen Shot 2020-09-02 at 7 25 03 PM](https://user-images.githubusercontent.com/2261308/92016105-23af1780-ed52-11ea-9b4f-61c2dbd37f85.png)

---

Note that **Host fees** and **donations to the Hypha Collective** are included in the liability account because splitting it is not easy (% of contribution before Stripe fees that is a variable number we don't have), we can invoice the account manually at year-end by summing up the 12-month of host fees and donations to us.

**Comment by benhylau** [comment]
We are now enrolled into two OC beta programs.

## New pricing model

>So what we're moving toward is charging 15% of host fees, plus 'platform tips' which is an optional donation to the platform that payers see in the checkout process when contributing to a Collective. In this model, there is no 5% fee or monthly flat host plan charge. So if Hypha charges a 10% host fee and your Collectives bring in $1,000 in a given month, $100 would go to Hypha and then Open Collective would send Hypha a bill for $15.

>In terms of timeframes, the plan is to charge the new fees manually to the beta testers for a few months and have it automated and switched on for everyone by early 2021. We can guarantee that we will stick to the pricing model we've agreed with you indefinitely. When we've changed pricing models in the past, we told everyone they could be grandfathered in on the old model or jump to the new model if they prefer it, so if we evolve pricing again in the future, that will be the policy.

## TransferWise

Enabled and available now as an expense payment option.

![Screen Shot 2020-10-26 at 5 37 45 PM](https://user-images.githubusercontent.com/2261308/97479428-98549b80-1928-11eb-9078-903e8a925648.png)

>When an expense submitter is putting in their payment info, a form appears formatted to match how bank stuff works in their country (we pull this straight from Transferwise), e.g. a European will be asked for their IBAN and an American will be asked for their routing and account numbers. I believe this will work how you want. However, they will still have to bill in CAD and the funds transfer will initiate with the CAD amount, then whatever the exchanged amount in their currency is will turn up in their local bank account.

**Comment by benhylau** [comment]
## Host deposits to Collective

>To add funds to a Collective's balance that are already in the host's possession—whether you keep the money in transferwise or your bank account or a cash box—go to your host dashboard > hosted Collectives > click the green $+ button on the Collective you want to credit. You will need to convert all figures to your host's currency (CAD)*.
>
>*(That means there might be slight variation due to exchange rates between the amount Open Collective says and the actual amount you're holding in another currency. You can either be OK with the variations, or convert the funds you're holding to CAD before crediting them on Open Collective.)

>No money actually moves, it's just assigning an amount already in your possession to the Collective. If you are charging a host fee, you can put it in here, and then Open Collective will take 15% of that. So if you add $14,000 with a 5% host fee, the Collective gets $13,300, the host $595, and the OC platform $105.

## Whether Host needs to charge taxes

>I can't comment on Canada's laws but I wouldn't be surprised if they were quite similar to NZ. For OCNZ (a regular limited company), its legal terms (which you can feel free to copy from if it's helpful) say that no Collective funds can be company profit, and if Collective funds are not spent by the project for any reason, we will donate them to charity. This enables us to not charge GST on unconditional donations to Collectives. But we still need to charge GST on conditional payments, i.e. when anything specific is being given in return, including event tickets. In which case, we have a feature in Open Collective where you can create contribution tiers that charge GST (e.g. selling a t-shirt, consulting services, etc). We also have that feature for EU VAT, and we can probably create it for CA VAT.

**Comment by benhylau** [comment]
## Vendors and invoices

Q: When vendors attach invoices sent to Collectives, should they be addressed to the Fiscal Host or its Collective? (Sorry if this is obvious but I couldn’t find info on this anywhere.)

A: It depends. For OCNZ, Open Source Collective, and Open Collective Foundation, they are structured so that Collectives are like just projects of that entity, and so all invoices are to the host, and all money coming in is the host's income. On the other hand, OC EU is structured so that each Collective is an independent unincorporated partnership, and invoices go to the Collectives individually, due to differences in EU laws. There is also the difference between "model A" and "model C" fiscal sponsorship in the US, which impacts this question. If your legal terms will be similar to OCNZ, then the answer is probably "to the host" but please check with a local lawyer.

Q: Are vendors considered vendors of the Fiscal Host or of the Collective? In OCNZ, do you put each vendor of all Collectives into your accounting software?

A: Similar to above, it depends. For OCNZ they are vendors of the host. However, I am not using accounting software for OCNZ because all activities will be going through the OC platform and the platform's data is enough for accountants. On the other hand, I also run a small co-op in NZ called Protozoa, and Protozoa is an OC fiscal host to hold a couple grants, but that's only a small part of Protozoa's activities, so we track everything for Protozoa in accounting software and I manually input data from the OC platform, including creating vendor contact entries and uploading invoices and receipts collected via OC for those grants.

## Host budget

Q: Is there a way to send a donation straight to a fiscal host? For example, can OCNZ itself accept contributions? (Right now Hypha makes its own Collective for that.)

A: Yes, this is what's enabled by switching on your host budget, and why I asked if you wanted your Hypha Collective merged into your host. Switching on a host budget essentially gives it all the same features of a Collective in addition to being a host. I have donations switched off for OCNZ at the moment, but you can see the option on Open Collective Foundation's host page, for example. You can customise the contribution options in your settings. If you change your mind about merging the Hypha Collective into the Hypha host, let me know.

**Comment by benhylau** [comment]
I drafted our [Fiscal Sponsorship Agreement](https://docs.google.com/document/d/1ewEOt8qh1s6Z3REUAsU7H0CxkuiaJC1iwcX86UbW9IY/edit#) based on [OCNZ's](https://docs.google.com/document/u/2/d/e/2PACX-1vRjqttNINUqiMoJ08wmF2s9r_PGDoaQxuUti-4MHwTBrLIZfRhPB_NrULkpI-ecNSGUQFH-4_GB-KIY/pub) can @hyphacoop/operations-wg review before Wed? Thanks!

**Comment by dcwalk** [comment]
Reviewed :ballot_box_with_check:

**Comment by patcon** [comment]
Reviewed ☑️

**Comment by benhylau** [comment]
@dcwalk @patcon the last step https://github.com/hyphacoop/handbook/blob/open-collective-host/fiscal-sponsorship.md

**Comment by patcon** [comment]
Looks great! Given that it's the authoritative, you sure you don't want to abandon the numbered list markdown format in favour of automatic deeplinks of markdown headers? Seems helpful to reading or speaking around it in practice. (I suppose manual and static named anchors could be better, since they won't change if numbers are added)

Re:

```
4. **Some header.** Blah blah
```

```
### 4. Some header

Blah blah
```

```
4. **Some header.** <a name="some-header">#</a> Blah blah
```

Your call though! Looks rad!
