### ISSUE TITLE
Set up commercial liability/WSIB insurance

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/organizing#351]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

Coming out of 2020-08-26 operations meeting, we need to get quotes and purchase insurance in prep of a client project

## To Do

- [x] ask members for previous experience / recommended providers
- [x] request quotes
  - [x] [the cooperators](https://www.cooperators.ca/en/insurance/business/coopguard.aspx) -Sara Sousa (will call on Friday) or [Frank Vaccaro](https://www.cooperators.ca/local/frank-vaccaro-insurance/)
  - [x] [zensurance](https://www.zensurance.com/liability-insurance) 📂 [Docs](https://drive.google.com/drive/u/0/folders/1mjPaT3IVkEBFBRv9gGVVWxexqU_lYmbN)
  - [x] [thinkinsure](https://www.thinkinsure.ca/)
- [x] review quotes
- [x] follow-up/revise quotes 
- [x] call WSIB about reclassification (no further action needed till contract is signed)
  > - Once contract confirmed 
  > - Send to wsib with reference #8279451 in subject + contact name and copy:  employeraccounts@wsib.on.ca
  > - Ruling 
  >  - letter with results of classification
  > Current: https://safetycheck.onlineservices.wsib.on.ca/safetycheck/ecm/naics/541514?lang=en
- [x] report back on day job's resolution of personal tool thefts -- @YurkoWasHere 
- [x] decide how to proceed
- [x] purchase and file insurance

**Comment by patcon** [comment]
Discussed in `2020-09-03` all-hands.

**Comment by patcon** [comment]
today's all hands: credit card or direct withdrawal maybe? -- @dcwalk

**Comment by patcon** [comment]
Added checkin with @YurkoWasHere on how his dayjob theft claim goes (personal items at work)

**Comment by dcwalk** [comment]
Purchased and filed the policy, @hyphacoop/operations-wg email is the point of contact for an annual renewal.
