### ISSUE TITLE
Desjardins Cheques

### ISSUE THREAD

**Issue by YurkoWasHere** [hyphacoop/organizing#354]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** Decide if we want cheques, if so order them

...

## To Do

- [x] Call desjardins to ask about cheques
- [x] Decide if we want cheques
- [ ] Order or Not Order them

**Comment by YurkoWasHere** [comment]
Cost of cheques

50 cheques - $103
200 cheques - $153
400 cheques - $179
600 cheques - $202
every 600 cheques after additional $103

**Comment by benhylau** [comment]
Decided to not have them with @YurkoWasHere
