### ISSUE TITLE
File notice of change for new directors/officers

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#359]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** AGM + 15 days = June 28, 2020 (we're late)  
🎯 **Success criteria:** ...  

We added 2 new officer positions and 2 new directors at the AGM on June 13. We're late filing this.

I'm using information from :lock: https://link.hypha.coop/employees

This will have no cost.

## To Do

- [x] prepare filing. :lock: [done](https://drive.google.com/file/d/1FgZ7n71gpwfHnN5d_B7p8FzqyOS7Tk4b/view?usp=sharing)
- [ ] submit annual return to CRA (block) cc @benhylau 
- [ ] submit filing via email companiesfilings@ontario.ca (as per covid protocols, see https://github.com/hyphacoop/organizing/issues/104#issuecomment-701484059)

**Comment by patcon** [comment]
Created new doc to spreadsheet to better track director/officer terms :lock:
https://docs.google.com/spreadsheets/d/1AwgVq3ghTQgg5J8s1xbcsdAfis2u4vBU9qi1nZANMOE/edit#gid=92266728

**Comment by dcwalk** [comment]
@patcon can we update this issue now that things seems resolved?

**Comment by patcon** [comment]
Yep, this was resolved via Hema (and was prob never an issue, just my missing an assumption about obligations). Closing!
