### ISSUE TITLE
Develop better sense of potential Y2 projects and member capacity

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/organizing#361]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** Have 

Based on convos in all hands and bizdev, we've been having difficulty tracking current opportunities and developing a sense of how much capacity we have as an organization to take on new projects, or if there is slack

## To Do

- [x] @dcwalk first draft of projects from existing channels where opps discussed: chat, email, gdrive, hubspot
- [x] **all** updating their availability and adding info
- [x] **biz-dev** tasks
    - @ASoTNetworks sync on how the Toronto Community Network is managed
    - @uditvira add some of the final grant docs 
    - @patcon and @uditvira (lesser extent): can you please add your project contacts to the crm tab
- [x] **biz-dev** review+feedback
- [x] @dcwalk next iteration
    - skills
    - legend
    - updating symbol in monthly columns
    - splitting up categories 
- [x] add shortlink
- potentials:
  - cleanup formatting/validation?
  - retire hubspot?
  - project hour estimations?
  - link member capacity to project hour estimation?

**Comment by dcwalk** [comment]
We've done a first pass and have a better sense of capacity + projects. I think we can reticket to lower priority issues to address the future directions:
- Operations on member capacities / skills etc... (lots to refine here)
- BizDev improve how we track current/future opps?
