### ISSUE TITLE
Scaffold out a Minute Book

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#366]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** Have a minimal concise, cross-WG deliverable that can be quickly passed to professionals who service us.  

Likely just a google drive folder with symlinks (not moving files out of WG folders). At top-level. Perhaps references place that can't yet fit in the GDrive format (on github, etc).

:lock:📁 [`Hypha - Privileged / Minute Book`](https://drive.google.com/drive/u/0/folders/1M1nFP12kzYnCeW4GPAVLZf82DIWwVp6C)

## To Do

- [ ] define scope of what goes in Minute Book and what format
  - [x] Articles of Incorporation
    - [ ] Subsequent amendments
  - [x] Bylaws
    - [ ] amendments
  - [ ] Minutes of Board Meetings (signed by secretary)
  - [ ] Resolutions of the Directors and Officers
  - [ ] all written consents of board for actions
  - [ ] Notices and Registrations filed with the government Registry (submitted forms)
  - [x] ~~registry of shareholders~~
  - [x] ~~share certificates~~
  - [x] ~~Shareholders’ Agreement~~
  - [x] ~~share transfers and any other documents relevant to transactions of the corporation~~
  - [x] register of officers. [link](https://docs.google.com/spreadsheets/d/1vxUSyZUvKN3irHCE2VtFGYjC-vGqVMNGAfdX9X9Bcrc/edit#gid=0)
  - [x] register of directors. [link](https://docs.google.com/spreadsheets/d/1vxUSyZUvKN3irHCE2VtFGYjC-vGqVMNGAfdX9X9Bcrc/edit#gid=1923145268)
  - [x] register of members. [link](https://docs.google.com/spreadsheets/d/1vxUSyZUvKN3irHCE2VtFGYjC-vGqVMNGAfdX9X9Bcrc/edit#gid=1969767365)
  - [x] any foreign qualification documents (docs to work in other jurisdictions/provinces/countries)
    - USA: W-8BEN-E
  - [ ] annual filings. [ref](https://blog.clausehound.com/overview-of-corporate-minute-books/)
  - [ ] employee contracts. [ref](https://blog.clausehound.com/overview-of-corporate-minute-books/)
- [x] create directory structure and scope

**Comment by dcwalk** [comment]
We have a parked version of this, I'm marking as wont-do for now
