### ISSUE TITLE
Create one-pager for prospective Polis service offering

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#369]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** We have a unique service related to consultation to share with prospective clients and capitalize on larger interest in Polis.  

Given the recent US election results, there will likely be increased interest and focus on repairing divides in the social fabric. Hypha should position itself as a leader in hosting and planning online-offline consultations inspired by vTaiwan and https://pol.is.

One approach involves converting existing facilitation professionals, as there is plenty of experience there that we could benefit from through collaboration.

- opportunities
  - one-pager
  - create landing page?
  - track incoming leads/clicks?
  - run some adsvertisements?

## To Do

- [ ] dive into old docs
- [ ] create Hypha one-pager
- [ ] soft outreach to past collaborators interested in polis: bianca, alexjay, ...
- blog post
  - [x] interview. https://github.com/hyphacoop/organizing-private/pull/119
  - [ ] draft
  - [ ] publish

**Comment by dcwalk** [comment]
bump @patcon can we track the first draft here? timeline is <2 weeks, correct?

**Comment by patcon** [comment]
Sure, this can be for both the business artefact and the blog post :)

**Comment by dcwalk** [comment]
I'd maybe keep those separate @patcon !! For me those are two very different types of writing. Also drafting will be discrete so tracking on two tasks seems very easy

**Comment by dcwalk** [comment]
Closing for now given as we won't develop due to changes in member status
