### ISSUE TITLE
Migrate handbook from GitBook to active fork (HonKit)

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#373]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

📅 **Due date:** None.  
🎯 **Success criteria:** Be using a tool that is being maintained.  

GitBook's open source CLI was deprecated. The most active fork is HonKit. The plugins are all cross-compatible. Should be straigthforward, mostly docs and package.json and maybe travis/actions updates.

https://github.com/honkit/honkit

## To Do

- [x] swap in package.json
- [x] Update GitHub Action workflows
  - https://github.com/hyphacoop/handbook/blob/master/.github/workflows/deploy-github-pages.yml
  - https://github.com/hyphacoop/handbook/blob/master/.github/workflows/test-pull-request.yml
- [x] Update README https://github.com/hyphacoop/handbook/blob/master/README.md

**Comment by benhylau** [comment]
@uditvira @dcwalk shall we close?

**Comment by dcwalk** [comment]
No we should do this. There are a few things that have been unmaintained for a long time with gitbook. I would just like some help to complete this
