### ISSUE TITLE
Plan lite-touch holiday party

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/organizing#378]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** Q4 2020
🎯 **Success criteria:** Have a holiday party. 

Discussed at all hands and 2020-11-26 Opa meeting:

> Sun, Dec 13 4-6:30pm ET [UTC-05]
>  - 2.5h; 1h "drop in" and then among us playtime
>  - Invite collaborators + clients.
>    - #todo cowork on this next Ops call
>        - create a yulelog background screen.
>        - multi-breakouts
>        - create door graphics for each "room"
>        - cheesy clipart invite for "Holidy Drop-In Party"
>       - Miro board?
>        - bbb = bad for this. Jitsi instead.
> - inspo: https://medium.com/swlh/how-to-run-a-zoom-cocktail-party-and-have-better-classes-conferences-and-meetings-too-dc2c5b58f8be
> - Few of us show up at Meet.coop <-- Dec 4 party

## To Do

- [x] cowork on this next Ops call
- [x] draft invite
- [x] set up space(s)
- [x] create email list
- [x] send invite (dc: suggest just bcc) by **Fri Dec 4)
   - [x] Org email @patcon 
   - [x] Individual email-outs (all, incl. @dcwalk )
- [x] refine space

**Comment by dcwalk** [comment]
Miro board + discord: https://miro.com/app/board/o9J_lcu-U58=/

**Comment by patcon** [comment]
Invite list: :lock: https://docs.google.com/spreadsheets/d/1vj5g2S7vQhLHNYt5XD9qfpb_D60aGlcEYubwlodqXUY/edit#gid=0

Planning doc: https://docs.google.com/document/d/1XcdJ0qivHc8gmwxx7CbREq_0VstvxCROIXT44GkcPC4/edit#heading=h.ld18hdmf7bei

**Comment by dcwalk** [comment]
We've planned this! invites sent! Just gotta show up! I'm closing for some year-end clean up vibes
