### ISSUE TITLE
Close Hypha office for holidays

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/organizing#381]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** Dec 18, 2020
🎯 **Success criteria:** ...  

Make sure we're ready to close office for 2 weeks

## To Do

- [x] Confirm dates, inform members, inform of payroll/invoicing deadlines:
  - Dec 19 - Jan 10, email/phone monitoring Jan 4 onwards (@benhylau)
  - ALL clockify hours in Dec 18 EOD
  - Project leads invoicing and payroll in sheet by Dec 18 EOD
- [x] Set up responder to hello@ (@hyphacoop/infrastructure-wg did)
- [x] encourage members to add email responder? (provide draft text)
- [x] Record temporary VM greeting

**Comment by dcwalk** [comment]
Email templates:

Happy holidays! 

I'm currently offline until January 10, 2021. 

Hypha is officially closed for the holidays from December 19 to January 10, 2021. If you require immediate assistance after January 4, 2021 on please email hello@hypha.coop.

Wishing you a safe and restful holiday season,
[Your Name]

===
Mine: 

Happy holidays! 

I'm currently offline celebrating the demise of 2020 until Monday January 11 and Hypha is officially closed from December 19, 2020 to January 10, 2021. 

I'm already looking forward to my inbox and responding promptly when we re-open. For time-sensitive issues, I'll respond in the new year as I am able. If you require immediate assistance after January 4, 2021 on please also email hello@hypha.coop.

Wishing you and yours a safe and restful holiday season,
[Your Name]
