### ISSUE TITLE
Launch a blog for Hypha: Dripline

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/organizing#382]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** Q1 2021 
🎯 **Success criteria:** Have a blog/place for publishing our writing at Hypha.

We're launching a blog and have a goal for publishing a **monthly** going forward (with a near term goal of 3 posts by end of Q1 2021). This issue will track todos, but coordination and co-writing will happen in a [google doc](https://docs.google.com/document/d/1Otvfq0VIJfqevsq5SisB7-uovEDL18CXLwXrzqggl7k/edit) :lock: 

## To Do

- [x] have initial brainstorm, identify audience, draft outline template
- [x] set up doc / template / gh issue 
- [x] co-writing sesh 1
- [x] discussion on website and look&feel reqs
- [ ] setup website:
  - [x] Ben: Setup up website + CI
      - Upgrade to website
      - Add travis files
  - [ ] Garry: Set up blog
      - [x] Add writing page
      - Regig homepage
  - [x] Udit: Change to use co-op everywhere! “We are a dash always co-op”
  - [x] DC to ask Elon: dripline@hypha.coop
  - [x] Dc: treatment/prep of incorporation flow image
  - [ ] Dc: Put in images to image bank
  - [x] Udit: Add a framing explainer at the top (2 sentences)
  - [x] Patcon: add first blog post: https://github.com/hyphacoop/hypha.coop/pull/21
  - [x] Dc+pc: Write footer with how to find us on dweb?
      - 1st draft: “This site is published using Distributed Press, you can use it to publish on the p2p and distributed web too.”
      - 2nd draft: "This site is published using [Distributed Press](#), you can [use it to publish](#) on the p2p and distributed web too."
      - final: "This site is published using [Distributed Press](#), an initiative we host. You can [use it to publish](#) on the p2p and distributed web too."
  - [ ] Garry: Add ~~RSS feed~~, [✅ Atom XML](https://staging.hypha.coop/feed.xml), ~~JSON~~
  - [x] Ben: ~~Pass static site to ben to publish through distributed press~~ `automated in ci`
- [x] publish [to staging](https://staging.hypha.coop/dripline/how-we-co-operate/)
- [x] publish to prod ~~**Feb 8**~~
- [ ] social media posts: twitter, ~~linkedin~~
- [x] #noblock ~~resolve jekyll bug with absolute_url breaking locally, but needed for atom render~~ `reticket`
- [ ] #noblock ~~add custom `includes` for improved images and divs (e.g., float left/right, captions)~~ `reticket`
- [x] #noblock ~~dweb reference in footer layout~~ `reticket`
- [x] #noblock ~~dweb redirects via shortlinks? can't store in file itself~~ `reticket`

**Comment by patcon** [comment]
> Dc: Put in images to image bank

@dcwalk is this in reference to the 2 images in the post itself, or something else that's already done?

**Comment by patcon** [comment]
> Add ~~RSS feed~~, [✅ Atom XML](https://staging.hypha.coop/feed.xml), ~~JSON~~

@dcwalk i'm thinking just an atom feed is good enough, yes? or should I reticket something from this?

**Comment by patcon** [comment]
> social media posts: twitter, linkedin

Recalling past convos, I'm assuming that sharing this on Linkedin would be taking ourselves too seriously, yes? I recall we wanted to be more experimental if we started posting there

**Comment by dcwalk** [comment]
> > Add ~RSS feed~, [white_check_mark Atom XML](https://staging.hypha.coop/feed.xml), ~JSON~
> 
> @dcwalk i'm thinking just an atom feed is good enough, yes? or should I reticket something from this?

Yes can we reticket RSS / JSON?

**Comment by dcwalk** [comment]
> > social media posts: twitter, linkedin
> 
> Recalling past convos, I'm assuming that sharing this on Linkedin would be taking ourselves too seriously, yes? I recall we wanted to be more experimental if we started posting there

Yes we talked about shitposting on linkedin main, so I think we can leave for now

**Comment by dcwalk** [comment]
@patcon reacting to this:
> #noblock dweb reference in footer layout reticket

The text i drafted is in the google doc, is there some reason this can't be in the first past?

**Comment by patcon** [comment]
Deploy to prod happening here: https://github.com/hyphacoop/hypha.coop/pull/18

Will need confirmation from:
- @benhylau about deploy working properly.
- @dcwalk and @uditvira on general look.

**Comment by patcon** [comment]
Tweet! https://twitter.com/HyphaCoop/status/1365006926992539650
