### ISSUE TITLE
FreeNas shared data store for all services

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/organizing#383]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #319  
🗣 **Loomio:** N/A  
📅 **Due date:** Q3 2021  
🎯 **Success criteria:** Implement shared data store based on FreeNas.  

Right now we have two backup systems:
1. Each VM image is backed up to OVH backup space (daily snapshots kept for 5 days)
2. Some dynamic content (e.g. vision board) is in a FreeNas VM that gets backed up to OVH space + hourly sync to @ASoTNetworks 

This is okay for now as everything has a backup somewhere. However, couple issues remain:

- Dynamic data in databases like Loomio's rely on VM-level backup to restore, we'd rather abstract out storage layer across all services (i.e. have Loomio connect to database via network mount to FreeNas)
- Ideally we want to only back up the FreeNas VM to OVH backup space and treat all Ansibles as ephemeral
- Once we reduce VM backup to a single VM, we can better utilize the 500 GB of backup space and use GFS (so we retain older backups)
- We can do lighter-weight syncs to @ASoTNetworks infra off OVH

Abstracting out storage layer provides additional benefits as we no longer have to think about backup plan for each service that has dynamic content individually. Instead, the problem becomes streamlined as "what is the storage layer and we'll create it in the FreeNas VM". This also allows us to switch data store solutions easily in the future.

For example, whether it's the vision board assets, Passbolt database, Loomio database, Greenlight database... there is one consistent way to bridge "service" with "storage".

## To Do

- [ ] Discuss architecture and the interfaces between VMs under this shared data store model
- [ ] Consider performance implications
- [ ] Discuss backup plan related to GFS and different backup volumes
- [ ] Make migration plan
- [ ] Implementation
- [ ] Update docs

**Comment by garrying** [comment]
WONTDO. Infra might create an initiative to make backups more consistent.
