### ISSUE TITLE
Investigate whiteboarding tool account

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#384]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** n/a 
📅 **Due date:** N/A  
🎯 **Success criteria:** We have a collab tool that suits the purpose of a whiteboard.  

@patcon was starting to use Miro for client work, but on a trial account. Trial accounts have the major drawback that they don't allow anonymous editors, so clients can comment/edit boards.

Miro is the tool I have most experience and positive feelings about.

- @uditvira was **not** a bit fan in the past. How do you feel now?
- We used Miro to host the xmas party, so everyone should have some sense of it now.

## To Do

- [x] Migrate boards out of prior account
- [x] Seek advice on needs of others in Hypha
- [x] Identify & price candidate services
  - Miro: USD$10.50/mo for [single shared user account, for "working with clients"](https://user-images.githubusercontent.com/305339/102407387-09740f00-3fba-11eb-8671-d93560894736.png) (billed monthly, assuming discount below) ([Pricing page](https://miro.com/pricing/))
  - ...
- [x] Submit request for [30% NPO discount](https://miro.com/contact/npo/)
  - [x]  Relay response into this ticket. **Approved.** Promo code forwarded to operations@
- [x] sign up for Miro. ($20/mo Team plan, for 2 users)
  - [x] email support to apply 30% discount :/
  - [x] report back to finance@ on new rate

EDIT: Oops. Had @uditvira's previous opinion reversed for lack of a key word. Fixed.

**Comment by patcon** [comment]
Permission given in 202/12/16 standup to pay for plan with Hypha credit card at discretion of operations.

**Comment by patcon** [comment]
Heard back from Miro, and was approved: have promo code for 30% off all future plans indefinitely. Forwarded to operations@

**Comment by dcwalk** [comment]
@patcon can this be closed?

**Comment by patcon** [comment]
Yep! Aside: My practice was 3 mo of monthly billing (to re-evaluate whether we're using it and it's suiting us), and set calendar reminder to change to yearly after that. @benhylau was +1 on making things yearly for accounting.

My sense is there's no need to document this, but just offering shared context :)

**Comment by patcon** [comment]
Actually, @benhylau should I add Miro to somewhere in https://link.hypha.coop/projection ?

**Comment by dcwalk** [comment]
Can we close this :pray: and leave to finance to handle when update projections? That is going to be an ask anyway for Strategic Planning.

**Comment by patcon** [comment]
Sure, closing. Though I feel clean and clear pass-offs are part of closing

**Comment by dcwalk** [comment]
Fair enough on clean and clear passoffs. However this issue wasn't rescoped to include the degree of passoff sought.
