### ISSUE TITLE
Prepare for first quarterly planning call

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/organizing#431]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** April 20, 2021
🎯 **Success criteria:** We host a successful quarterly planning call. 

A tracking issue to get us to the first quarterly planning call in April in 5 weeks

## To Do

- [x] email WGs 4W
- [x] develop and adopt new meeting format 4W
- [x] draft agenda 3W
- [x] meeting package prepared 3W (agenda + loomio + playbook / transition plan)
- [x] have initiative playbook 2W
- [x] each WG prepares materials for distribution (~4 hours)
   - [x] infrastructure
      - updated Service Inventory: https://hackmd.io/@patcon/HyH0W9bAE (answer to questions: what are current tools we are using? how active are tools?) IN ADVANCE
      - provide recommendation on course of action for tools no longer using
      - provide status update on migration (are all services migrated into hypha?  which core business activities aren't on hypha infra? (e.g., email, calendar)
      - analyze tools we can use for voting at AGM and async on proposals (loomio is available, github discussions? gitlab (not proposing tools?)
   - [x] finance
      - updated books (early April) IN ADVANCE
      - provide financial forecast/financial statements YTD, in some way should include: 
         - costs broken down by WG
         - line-item detail on recurring costs
      - provide all requests/type of requests for finances you have received
      - provide [draft] budget template/proposed budget IN ADVANCE
   - [x] governance
      - Wrap up from AGM completed (handbook documenting) IN ADVANCE
      - Articles amended IN ADVANCE
      - revisit the Y2 strategy/AGM governance report
   - [x] operations
      - provide plan for initiative transition IN ADVANCE
      - Wrap up health and safety IN ADVANCE
      - drafted initiative playbook 
      - updated Meetings playbook for hosting meetings (AGM, new formats)
      - updated Handbook to current status
   - [x] business planning
      - updated to strategic positioning (now ecosystem map) IN ADVANCE
      - provide opportunities roadmap for next quarter (~3 months)
- [x] add next ~3months budget requests to form (1 meeting)
   - [x] infrastructure
   - [x] business planning
   - [x] governance
   - [x] operations
   - [x] finance
- [x] brainstorm proposed initiatives <with first graph description> add to form (1 SAME meeting)
   - [x] infrastructure
   - [x] business planning
   - [x] governance
   - [x] cmc (incls. finance and operations)
- [x] meeting package distributed 1 week before

**Comment by benhylau** [comment]
@YurkoWasHere I have added the Finance stuff to [here](https://hackmd.io/YkUJxCkDRJ-7qTFqLmGtyg?view#Discussion-Financial-forecast-and-budgeting). Please review and ping me or adjust as needed.

**Comment by benhylau** [comment]
Added https://link.hypha.coop/budget for budget planning

**Comment by dcwalk** [comment]
We had this meeting, wrap up here: https://github.com/hyphacoop/organizing/issues/451
