### ISSUE TITLE
Publish MARCH Dripline post: Listening at scale with Polis

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/organizing#441]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** Post is published on Dripline

...

## Todo

- [x] brainstorm
- [x] interview. [notes](https://meetings.hypha.coop/2021-02-11-business-planning.html)
- [x] first draft. [gdoc](https://docs.google.com/document/d/1Otvfq0VIJfqevsq5SisB7-uovEDL18CXLwXrzqggl7k/edit#)
- [x] review.
  - [x] dc added some content, revised + left comments 
  - [x] uv  
- [x] edits
  - [x] dc
  - [x] uv
- [x] final version -- pc
- [x] create dripline pull request -- dc
- [x] make GIFs -- pc
- [x] publish - ~~April 20ish~~ Apr 30
- [x] tweet & share -- pc

**Comment by patcon** [comment]
🎉  https://hypha.coop/dripline/listening-at-scale-with-polis/

Waiting for this to show up, maybe by morning?
https://ipfs.distributed.press/ipns/hypha.coop/dripline/listening-at-scale-with-polis/

**Comment by dcwalk** [comment]
I tweeted, so closing this out
