### ISSUE TITLE
Get ready for CSJ / Summer Internship

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/organizing#450]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** have a person placed for paid summer internship

We got the grant! Now we need to get someone in the position!

## To Do

- [x] review acceptance letter and identify next steps
- [x] return signed agreement
- [x] complete setup
   - [x] Register for Grants and Contributions Online Services 
   - [x] Confirm your Authority to Act as the Primary Officer _"An authorization code has been mailed to the business owner or chief executive officer at the address on file."_
   - [x] Complete ESDC NAS5050 Grants and Contributions Direct Deposit Request Form (submit via GSOS)
   - ~~Confirm sent agreement to the correct place...?~~ handled below
- [x] advertise
  - [x] create our posting [drafted ✍️ ](https://docs.google.com/document/d/1lMjBf8r3BPb_aY-8QdRNnpzOzlNbdxlFFe5FJRAbICQ/edit#heading=h.pcil4k619um4)
  - [x] ensure on canada job bank: https://www.jobbank.gc.ca/jobsearch/jobpostingcsj/34288529?source=searchresults
  - [x] tweet, circulate in our networks 
- [x] hire position
  - [x] unlist on linkedin, yes jobboard
  - [x] notify all candidates (bcc)   
  - [x] prepare employee acknowledgement
- [x] post hiring tasks
    - [x] complete form EMP5397 **within 7 days** the [EMPLOYER AND EMPLOYEE DECLARATION](https://srv217.services.gc.ca/ihst4/Questionnaire.aspx?sid=8efa531b-23f5-49d1-99c1-092d890611a2&lc=eng&GocTemplateCulture=en-CA&iffsappid=TISMB-DGSTP&iffssid=b221d1a3-6e9c-4073-9cca-7000332eb994#) 🔗  https://github.com/hyphacoop/organizing/issues/133
    - [x] employee must complete [ESDC EMP 5616](https://www.canada.ca/content/dam/esdc-edsc/documents/services/funding/gcos/csj_consent.pdf) **within 7 days** and we must store
    - [x] give youth the [required info/materials](https://drive.google.com/drive/folders/1NpNxiXD2WZHj7Dmho6dNXV9yVjCaWwi9) 🔒 
    - [x] ask youth to complete a [Canada Summer Jobs Participant questionnaire](https://srv217.services.gc.ca/ihst4/Questionnaire.aspx?sid=ca5dd962-408d-4e19-b69a-28a5c5010000&lc=eng&GocTemplateCulture=en-CA&iffsappid=TISMB-DGSTP&iffssid=15d4644f-5f5e-41f4-a5f8-5e057be899de) 🔗 
- [x] reticket for wrap-up:
     - we must complete a [Canada Summer Jobs Employer Questionnaire](https://srv217.services.gc.ca/ihst4/Questionnaire.aspx?sid=7febf1b4-9d90-4d6d-8a8a-39742643f7ec&lc=eng&GocTemplateCulture=en-CA&iffsappid=TISMB-DGSTP&iffssid=aae2c25c-6f3a-4c08-832f-168d383f4799) 🔗 
   - Complete [PAYMENT CLAIM AND ACTIVITY REPORT](https://srv217.services.gc.ca/ihst4/Questionnaire.aspx?sid=87d02adc-4d57-45ad-967e-02647c58859c&lc=eng&GocTemplateCulture=en-CA&iffsappid=TISMB-DGSTP&iffssid=7ffdfbb3-809c-424f-86df-49a684a0ce8b)  (submit via GSOS)

**Comment by uditvira** [comment]
@dcwalk thanks for this. Reviewed draft and left suggestions. Most are minor.

**Comment by dcwalk** [comment]
PDF: https://hypha.coop/assets/JobDescription_PTMarketingCoordinator_2021-05-07.pdf
Tweet: https://twitter.com/HyphaCoop/status/1392954153580867586?s=20

**Comment by dcwalk** [comment]
Postings:
- LinkedIn (urg): https://www.linkedin.com/hiring/jobs/2536716017/applicants/
- Job Bank: https://www.jobbank.gc.ca/jobsearch/jobpostingcsj/34288529?source=searchresults
- YES: being reviewed
- CWCF: being posted (maybe insta?)

**Comment by dcwalk** [comment]
https://www.yes.on.ca/job/part-time-marketing-coordinator/

**Comment by dcwalk** [comment]
Done, closing!
