### ISSUE TITLE
Complete wrap up from Q2 planning call

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/organizing#451]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** Tasks from quarterly call are finished 

A tracking issue to get us to the wrap up from the quarterly planning call held April 21. Should be done by May 5 All hands.

## To Do

- [x] clean up meeting notes -> #452 
- [x] send email with next steps for defining initiatives from plan
- [x] update financial modelling for discussion at next all hands
- [x] update initiative playbook, role
- [x] update CMC miro/generate github tasks

**Comment by dcwalk** [comment]
wrapped!
