### ISSUE TITLE
Dissolve WGs into Inititiatives

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/organizing#453]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** May 19, 2021!
🎯 **Success criteria:** We have no more WGs!  

- Worked from transition modelling:
    - https://docs.google.com/spreadsheets/d/1HWa3XPNsY-k6MtfAlNnUWy7kPCid65OUPooWMY6qpyY/edit?usp=drivesdk
    - **Consensed** on guidelines with 100 hours per month cap for Q2 (April-June)

Discussed and **consensed** on proposed pathway:
- Start July 1 @ 22.50 (living wage in Ontario)
    - paying everyone
    - introduce member requirements (MIN/MAX hours, track hours, good mem.)
- Cap hours @ 15/member mthly, cap internal hours 100 mthly Q3
- Increase clip to 35% internal (keep flat), grandfather exceptions
    - This increases wage floor: $35/hour billed work (something like $30/hour covers internal hours?)
- Enforce clip for contractors 40% (talk through exceptions)
- PARKING for now: Do member loan (!!) for $2000 (split quarterly) for roughly paying 1/3 total hours (annual: 200hrs @ $32/hr to pay living wage = $6400)
FY3 Targets: 
    - bill $250k without subcontracts to cover operating costs+internal work
    - contain/keep stable internal hours / mth at start (gains go to wage)

## To Do

- [x] dc / ghost in the machine: 
  - [x] complete initiative(s) template using playbook 
  - [x] once complete, finalize "launch" in db / miro   
- [x] business planning
  - [x] winddown WG and kickoff initiative(s) 
- [x] infrastructure
  - [x] winddown WG and kickoff initiative(s) 
- [x] governance
  - [x] winddown WG and kickoff initiative(s) 
- [x] backoffice
  - [x] finance
  - [x] operations
    - [x] finalize "launch" in db / miro 
- [x] discuss at all hands
- [ ] update repos/shortlinks: #465 https://github.com/hyphacoop/handbook/pull/128 https://github.com/hyphacoop/handbook/pull/127

**Comment by dcwalk** [comment]
Email/summary sent:

Thanks all for the meeting last Wednesday!

Takeaways:

1. We reviewed finances, member capacity, and WGs=>initiatives on the go

We made the following collective agreements: 
- We will use clockify to track all hours to month-level granularity (higher granularity helpful!)
  - yj+el will track meet.coop hours here going forward and add a single entry per month for the last qtr
  - consensed to finish deprecation of jitsi this qtr (and update COVID-19 resource to note that)
  - Consensed on transition pathway and 100 hours/month guidelines for this qtr

2. We developed a list of initiatives and time budget for the remainder of Q2 (June 30), we will spend more time discussing and refining at our next strategy meeting at the AGM (July or Aug)

3. We collectively identified the key goal for this quarter: 

(7) Hypha should develop our workflow and processes to support a culture of accountability with defined collaboration and decision-making techniques and tools

This seems especially pertinent to all the discussions we had about: clockify use, establishing initiatives, thinking about hours toward internal work. We can carry this forward into establishing the initiatives in the next few weeks.
 
Others in the top 3: (6) Deepen our relationships and partnerships, (4) refine our positioning with respect to our collaborators

4. We estimated and agreed on a 15/month hourly limit per member (or 100/month total) for internal initiatives 
https://docs.google.com/spreadsheets/d/1LyElXvLj7ASclSPQqcgOnuEWqBWBStilEfOhIosZzhA/edit#gid=858595530

5. We went over time and did not discuss budget requests, those are all captured in the notes and will be brought to our next All hands on May 5, 2021.

===

NEXT STEPS: [WIP -- give me till this Friday pls!]

- Move proposed initiatives into set up following the initiative playbook 
- Dissolve/wrap up existing WG meeting structures (or determine what carries over to the new initiative one) over the **next 3 weeks**
- Use this github issue as a checklist to track progress: https://github.com/hyphacoop/organizing/issues/453

DEADLINE to switch to initiative meetings and structure: 3 weeks == May 19!

- Dawn

**Comment by dcwalk** [comment]
Done some reviews on this, think I have done it all. Closing!
