### ISSUE TITLE
Wrap up CSJ / Summer Internship

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/organizing#464]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #450  
🗣 **Loomio:** N/A  
📅 **Due date:** September 15, 2021  
🎯 **Success criteria:**  Have wrapped up summer marketing coord position.

For the end of the summer :cry: 

## To Do

- [x] have exit interview and offboarding call
- [x] Follow [offboarding checklist](https://handbook.hypha.coop/templates/checklist-offboarding.md)
  - [x] Signal 
  - [x] Matrix all private channels
  - [x] Email members@ and WG/initiative forwarders
  - [x] Clockify
  - [x] Passbolt groups 
  - [x] GitHub organization (per-repo access as needed?)
  - [x] Google Drive (messy)
  - [x] Google Calendars
- [x] Complete CSJ obligations
     - we must complete a [Canada Summer Jobs Employer Questionnaire](https://srv217.services.gc.ca/ihst4/Questionnaire.aspx?sid=7febf1b4-9d90-4d6d-8a8a-39742643f7ec&lc=eng&GocTemplateCulture=en-CA&iffsappid=TISMB-DGSTP&iffssid=aae2c25c-6f3a-4c08-832f-168d383f4799) 🔗 
   - Complete [PAYMENT CLAIM AND ACTIVITY REPORT](https://srv217.services.gc.ca/ihst4/Questionnaire.aspx?sid=87d02adc-4d57-45ad-967e-02647c58859c&lc=eng&GocTemplateCulture=en-CA&iffsappid=TISMB-DGSTP&iffssid=7ffdfbb3-809c-424f-86df-49a684a0ce8b)  (submit via GSOS)
- [ ] Issue ROE (Sept 15) -- @benhylau see https://github.com/hyphacoop/organizing-private/issues/146 for context

**Comment by benhylau** [comment]
I updated Elani's email address in Wagepoint and issued an ROE, terminated the employee relationship but she'll still have access.

Wagepoint just updated the ROE workflow so now ROE issuance is separate from employee termination. It also has much clearer UI to preview the ROE and submit to Service Canada. So this actually appears in the UI, while the two we did before hasn't shown up.
