### ISSUE TITLE
Close office for summer holiday

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/organizing#473]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** Aug 10
🎯 **Success criteria:** ...  

Make sure we're ready to close office for 2 weeks

## To Do

- [x] Confirm dates, inform members, inform of payroll/invoicing deadlines:
  - Aug 16-29 
  - Hours and invoices completed Aug 30 and 31.
- [x] Update calendar 
- [x] Set up responder to hello@ (ping @ASoTNetworks )
- [x] encourage members to add email responder if they want (provide draft text)
- ~Record temporary VM greeting~

**Comment by dcwalk** [comment]
### Email templates

Subject: Hypha offices closed RE: ${subject}

Org:

Hypha is officially closed from August 16-29, 2021 and members are offline for a much needed break. We look forward to responding when we re-open in September. 

Best,
Hypha

---

Individual:

Subject: On holiday RE: ${subject}

I'm currently offline and only periodically checking my email as Hypha is officially closed from August 16-29, 2021. 

[Outro],
[Your Name]

---

Mine: 

Subject: On holiday RE: ${subject}

I'm currently offline and only periodically checking my email as Hypha is officially closed from August 16-29, 2021. 

For time-sensitive issues, I'll respond over the next two weeks as I am able to emails send to dc@ and hello@hypha.coop.

All best,
Dawn

**Comment by ASoTNetworks** [comment]
I set up the auto responder to be enabled on the Aug 16th and disable on the 30th.

**Comment by dcwalk** [comment]
Thanks!

**Comment by dcwalk** [comment]
This was done :)
