### ISSUE TITLE
Close office for Winter Holiday

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/organizing#484]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

Get us ready to close for our break

## To Do

- [x]  Confirm dates, inform members, inform of payroll/invoicing deadlines:
      - Dec 18 - Jan 2
      - ALL clockify hours in Dec 20 EOD
      - Project leads invoicing and payroll in sheet by Dec 18 EOD
- [x] Set up responder to hello@
- [x] encourage members to add email responder and leads to inform clients of closure (provide draft text)
- [x] Record temporary VM greeting

**Comment by dcwalk** [comment]
Last year templates: https://github.com/hyphacoop/organizing/issues/381

**Comment by dcwalk** [comment]
## Email templates

### Org

Subject: Hypha offices closed until January 3 RE: ${subject}

Happy holidays!

Hypha is officially closed for the holidays from December 18, 2021 to January 2, 2022 and members are offline. We look forward to responding when when we re-open in the new year. If you require immediate assistance after January 3, 2021, please email hello@hypha.coop.

Wishing you a safe and relaxing holiday season,
Hypha

### Individual

Subject: On holiday RE: ${subject}

Happy holidays! 

I'm currently offline until January 3, 2022. 

Hypha is officially closed for the holidays from December 18, 2021 to January 2, 2022. If you require immediate assistance after January 3, 2022, please email hello@hypha.coop.

[Outro],
[Your Name]

---

Mine: 

Subject: On holiday RE: ${subject}

Happy holidays! 

I'm currently offline celebrating the end of 2021 until Monday January 3 and Hypha is officially closed from December 18, 2021 to January 2, 2022. 

On a personal note, I'll be taking less available in the coming months as I wrap up other projects. For time-sensitive issues or emails requiring a response after the break, please also email hello@hypha.coop. For all others I'll respond in the new year as I am able.

Wishing you and yours a restful holidays,
Dawn

**Comment by dcwalk** [comment]
If you would like language to provide to clients, here is some (h/t @benhylau):

No avail:
Hypha’s office is closed from December 18, 2021 to January 2, 2022 and members are offline.

Some avail:
Hypha’s office is closed from December 18, 2021 to January 2, 2022. We should cancel standing calls or regular syncs until the new year. However as a client lead I can be available for urgent client matters over the break, excepting a few blackout dates: Dec 24-26, Dec 31-Jan 2.

**Comment by dcwalk** [comment]
For contractors:

Hello [X}, 

I just wanted to provide an update on scheduling over the holidays:

- Hypha is officially closed for the holidays from December 18, 2021 to January 2, 2022 and members are offline. This means we do not have any internal initiative calls or standing weekly events for the duration. There is no expectation that you are monitoring chat nor work done over that period (unless you discuss and work that with the initiative lead)
- We will not process any invoices received on Friday December 17 forward until after January 3 when we re-open (I do not foresee this as an issue given our current cycles)
- If there is any emergency or something comes up the initiative lead is your best point of contact.

Best,
Dawn
