### ISSUE TITLE
Reading/Writing Practice + Matrix Archive Bot

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/organizing#485]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** Having a document and meeting with Hypha members to discuss reading/writing practice

[Workplan](https://docs.google.com/document/d/1GcqpE8XaRheQ2KRulRzx8mo0KhB_S7W41Z0IDgpzrWw/edit#)

## To Do
R/W General
- [x] Notes are organized and ready for workshopping
- [x] Complete 1:1 meetings
- [x] Book brainstorm with team
- [x] Create Miro board for brainstorm
- [x] develop chatbot or similar to pull content out of Matrix & into another tool to be organized 
- [x] document above process and share with everyone so they use it
- [x] create Miro board to capture everyone's areas of expertise

Dripline
- [x] Create editorial calendar for Dripline
- [x] Develop content process for Dripline
- [x] Create Dripline post template 
- [x] Dripline post PR process walk-through (scheduled for March 17)
- [ ] Post process to Handbook

**Comment by writerly03** [comment]
Assigned @YurkoWasHere for the Matrix bot piece only

**Comment by writerly03** [comment]
History: In our team brainstorm ([see Miro Board here](https://miro.com/welcomeonboard/ZzhFdXVIRUYyYnkzcXFRMU8wekpPdW5tZ0t4SUEyQVF2WTBOaHRLVEdPV3dhZ3pLWDNWcnBxTGhrMUVjZVFobnwzNDU4NzY0NTE0MjU1ODg5NjE2?invite_link_id=65566994667)), we talked about how Matrix functions as a repository of co-op knowledge, but that this isn't easily accessible. One option for making this material more available for future projects is to build a chat bot that could pull out tagged conversations (or snippets of conversations) and store them somewhere else. No storage options were confirmed but Are.na was mentioned. 

The task: build a chat bot that can pull out tagged conversations and store them somewhere. The somewhere has to have some ability to sort or search, so that saved conversations can be catalogued in a usable way. Once this is built, we'll test the process to see how it works, and whether it's achieving the goal of building a usable knowledge base for Hypha.

@benhylau please add in other technical specifications.

**Comment by benhylau** [comment]
Added `!save` func to proof-of-concept matrix bot:

```
from datetime import datetime
from maubot import Plugin, MessageEvent
from maubot.handlers import command
from typing import Tuple

import base64
import json
import requests

class hyphabot(Plugin):
  @command.new(name="hello-world")
  async def hello_world(self, evt: MessageEvent) -> None:
    await evt.reply("Hi There. I'm a new bot you gatta program me!")

  @command.passive("!save")
  async def save(self, evt: MessageEvent, match: Tuple[str]) -> None:
    msg = evt.room_id + "\n" + evt.content.body

    # Encode message to base64
    b64Bytes = base64.b64encode(msg.encode("utf-8"))
    b64String = str(b64Bytes, "utf-8")

    # Publish to GitHub repo
    owner = "benhylau"
    repo = "bot-testing-facility"
    path = datetime.now().strftime('%Y-%m-%d-%H-%M-%S') + ".txt"
    file_content = {
      "message": "Add message from chat bot",
      "content": b64String,
    }
    r = requests.put(f"https://api.github.com/repos/{owner}/{repo}/contents/{path}",
      headers={'Authorization': 'token [REDACTED]'},
      data=json.dumps(file_content))

    await evt.reply("I saved your message to https://github.com/benhylau/bot-testing-facility/")
```

Archived msgs in here: https://github.com/benhylau/bot-testing-facility

**Comment by YurkoWasHere** [comment]
> which rooms to give roobot access to? 
Bot works by invite. You invite the bot, it joins the room so its "self serve"

> privacy: access to DMs in particular seem problematic
Currently the bot does not do encrypted chats, I think it can with additional modules installed.  But im not sure exactly what the question here is.

> where things get stored: if we're using something outside of our Google Workspace or an internal Hypha platform, need to consider security implications for moving data around

Currently there are two prototypes, Append HackMD (that can be modified by users) and GitHub which is a more permanent location

> server space: will this take up a lot of resources if we use it for a long period of time?

Bot itself does not store data. This should not be an issue.

**Comment by writerly03** [comment]
> To be fair i did not dive to deep into the "google verse" to try to understand the inner workings of authentication, but asking colleagues about direction did not help either.

So... a nextcloud spreadsheet? Airtable? I'm not that picky about what it is as long as it's searchable and filterable. Otherwise, it's a just a big useless mess of text

**Comment by YurkoWasHere** [comment]
Added `remember` commands to roobot
https://github.com/hyphacoop/matrix-roobot/pull/7

`!remember [topic] [messages]` - adds message to sheet under `topic` tab
`!remember_topics`  - returns tabs in sheet
`!remember_sheet` - returns link to sheet

TODO:
- [ ] Recall on time-span IE: `!recall topic time-span`
- [ ] Error better handling?
- [ ] ...

**Comment by writerly03** [comment]
Most of this work has moved into other issues and the Bot testing room in Matrix. I'm closing this issue as the new work supersedes this and Roobot is alive and mostly well
