### ISSUE TITLE
Dripline Matrix Post 

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/organizing#486]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

https://docs.google.com/document/d/17giec7MWFr_3mehE7h6VZvPO6rBhCLsSnkc7vdmVmz0/edit

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** Post published on Dripline 

...

## To Do

- [x] Elon to review post and add missing context/article 'so-what'
- [x] Andi to schedule call w/ Udit & Elon to close loop on edits
- [x] Posting process overview (Ben or Udit?)
- [x] Post!
