### ISSUE TITLE
Grants + Solidarity Work Nexus

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/organizing#493]
Reopening the IRP work, looking at other grants that are applicable, and assessing how we can add value to collectives and nonprofit organizations.
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** e/o April 2022  
🎯 **Success criteria:**  Plan in place for next IRP round, plus an outline of a solidarity (?) strategy for Hypha

...

## To Do

- [x] get updated information on next IRP round
- [x] do a scan for applicable grants
- [x] landscape scan for relevant areas/projects that Hypha could support

**Comment by writerly03** [comment]
IRP 2022

- All the details from the first round of applications https://github.com/hyphacoop/organizing-private/issues/92
- [Feedback](https://hackmd.io/aqxRqYuRRa6RTD4R723JSQ?view ) the unsuccessful round
-

**Comment by writerly03** [comment]
Sector Research

**Comment by writerly03** [comment]
Applied to the 2022 IRP round
