### ISSUE TITLE
Update Handbook Pages

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/organizing#495]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

...

### List of pages to edit

- [x] [About page](https://handbook.hypha.coop/co-operative.html#about-us): update intro blurb with new language from offerings deck; the *Non-Profit Act* is current legislation
- [x]  [Assets and templates](https://handbook.hypha.coop/look-and-feel.html): there are some missing assets in the Public Drive
- [x]  [Mission & Vision](https://handbook.hypha.coop/vision.html):update mission language?; update values list to the 5 key values by adding them in above current list

- [x] [By-laws](https://handbook.hypha.coop/bylaws.html): has anything changed since?
- [x] BOD & Member-Workers pages: any changes in the board or number of members? (Still 7, with 2 inactive but still members?)

- [x]  [Virtual Office](https://handbook.hypha.coop/onboarding.html): need to check links; onboarding checklist should be a checklist; service inventory is out of date or obsolete; change all Passbolt mentions to Bitwarden; add link to virtual pet
- [x] #496
- [ ] #497
- [ ] #498
- [x] #500
- Add in that lead is responsible for tracking hours
- Add in Operations Role; note that internal hours are managed by this person 
- [x] [Meetings](https://handbook.hypha.coop/meetings.html): needs a general refresh. Also, what happened to all hands meetings?!
- [x]  [Working Open](https://handbook.hypha.coop/working-open.html): might need a refresh to reflect that many meetings aren't open anymore
- [ ] #499
- [x]  [Fiscal Sponsoship](https://handbook.hypha.coop/fiscal-sponsorship.html): has any of this changed (on our side or the OC side?)
- [x]  [Holidays](https://handbook.hypha.coop/holidays.html): fix a few typos; update the calendar to 2022-2024
- [x]  [Novel Coronavirus](https://handbook.hypha.coop/coronavirus.html): update language, add in the resources/links that are currently on the website 
- [ ]  [Guides](https://handbook.hypha.coop/guides.html): remove or update content; email content is def out of date. Remove the out of date info and add in links to GSuite
[ ]  [How we use data](https://handbook.hypha.coop/data.html): some links are out of date; check copy to ensure it's current
- [ ]  [Reading Pool](https://handbook.hypha.coop/reading-pool.html): check that all links are still valid; add in some new resources - ask the larger team about adding in new stuff
- [ ]  [Glossary](https://handbook.hypha.coop/glossary.html): what about adding some additional terms relating to the DWeb?

**Comment by benhylau** [comment]
>[Fiscal Sponsoship](https://handbook.hypha.coop/fiscal-sponsorship.html): has any of this changed (on our side or the OC side?)

Checked off. No changes here.

**Comment by benhylau** [comment]
We should merge this with the current handbook ticket.
