### ISSUE TITLE
Onboarding Adrian Kiva

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/organizing#503]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

...

## To Do
New workers and contractors will provide...

- [x]     Preferred pronouns
- [x]     A permanent and/or mailing address
- [x]     A personal email for communications
- [x]     A google-friendly email address (this could be a prior personal address or a hypha email can be used once set up)
- [x]     A Signal-friendly number
- [x]     A Matrix account (feel free to register on the Toronto Mesh homeserver where Hypha rooms exist)
- [x]     A Github account
- [x]     For members and workers:
- [x]         Their Social Insurance Number (SIN)
- [ ]         Completed TD1 and TD1-ON forms

_____

### Set up contractor documents

   

- [x]  Prepare and provide an Independent Contractor Agreement outlining the service description, contractor relationship, including the Intellectual Property Agreement

- [ ] Set up employee documents, employee record and payroll

- [x]     Prepare and provide an Employee Acknowledgement outlining the job description, employment relationship, including the Intellectual Property Agreement

- [ ]     Collect information above and complete [employee record](https://link.hypha.coop/employees)
-
- [ ]     Add member SIN to BitWarden and share access with People Operations group. Change the member access to the entry as read-only, as this information is for recording keeping and the Member should not be able to modify it

- [ ]     Collect encrypted (see [Sensitive Data](https://handbook.hypha.coop/guides.html#sensitive-data) guide) [TD1 and TD1-ON forms](https://www.canada.ca/en/revenue-agency/services/forms-publications/td1-personal-tax-credits-returns.html) to [Drive](https://link.hypha.coop/drive)

- [x]     Add member to Clockify and [as Employee in Wagepoint](https://handbook.hypha.coop/guides.html#adding-a-new-employee) for payroll

## Set up communications

    
[ ] Add member to Signal hyphacoop (Emergency Channel) group

- [x] Invite member to Matrix spaces:

        Private chat #hyphacoop-private:tomesh.net
        Public chat #hyphacoop-open:tomesh.net
        Community +hyphacoop:tomesh.net

- [x] Set up a [hypha.coop email](https://link.hypha.coop/email) address:

          
Set up virtual office

- [x] Invite to [GitHub Organization](https://github.com/hyphacoop/) and add to Member-Workers [GitHub Team](https://link.hypha.coop/teams)

- [x] Add to [Google Drive](https://link.hypha.coop/drive) and invite to calendars:

        https://link.hypha.coop/calendar
        https://link.hypha.coop/availability
