### ISSUE TITLE
Prepare and host our third AGM in September 2022

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/organizing#507]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Related** #463  
🗣 **Loomio:** N/A  
📅 **Due date:** Planning deadline: September 12; AGM date: September 20th 
🎯 **Success criteria:** A thoroughly planned, enjoyable and engaging AGM! 

...

### 2022 AGM committee
@uditvira, @LexaMichaelides @writerly03  

## To Do

Everyone:

- [ ] draft [initial plan (incl. pre-work, requirements, outcomes)🔒](https://docs.google.com/document/d/1ns5Wz1XmYziznahyIuVBUbWG8IMS5_NO9OG9MioKO-g/edit#)
- [ ] finalize [agenda](https://docs.google.com/document/d/1ns5Wz1XmYziznahyIuVBUbWG8IMS5_NO9OG9MioKO-g/edit#heading=h.foffl0fg0rs2)
- [ ] update [year in review](https://docs.google.com/presentation/d/1yv9HsjXfXXvw6cJHxE9lpQqROnTDpzE-xCcl8KoE8T4/edit#slide=id.ge5c73bf1c0_1_77)

*A) Framing / Scoping (Udit lead; Lexa support)*

Finalize 2022 vision statement
Finalize 2022 Agenda

*B) Coordination (Lexa lead; Andi support)*

- [x] review requirements for AGM as noted in planning doc
- [x] finalize a date for our AGM  **Tuesday, September 20
   - [x] add to calendar and communicate Save the Date to folks (via Matrix)
   - [x] send official **notice of AGM/member's meeting with location**:  September 8th, 2022; [deadline is 10 days before meeting](https://handbook.hypha.coop/bylaws.html#3-member-meetings)
- [ ] Prepare pre-read facilitation/materials (anything that we want ppl to read before hand?)
- [ ] Email ppl with what's happening/ guidance for any initiative presentations/ meeting explainer
- [ ] Make sure finance has financial statements ready
- [ ] Make sure anyone presenting/leading a session is organized and prepared to do their thing

*C) Production (andi lead; Udit support)*

- [ ] Organize catered food and drinks
- [ ] Organize any workshop materials we may need
- [ ] Organize social activity

*Day-of*
- [ ] 🎉 run the meeting! 

**Sessions:**

Year in review: [presentation] Ben
Financial statements: [presentation] Yurko
Team building / values alignment: [casual workshop over lunch] Andi
Vision conversation [workshop] Udit
Strategy - [conversation] everyone talking (either Udit or Andi can facilitate, but should be pretty straightforward)
Budgeting - [workshop] (Ben or Yurko)

*Post-work*

- [ ] Schedule board meeting call; likely, September 21 (Udit)
- [ ] Create issues for any outstanding items generated during the AGM

**Comment by benhylau** [comment]
Pls see also https://github.com/hyphacoop/organizing-private/issues/217

**Comment by writerly03** [comment]
AGM is now over and follow-up items created as separate issues.
