### ISSUE TITLE
Get D&O insurance

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/organizing#512]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** Get D&O insurance forever.  

We have a Zensurance policy, but we wanted to add D&O insurance coverage:

https://drive.google.com/drive/u/0/folders/1-KdKst27_STVfu4aCg_1kEUwG113Eid_

@benhylau will send email thread to Rachael.

## To Do

- [x] Review form and add as much info as possible
- [x] collaborate on insurance doc with Ben & Yurko
- [x] pull 2022 YE financial statements
- [x] get doc signed
- [x] send to insurance contact
- [x] quote from Zensurance
- [x] assess quote 
- [x] sign off on new Insurance policy - @benhylau
- [x] Payment on new insurance - @rkashe

**Comment by rkashe** [comment]
@benhylau I got started with the form you sent me. I can see why you put off working on it because it is A LOT. I don't have enough information to fill out the entire thing, so will start tracking down the answers. I shared a link to it with you.

Management Liability application: https://dochub.com/rachael-g4trhu/eOLPG9YKjoQx5PvVZpXz6y/management-liability-application-can-v2-0-2-1-pdf?dt=4xxVxfyt66FzPExx5kJ3

**Comment by benhylau** [comment]
>- Employment Practices Liability
- Fiduciary Liability
- Cyber cover
- Crime cover

**Comment by rkashe** [comment]
I worked on filling out the rest of the form with Yurko & Ben. One final piece is getting a signature, and sending it off

**Comment by benhylau** [comment]
Signed!

**Comment by rkashe** [comment]
The form was sent off on April 10th. Waiting for a response from Insurance broker.

**Comment by rkashe** [comment]
I had an email back from Zensurance asking to confirm our account manager, and then follow up questions regarding changes in expected revenue, and changes to operations/services. I responded to these.

Next step: they will send us a quote for the insurance.

**Comment by rkashe** [comment]
Quote received, reviewed, and approved by Ben and Udit.

We are currently in the sign off stage, and I will make a payment once Ben signs off on the new paperwork.

**Comment by rkashe** [comment]
Update: More questions from the agent at Zensurance:

- they asked for clarification regarding the location of our contractors
- they asked for clarification regarding the mention of "loss of cryptocurrency" noted in our financial statements I shared with them as part of the application process

**Comment by rkashe** [comment]
Update: This is a message from Zensurance with the latest information from them. Also posted to Matrix for discussion

"Upon further review of your file the insurance company has advised that they have increased the premiums based on the contractors residing in California which they were not aware of previously.

The insurance company has also added a cryptocurrency exclusion clause: Losses arising directly or indirectly out of the development, use, offer, sale, purchase, or airdrop of any crypto asset, including cryptocurrency, utility tokens, security tokens, ecosystem tokens, or any other type of digital currency will not be covered.

The revised premium of the policy is $6,000, an extra $1000 on top of the $5000 that has already been paid.

I apologize for the inconvenience. Please do let me know if you have any questions or concerns and I would be happy to discuss them with you.

Let me know if you would like to proceed and I can send you an invoice for the extra $1000 payment. "

**Comment by rkashe** [comment]
Update from Zensurance in response to Ben's scenarios around crypto:

"Regarding the first scenarios, The D&O is provided to respond to claims made against your board or business for alleged wrongful acts or mismanagement such as breach of duty or mismanagement of funds. Your E&O or Professional Liability is meant to respond to claims of this nature. The crypto asset exclusion has been added specifically for your D&O coverage which would mean it exclude any claims that your business or board could be held liable for, on your own crypto assets. In short, you would be covered for this particular scenario as long as the claim does not arise out of the mismanagement of your crypto assets. 
 
An example of a claim that would not be covered would be a shareholders alleging breach of duty of care of the directors as a result of a significant loss on the cryptocurrency value they hold which has damaged your corporation.
 
Regarding the second scenario your Errors & Omissions or Professional Liability would provide coverage for the costs associated with any allegations or disputes of an error made through your work or potential misrepresentation and your D&O policy would cover you for any claims particularly made against a director for any wrongful acts. 
 
For contractors based in California , it increases the chance that claims may be brought under Californian jurisdiction. California is generally speaking a very litigious and plaintiff friendly State and defending claims brought in California can be several times more expensive than other US States or Canada. CFC's terms are on a worldwide basis (hence no coverage restriction in terms of where the claim is brought) and the definition of employee does include independent contractors. 
 
Please let me know if this cleared some things up and if you have any additional questions or concerns. "
