### ISSUE TITLE
Improve onboarding documentation

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/organizing#518]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

📅 Due date: N/A
🎯 Success criteria: Gather onboard resources and figure out how to improve onboard process.  

Several items were created to improve onboarding flow. We should centralize these resources:
- [Onboard email template](https://github.com/hyphacoop/organizing-private/blob/main/documents/operations/employee-onboard-email.md)
- [Stuff that Ops has to do to set up a new employee](https://github.com/hyphacoop/organizing-private/issues/264#issuecomment-1476880857)
- [Matrix sign-up](https://hackmd.io/@andia/S1iB5nEKq) that @writerly03 wrote
- [Add new employee](https://github.com/hyphacoop/handbook/pull/226) guide by Finance
- [Onboard doc for Denise](https://docs.google.com/document/d/12yUQWvMsuuU4zFfNNLtoNlV9q3IHtmo2JRsu4uJz_wA/edit?usp=sharing) by @uditvira 

## To Do

- [ ] Review by Operations group
- [ ] ...

**Comment by deniseyu** [comment]
I stumbled on this 😄  I basically wrote down every time I had to make an account or join something in the last 2 weeks. In case it's helpful:


To do by Onboarder

- [ ] Accounts setup
  - [ ] Invite to GitHub org
  - [ ] Invite to Bitwarden
  - [ ] Invite to shared Hypha gcal? (jk might be going away)
    - [ ] Ensure added to coffee chats, all-hands, recurring socials
  - [ ] Invite to Miro org
  - [ ] Share folders in GDrive
    - [ ] Initiatives (?)
  - [ ] Add to relevant channels in Element
    - [ ] Add to Element org? Not sure the lingo
  - [ ] Add to Hypha Coop Signal emergency contact group
  - [ ] Add to Airtable (?)
  - [ ] Invite to hyphahq Slack
  - [ ] Invite to social Discord
  - [ ] Invite to Digital Ocean
- [ ] Project
  - [ ] Add to project standups, syncs, any other recurring meetings
    - [ ] Add to project-specific Gmail distribution list, if exists
  - [ ] Add to project-specific GitHub repos and Google Drives
  - [ ] Add to sync notes (eg. Notion for Cosmos)
  - [ ] Add to Grafana (https://monitor.prod.hypha.coop/login) 
  - [ ] Add to relevant Telegram groups

Onboardee

- [ ] HR tasks (mostly covered in Ben’s email, not sure if need more systematizing)
  - [ ] Sign & submit tax withholding forms to Ben
  - [ ] Complete & send healthcare enrollment forms to provider
  - [ ] Send payroll information via email to Ben
  - [ ] Send SIN via Signal to Ben
- [ ] Accounts setup
  - [ ] Sign into your Hypha email
  - [ ] Create account with Element
    - [ ] Configure a profile picture
  - [ ] Create account with Bitwarden
    - [ ] Download Bitwarden Chrome extension
  - [ ] Create GitHub account, if needed
  - [ ] Create Discord account, if needed
  - [ ] Sign up for Telegram, if needed
  - [ ] Sign up for Signal, if needed
    - [ ] Recommended: After being added to emergency Signal group, save the contact details of at least the people on your team
  - [ ] Sign into Miro with Hypha email
- [ ] Optional admin
  - [ ] Set up your working hours in Google Calendar
- [ ] Social
  - [ ] Complete Miro board with your profile
  - [ ] Have a 1:1 with people on your project team

**Comment by rkashe** [comment]
I've pulled all of the information from this issue, and collected all of it into docs in Drive. Tracking this over in [issue 293](https://github.com/hyphacoop/organizing-private/issues/293)
