### ISSUE TITLE
DecentSocial OC fiscal hosting

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/organizing#533]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

📅 **Due date:** N/A  
🎯 **Success criteria:** Transfer DecentSocial to our OC.  

Hosting [DecentSocial](https://opencollective.com/decentsocial/), transferring over from Fission, another Canadian host.

## To Do

- [x] Submits an expense to DecentSocial for CAD 308.26
- [x] Submits an expense to DecentSocial 2023 event for CAD 1,635.24
- [x] Ian approves the expense
- [x] Fissions pays us
- [x] With a zero'd out balance, Ian now apply to switch to Hypha
- [x] Hypha approves DecentSocial, and transfers the money back to the collective

**Comment by benhylau** [comment]
<img width="1036" alt="Screen Shot 2024-07-02 at 11 11 08 PM" src="https://github.com/hyphacoop/organizing/assets/2261308/c21539b8-6700-469b-9e83-cc870b3b8804">
