### ISSUE TITLE
Set up a task tracker

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#66]
## Shared Description

🗣 **Loomio:** https://loomio.hypha.coop/d/ZIbOUBsi/tool-talk-task-tracker
🎯 **Success criteria:** Be running an experiment in using a task tracker, in a way that feels workable for all members.

## To Do

- [x] create proposals to surface sentiments (see Loomio thread) -- @patcon
- [x] make decision on tool to trial. Done: GitHub Projects!
- [x] collect/migrate #todo items into tracker (back until June 5) [dynalist](https://dynalist.io/d/cdVoKITQjayPFrSGb3-Zthe3) -- @patcon
- [x] ~~collect older #todos~~
- [x] investigate how issue templates work for project boards -- @patcon
- [x] solicit advice on labels -- @patcon 
- [x] add priority labels
- [x] remove spaces/symbols from label names
- [x] Reticket grooming session tasks
- [x] create issue template https://github.com/hyphacoop/organizing/pull/88
- [x] create shortlink: https://link.hypha.coop/new-task

**Comment by patcon** [comment]
Personal dynalist that patcon is using to: https://dynalist.io/d/cdVoKITQjayPFrSGb3-Zthe3 (Done back to June 5

**Comment by patcon** [comment]
Decided to not go back further than June 5

**Comment by patcon** [comment]
@dcwalk: was prev convo about grooming being by end of aug. and using that to inform org-wide PM role definition #73

**Comment by patcon** [comment]
feedback on labels:
@dcwalk: labels are easier with no spaces and no fancy characters
@benhylau shorthand acronyms? @dcwalk no need to be shorter :)

#todo migrate grooming to new ticket

**Comment by patcon** [comment]
## To re-ticket

- [ ] schedule grooming/feedback session -- @dcwalk 
- [ ] run session
- [ ] decide whether to commit to GitHub Projects

**Comment by patcon** [comment]
Also added an issue template and a shortlink for https://link.hypha.coop/new-task

**Comment by dcwalk** [comment]
All check boxes are check, this was reticketed (#87) and the template was merged. I'm closing for now, feel free to reopen if there are any lingering todos
