### ISSUE TITLE
Find accounting services

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#70]
## Shared Description

🗣 **Loomio:** https://loomio.hypha.coop/d/7Dp6TQfg/select-an-accountant
:date: **Due date:** Wed, Aug 14

Candidates worker co-ops for advice:
- ✅ Brierwood Co-op, Ottawa (tech, apps)
- ✅ MOSS Digital, London (tech, websites)
- Urbane Cycle, Toronto (bikes)
- ✅ Fourth Pig, GTA (nonprofit, construction, accountant founding member)
- ✅ [Come As You Are](https://www.comeasyouare.com/pages/about-us), Toronto (sex shop)
- [Libra](http://www.libraknowledgeinfo.net/whoweare.html), Toronto (knowledge management)

## To Do

- [x] solicit recommendations from CWCF (PYC recommended)
- [x] Email Prentice Yates & Clark (PYC) -- @benhylau
  - no response
- [x] Email Dionne Reid of PYC directly
- [x] ~~Contact Williams, Payne & Associates (WPA)~~`wont-do`
  - [x] Find email contact: wpa@bellnet.ca
  - [x] ~~Call WPA: 905-953-1144 x 305~~ `wont-do`
- [x] Call Gordon Holley, [Humanity Financial Management](https://www.humanityfinancial.ca/contact/)
- [x] contact matt@fourthpig
  - [x] share back [done](https://loomio.hypha.coop/d/7Dp6TQfg/select-an-accountant/19)
  - [x] contact CHIRAG DESAI, accountant
    - [x] call (Aug ~~20~~ 21). busy.
    - [x] share back
  - [x] ~~contact urbane cycle to ask for accountant~~ `wont-do`
- [x] email info@comeasyouare.com
  - [x] share back
  - [x] contact accountant, Hema Murdock: hema@hemamurdock.ca
    - [x] call (Tue, Aug 20) [done.](https://hackmd.io/m5xT18KQS-KK6jbMKWEpsQ?view)
    - [x] call, to be cont. (Aug. 21)
    - [x] share back
  - [x] contact bookkeeper, Rodica Butean: r************@yahoo.com
    - [x] call (Tue, Aug 20). [done.](https://hackmd.io/m5xT18KQS-KK6jbMKWEpsQ?view)
    - [x] share back
- [x] contact brierwood coop. ~~bumped thread. still waiting.~~ heard back.
  - [x] share back
  - [x] create informational interview ticket https://github.com/hyphacoop/organizing/issues/70
- [x] do call with LiveCA. done: [loomio.](https://loomio.hypha.coop/d/7Dp6TQfg/select-an-accountant-and-or-bookkeeper/32) [notes.](https://hackmd.io/hI3Pt6peThKK10K2kefmTg)
  - [x] contact Varun @ Think Accounting
    - [x] video call (Aug ~~20~~ 21). rescheduled.
    - [x] share back
- [x] contact moss digital
  - [x] share back
- [x] Contact [Kevin Sampath](https://www.linkedin.com/in/kevinsampath/) :books: on Twitter. [done.](https://twitter.com/patconnolly/status/1163340506862166017)
  - [x] ~~email~~
- [x] Draft proposal. [done.](https://docs.google.com/document/d/1Ssta21Cq88_X47mjikQR9F3xz9FaYLH0m32uB2MjqnY/edit#)
  - [x] offer for review
  - [x] member vote to approve (Wed, Sept 4, 2019)
- [x] initiate accountant relationship with Hema
  - [x] email new accountant
  - [x] schedule kickoff meeting. TUE OCT 1 (in calendar)
  - [x] prepare for meeting
    - [x] create stub [meeting notes](https://hackmd.io/@patcon/ryMxS3okB/https%3A%2F%2Fhackmd.io%2F716xTfHcQ-CSzwmcYgmtjw%3Fview?type=book)
    - [x] ~~review [letter of engagement](https://drive.google.com/file/d/0B2riIxpG2GHEd21fSTBrOVJTSWdUZUJUM2Z5U1IwMHBuSElZ/view?usp=sharing)~~ 🔒 `deferred`
    - [x] aggregate outstanding questions (see notes)
  - [x] attend kickoff meeting
  - [x] ~~sign/deliver letter of engagement~~ `deferred`
  - [x] ~~store copy in gdrive~~ `deferred`
- [x] decline other candidates via email (Chirag, Varun)
- [x] email Rodica to tentatively express interest and defer engagement
- [x] ~~define role to manage relationship~~ reticketed: #121
- [x] wrap up
  - [x] thank-you email to CAYA co-op
  - [x] re-ticket todos from [meeting notes](https://hackmd.io/@patcon/ryMxS3okB/https%3A%2F%2Fhackmd.io%2F716xTfHcQ-CSzwmcYgmtjw%3Fview?type=book) and `deferred` actions

**Backup Options**
- #discuss willingness to work with "inexperienced" accountant who's passionate about new economy
- Email Girl Guides of Canada contact, Louise Kent (Director, Member Experience), to get Andrea's 💰 contact info
- Contact [Andrea Tsang](https://www.linkedin.com/in/andreachiutsang/), Financial Director of CSI, to ask about modern accounting firms via CSI
- Contact Jenny Yan 💰

**Comment by patcon** [comment]
We should reach out to other ON tech worker co-ops to ask:

Brierwood.coop: info@brierwoodapps.com

**Comment by patcon** [comment]
Reached out to brierwood for kicks. Because why not -- just copy-paste ;)

**Comment by patcon** [comment]
Emails sent out to _actual_ accountants/bookkeepers this weekend, and hoping to hear back this week with some bites by mid-week.

**Comment by patcon** [comment]
Added steps related to approval and proposal to #todos

**Comment by patcon** [comment]
#todo contact Hema (and accountants we didn't go with)
#todo connect Ben with Hema

**Comment by patcon** [comment]
Called Hema for next steps. She asked:
- Write her sharing corp name, contact details. #todo
- She'll send us a letter that we can sign and return to engage.
- She'll invoice us after work performed. (not retainer)
- I'll suggest timee range for a kickoff. She prefers in-person, but can do video. One or multiple of us may attend. #todo
- She confirmed Rodica is great bookkeeper (same one as CAYA Co-op). They've worked together for years. Not-for-profit will be new to her. External, but supports us using her services, when we want a bookkeeper. DIY also ok if we'd like. Hema is not of strong opinion on bookkeeping arrangements.
  - My suggestion: We email Rodica to let her know that we plan to contact her when we feel the need for an external bookkeeper, but we might do it ourselves for the first few months. We can ask further advice about this during kick-off meeting with Hema. #todo

**Comment by patcon** [comment]
We have a #todo for "define role to manage accountant relationship". This may be related to treasurer https://github.com/hyphacoop/organizing/issues/99#issuecomment-531844354 cc @dcwalk

**Comment by patcon** [comment]
Last time, she immediately replied to say she was sick, and said she'd followup when she got back to office. I have not heard from here.

I sent another note expressing that we were feeling blocked, and I'm hoping her website's commitment to "24-hour" response will hold from here on out.

**Comment by patcon** [comment]
Heard back from Hema. She needs to know of desired fiscal year-end.

Considerations here: https://www.liveca.ca/how-do-i-choose-my-fiscal-year-end/

Summary:
- we must set it 52 weeks from incorp (Aug 1)
- corporate taxes due with 3 months of it passing
- recommendation: put it as far away as possible, but at end of month (e.g., July 31)
- adjust to avoid busy season (will aug/sept/Oct be busy time where filing is inconvenient?)

**Comment by patcon** [comment]
Reply sent. Set fiscal year end for June 30. Requested in-person kickoff meeting for Tues/Wed next week. (@benhylau and @patcon in attendance, and others who speak up)

**Comment by patcon** [comment]
received reply and agreement for review. locked kick-off meeting date (see thread-starter).

@hyphacoop/finance-wg could use eyes reviewing/commenting on agreement (linked above)

**Comment by patcon** [comment]
Just a point of correction from an earlier comment I made **about repercussions of choosing the fiscal year**: Under the _ON Co-op Act_, we have NO responsibility to run the AGM within a specific timeframe of fiscal year-end (unlike _Canadian Business Corp Act_, which [has opinions about it being within 6 mo](https://corporationscanada.ic.gc.ca/eic/site/cd-dgc.nsf/eng/cs06644.html#toc-03.02)).

It's simply that soon after is a good time to run it, since the financial picture will be as complete as it gets.

**Comment by patcon** [comment]
Moving "finance role definition" into its own issue.

**Comment by patcon** [comment]
Aaaaand I think we're good to close this long-standing issue! We have an accountant and had our first meeting! 🎉
