### ISSUE TITLE
Complete initial business plan

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/organizing#85]
## Shared Description

:speaking_head: **Loomio:** https://loomio.hypha.coop/d/Vi0YSIx4/business-plan-writing  
:date: **Due date:** N/A  
:dart: **Success criteria:** Publish a vetted final business plan.

This was raised (by @dcwalk?) in `2019-05-27` and  `2019-06-05` all hands meetings. Research was set as next task.

Note: Not currently intended to include content changes beyond minimal.

## To Do

- re: [business plan template](https://hackmd.io/K2LkrA36RDmwNwTfMZocMA?view#Business-Plan-Template) from 2019-02-08 cowork
  - [x] draft two-tweet-per-item business plan 
       section 1☑ 2☑ 3☑ 4☑
  - [x] discuss sec 5☑ at all-hands
- [x] reconvene and discuss/refine draft
- [x] move to [Google Doc for final drafting](https://docs.google.com/document/d/1U8C1XZcDpu1r4ciecbKEZ6vOL41nTinfqPCbZDhkAWc/edit#heading=h.vkvqdubed56i)
- [x] share/discuss draft at All Hands
- [x] review current state and identify todos
  - [x] Add examples of language from other studios by [competitive positioning](https://docs.google.com/document/d/1U8C1XZcDpu1r4ciecbKEZ6vOL41nTinfqPCbZDhkAWc/edit#heading=h.ndof266taab4) @uditvira 
  - ~Review and propose thicker approach to procurement / suppliers / tools and our values section~ (only reviewed!)
  - [x] Add in/formally document our sweat equity practice (documented in loomio thread/elsewhere)
  - [x] Draft [strategic plan](https://docs.google.com/document/d/1U8C1XZcDpu1r4ciecbKEZ6vOL41nTinfqPCbZDhkAWc/edit#heading=h.wqdyvqvcxfm6) for discussion @dcwalk
  - [x] Draft [financial projections](https://docs.google.com/document/d/1U8C1XZcDpu1r4ciecbKEZ6vOL41nTinfqPCbZDhkAWc/edit#heading=h.ih5hiognhvi8): income/loss statement and balance sheet for discussion @benhylau 
- [x] wg meetings to discuss and finalize
  - [x] book work session \#2 SEPT 25
  - [x] run work session \#2
  - [x] book work session \#3
  - [x] run work session \#3
- [x] spin out issues / cross-references from business plan
  - [x] review doc to pull into gh issues
  - [x] PRs into handbook of key definitions
- [x] final edit for clarity
- [x] discuss and consense on initial business plan at working group
- **parked** discuss and consense on initial business plan at all hands
- **parked** seek review from [a local small business development centre](https://loomio.hypha.coop/d/sWnNveKO/public-communication-spaces#undefinedsmall-business-development-centres)
- [x] make snapshot PDF
- [x] share out with broader group informally

**Comment by patcon** [comment]
I'd suggest adding the following todos:
- [ ] assign a single owner/steward for this issue
- [ ] seek round of free feedback from [a local small business development centre](https://loomio.hypha.coop/d/sWnNveKO/public-communication-spaces#undefinedsmall-business-development-centres)

**Comment by patcon** [comment]
@dcwalk suggested meeting one more time

**Comment by patcon** [comment]
@uditvira suggested week of sept 22

**Comment by patcon** [comment]
booked date in calendar for wed sept 25

@dcwalk will plan

**Comment by dcwalk** [comment]
Updated the todos at the told based on review and sent out an email: 

```

Hi Businessfolks,

...

I am proposing the following approach:

1. We each take on one-two below todos and draft something to bring to
our meeting and discuss
2. We meet! Sept 25 and:
  - work through the comments still open in the doc and resolve,
itemized #todos as needed (looks like very few will linger after we discuss)
  - discuss the larger todos we'll have done in advance (I think 2-3
will linger and we should confirm how to handle. The might stay as a
"snapshot" in business plan but be broken out for further refinement)

So, that said, here are those TODOs (last two more substantial):

- Add examples of language from other studios by competitive positioning
- Review and propose thicker approach to procurement / suppliers / tools
and our values section
- Add in/formally document our sweat equity practice (documented in
loomio thread/elsewhere)
- Draft strategic plan for discussion @dcwalk
- Draft financial projections: income/loss statement and balance sheet
for discussion

This is all in the gh issue, can people either respond here with the
ones they are taking, or update the gh issue? We should confirm by
Wednesday.
```

**Comment by patcon** [comment]
I've converted some tasks into checkboxes, added a task for the business centre review )that got a +1 and no dissent_, and also added "meeting booking" #todos so we keep tabs on those next steps/progress.

If the above is assuming too much, pls do say so!

**Comment by patcon** [comment]
## Suggested To Do
- [ ] spin out issues / cross-references from business plan

**Comment by dcwalk** [comment]
I'm switching the consult on business plan with a centre to stretch, as I think that might be more effective as we move into a second iteration (refinement) during the lead up to AGM, bylaws sometime Q1 2020.

I also don't think it should be a block on us "completing" the business plan as it stands.

@hyphacoop/business-planning-wg I'm asking you all, in particular @benhylau as there are open comments in your section... to to a final review this week. I'll aim to closeout edits and distribute for a final readthrough by this weekend.

**Comment by benhylau** [comment]
Approved all edits, thanks @dcwalk

**Comment by dcwalk** [comment]
Had a meeting 2019-12-12 as @hyphacoop/business-planning-wg, we agreed:

- accurate reflection of our collective planning
- give the doc a rest until AGM
- consult with external group closer to AGM 
  - (if any feedback from agencies than we can incorporate later)
- make a snapshot document (PDF), store in private doc
- share out broader with group informally, aim for formal distribution/discussion at AGM

**Comment by dcwalk** [comment]
Closing this out as completed! :tada: 🧟
