### ISSUE TITLE
Set up time tracking

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/organizing#86]
🗣 **Loomio:** https://loomio.hypha.coop/d/iE1VYzgZ/tool-talk-time-tracking
📅 **Due by:** Aug 23, 2019
🎯 **Success definition:** See Loomio check.

# To Do
- [x] [wrap up loomio check](https://loomio.hypha.coop/p/O8bMgpA5/i-am-clockified)
  - [x] get hours back to beginning into clockify
    - [x] @garrying 
    - [x] @patcon 
    - [x] @ASoTNetworks 
    - [x] @benhylau 
    - [x] @dcwalk 
    - [x] @uditvira 
    - [x] @YurkoWasHere
  - [x] get clockified
    - [x] @garrying 
    - [x] @patcon 
      - [x] jan - july
      - [x] july onward
      - [x] back-fill billable digital coaching
    - [x] @ASoTNetworks 
    - [x] @benhylau 
    - [x] @dcwalk 
    - [x] @uditvira 
    - [x] @YurkoWasHere

**Comment by YurkoWasHere** [comment]
@benhylau @dcwalk @elon @YurkoWasHere  @patcon  seem to have joined clockify as of now.

**Comment by benhylau** [comment]
But who's using it? Heh! I will start using it now.

**Comment by benhylau** [comment]
I have entered my time from beginning of June and am set up to use Clockify from my phone!

**Comment by patcon** [comment]
You didn't have Aether set to "Public" access, so only owners could see it, I think:
![Screen Shot 2019-08-09 at 1 14 05 AM](https://user-images.githubusercontent.com/305339/62755691-13d7dd80-ba43-11e9-9731-0bddde7f2daf.png)

Fixed. (Clicked project, checked "public" at top.)

Is this just ppl getting on, or getting our time-tracker tool totally setup and signed-off? If whole setup, then what does that involve? To start a scratch list:

- going through all default config
- dropping notes on handbook sections this will involve; maybe reticketing another issue for eventually writing handbook section.
  - how to create/config a new project
  - how to add a new client

**Comment by patcon** [comment]
Proposal: Start running a biweekly check to ask people who've committed to using clockify to update their timesheets if they aren't doing it directly in clockify (dc and i use our own tracking app i believe). That way, we'll be doing this correctly when payroll happens -- no lazy habits

**Comment by patcon** [comment]
> I have entered my time from beginning of June

Do you have time further back logged?

**Comment by benhylau** [comment]
I have created a poll here to track who is fully set up: https://loomio.hypha.coop/p/O8bMgpA5/i-am-clockified

**Comment by patcon** [comment]
Suggested todo's to add [re: Loomio comment](https://loomio.hypha.coop/d/iE1VYzgZ/tool-talk-time-tracking/9)

- [ ] Discuss "time minder" role in meeting
- [ ] Define role (and how long it's held)
- [ ] Approve and vote someone in
- [ ] Add to handbook
- [ ] Create gcal event to re-assign?

**Comment by patcon** [comment]
In [`2019-08-14` infra & ops meeting](https://hackmd.io/@patcon/ryMxS3okB/https%3A%2F%2Fhackmd.io%2F4sJvq3CdR52ZxVuPjuiipA%3Fview?type=book), we:
- discussed time-tracker role
  - realized more general discussion was needed on size and scope of all roles
  - discussed potential accountabilities related to time-tracking (though may be part of larger role, bundled with finances)
  - @uditvira taking over this issue
    - will help everyone gets on Clockify
    - will help everyone get backlog of hours into Clockify before loomio check expires
  - definition of time-tracker role extracted into new issue (see cross-ref above)

**Comment by patcon** [comment]
I'm up-to-date and I've created a personal weekly calendar event to transfer my hours to clockify. If others want to commit to something comparable, we could move that in the shared calendar as a collective agreement. That convo could also be kicked to https://github.com/hyphacoop/organizing/issues/121

@uditvira you still able to own the task? If so, do you need any support from anyone to move it forward? :)

**Comment by benhylau** [comment]
Added [comment about using tags](https://loomio.hypha.coop/d/iE1VYzgZ/tool-talk-time-tracking/35) and shared practice. I feel it could be part of this task?

@uditvira you seem busy, can I take this task from you?

**Comment by dcwalk** [comment]
This is done! Not sure why this isn't closed, so closing.
