### ISSUE TITLE
Task tracker grooming/feedback session

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#87]
Re-ticketed from https://github.com/hyphacoop/organizing/issues/66#issuecomment-519278044

## Shared Description

🗣 **Loomio:** https://loomio.hypha.coop/d/ZIbOUBsi/tool-talk-task-tracker
🎯 **Success criteria:** ...

- Due: end of Aug.
- Should inform org-wide project manager role definition: #73

## To Do

- [x] host test session in infra and share notes in this issue
- [x] schedule grooming/feedback session
- [x] run session
- [ ] decide whether to commit to GitHub Projects

**Comment by dcwalk** [comment]
We did a mini-grooming sesh in the 2019-09-11 infra conversation and these were the steps we took:

- Start on doing, discussed more in depth, updated checklists, and moved from stack
    - Odoo, one sentence on what problem it will solve? 
- Moved to todo, added in prioritizing / block labelling 
- Did a quick review of backlog, some belong there, others don't 
    - Some discussion of whether or what label fits, "blocked"? "not yet due"?
- Took approx. 25 mins
- Reflection
    - Chair / one person grooms backlog rather than us all collectively?

**Comment by dcwalk** [comment]
Just picking up on this thread -- it seems we've integrated Github Projects and regular grooming into our task flow after those initial sessions. I'm inclined to close this out as we have a process check-in most calls.

Will close, but if someone from @hyphacoop/infra-ops-wg sees a need for this to stay open please re-open!
