### ISSUE TITLE
Decide on role for time-tracking related stuff

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#97]
Re-ticketed from https://github.com/hyphacoop/organizing/issues/86#issuecomment-521451204

📅 **Due date:** early-Q3 2020
🗣 **Loomio:** https://loomio.hypha.coop/d/iE1VYzgZ/tool-talk-time-tracking

# To Do
- [x] discuss premise of time-tracker role at `2019-08-14` infra&ops meeting. [notes](https://hackmd.io/@patcon/ryMxS3okB/https%3A%2F%2Fhackmd.io%2F4sJvq3CdR52ZxVuPjuiipA%3Fview?type=book)
- [ ] surface expectations on size/scope of roles [loomio?] (`2019-08-14` infra meeting convo)
- [ ] optional: create time-tracker role (or larger scoped role)

**Comment by patcon** [comment]
Related: https://github.com/hyphacoop/organizing/issues/86#issuecomment-520090481

**Comment by patcon** [comment]
As per points raised by @dcwalk and supported by others, we need to discuss size/scope of roles we want. Adding #todo for running that convo in loomio

**Comment by patcon** [comment]
in 2019-08-04 all-hands meeting, dc asked for a way to sync up on how we're rounding time tracking. not a fan of to-the-second tracking

**Comment by dcwalk** [comment]
Picking up conversation on Sep 04, 2019 All hands --> Can we make a decision on rounding in terms of how we bill / invoice and aggregate our time?

**Comment by patcon** [comment]
To clarify, this is just a lower-bound expectation of granularity, right?

Like if I happen to track more specifically, I don't need to put in extra effort to round up/down -- I can just mindlessly enter my exact and be done with it?

**Comment by dcwalk** [comment]
2019-01-29 we acknowledged in gov / ops meeting that we'll pick up the conversation of roles and this is one of 'em!

**Comment by benhylau** [comment]
We should do some accounting on where people are spending our time, and probably involves "a task assigned to a person" whether this is a distinct role or part of the responsibility of another role, TBD.

Timeline can be early-Q3 2020?

**Comment by patcon** [comment]
Closed after convo in ops wg meeting about it not moving forward for a year
